### ISSUE TITLE
Host crashes don't always list the function name 

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-host#1318]
When getting host crash loops (such as the X.509 Service Bus issue), we don't tell customers which function is the issue, which causes the host to crash when starting Service Bus Trigger.

We need to improve both the red bubble error and include the info in the host log.

**Comment by christopheranderson** [comment]
@mamaso - will your fix improve this by preventing crashes?

**Comment by mamaso** [comment]
My fix works for listener startup, i.e. connecting to blob service, which was a problem because it occurs outside of function execution.

I'm surprised that failures during triggers aren't propagated down the pipe, that's more along the line of per-execution. I'll set up a throwing trigger and if necessary hook up the exception routing to script

**Comment by lindydonna** [comment]
@mamaso See email thread with more details, title is "Functions certificate error in popup that isn't logged in host"

**Comment by mamaso** [comment]
This happens because the service bus listener follows a different pattern - it registers a message handler synchronously, so listener errors do not occur in the context of StartAsync().

We could create `MessageOptions.ExceptionReceived` handler, but it seems hard to get to a context where we can pass the exception through the tracewriter pipeline

**Comment by pragnagopa** [comment]
Closing as the fix is checked it in the referenced PR.
