### ISSUE TITLE
Intermittent lag in function processing of events from EventHubs

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-functions-host#1322]
In some scenarios, we are seeing intermittent lag where a particular worker seems to fall behind, resulting in long processing delays.

We need to isolate and get to the bottom of it.

**Comment by paulbatum** [comment]
I'm still investigating, there appears to be several different issues that contribute to this overall problem. I've captured notes on one of the issues - see https://github.com/Azure/azure-webjobs-sdk/issues/1111.

**Comment by paulbatum** [comment]
Closing this old issue that was not updated once we concluded the investigation.

In addition to the issue mentioned above, we also determined that a significant amount of the lag was due to inefficencies incurred when running in single dispatch mode (i.e. one function execution per event hub message). Switching to batched mode addressed this.
