### ISSUE TITLE
Using Azure Functions written in PowerShell in production

### ISSUE THREAD

**Issue by KirkMunro** [Azure/azure-functions-host#1566]
@tohling: I have some important questions about how the PowerShell support will evolve within Azure Functions.

I have successfully implemented one solution using Azure Functions that solves a pain point at a company I work for. We would like to take that solution and put it into production. I am also getting started on some additional solutions right away. I know the current status of PowerShell support is experimental and therefore subject to significant change, so I need to assess the level of risk I would be taking to use these solutions in production. How do you plan to evolve the PowerShell support that is in Azure Functions today? What plans or channels do you have in place to communicate changes with customers who are using the experimental PowerShell support in production?

I've been involved in a number of TAP programs over the years, so I can deal with changes, as long as I know what is coming so that I can plan accordingly (if there is a TAP program for this, I would be interested in getting involved in it). Do you have a rough timeline or roadmap with milestones for this feature set that you can share?

Please let me know as soon as possible. We can also take this discussion offline if you prefer.

Thank you.

**Comment by tohling** [comment]
@KirkMunro, thank you for reaching out to us regarding this issue.  We have placed PowerShell support under experimental mode to gauge the level of interest from customers wanting to run PowerShell in Azure Functions.  We really appreciate the feedback that you and other users have provided so far.  Your expertise and input is very valuable to us and we have started the process of evaluating the information we have gathered.  

Because Azure Functions workloads run in a multi-tenant environment, a critical premium is placed on ensuring that all Function executions operate within the boundaries of our security model.  As such, the Function host process runs within a sandboxed environment.  Many PowerShell workflows operate with the assumption that they have system-wide access to host settings and resources.  We will need time to evaluate the wish list and investigate the viability of achieving parity with your typical PowerShell experience.  Our team will be working through this list and plan to update this thread by the end of this month with our progress.

In the meantime,  we do not recommend that our customers take a dependency on running PowerShell Functions in production scenarios.  For production tasks, we highly recommend using Azure Automation.

**Comment by tohling** [comment]
We will be starting an investigation to explore an alternative path for supporting PowerShell in Azure Functions.  We are very motivated to improve the customer experience with PowerShell and will work towards getting PowerShell support to run production workloads.  This work will commence in July and we will update this thread as soon as we have more information.

**Comment by jmuthuku** [comment]
Any update on this. I still see Powershell as Experimental in the Azure Portal when creating Azure Functions.

**Comment by tohling** [comment]
@jmuthuku , kindly see an updated comment by @asavaritayal here https://github.com/Azure/Azure-Functions/issues/585#issuecomment-424014397

**Comment by Francisco-Gamino** [comment]
PowerShell in Azure Functions GA-ed on November 2019, and it is available in both V2 and V3. For more information, please see https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-powershell. Closing issue.
