### ISSUE TITLE
Please upgrade the default version of AzureRM modules

### ISSUE THREAD

**Issue by KirkMunro** [Azure/azure-functions-host#1932]
The default version of the AzureRM PowerShell modules installed on Azure Function deployments is very old. For AzureRM.Storage, version 1.1 is installed. The current version of that module is 3.3.1. Please update the version of AzureRM PowerShell that is installed on Azure Function deployments. If you cannot, then provide an option to allow Azure Function App managers to choose the version of AzureRM that should be installed by default. With the speed of new features being added in Azure, and the amount of change in the AzureRM PowerShell modules, the version you are using is horribly out of date.

Note: This applies to C# Azure Functions as well (I have multiple C# functions written that internally invoke PowerShell).

#### Investigative information

Please provide the following:

- Timestamp: 2017-09-21T17:37:06.760
- Invocation ID: 7fbcf816-455a-49e0-bfbe-0d93cda1d814
- Region: South Central US

#### Repro steps

Provide the steps required to reproduce the problem:

Try to get the EnableHttpsTrafficOnly flag on a storage account in Microsoft Azure using the Get-AzureRmStorageAccount cmdlet.

#### Expected behavior

The resulting objects should have the EnableHttpsTrafficOnly property on them, with a value.

#### Actual behavior

The property is not there because the version of AzureRM you are using is very, very, very old.

#### Known workarounds

Manually upload the AzureRM bundle you need into the Azure Function App. Place all AzureRM modules in one folder, and add that folder path to $env:PSModulePath.

#### Related information 

Version compatibility is a potential challenge here, because there may be published functions that are tested as working with the existing installed version, and that may break with an upgrade to the AzureRM module bundle. As long as the base version of PowerShell is less than 5 (meaning that you don't have side-by-side version compatibility for modules), you will need to be careful of this; however, it is possible to maintain compatibility while allowing customers to use the latest version, even on PowerShell 4.

For example, you could create packages of AzureRM that are built from versions of AzureRM published to the Gallery, with each package versioned according to the version of AzureRM itself, and then include an option in an Azure Function to use a specific version of AzureRM. Behind the scenes, all you would then need to do is deploy the appropriate package for that function, and modify $env:PSModulePath in the process in which that function runs so that it uses the right version of AzureRM. Existing functions would default to the currently installed version since they wouldn't have this configuration set, and new functions could be configured automatically to default to the latest version. I would take this approach for every non-core PowerShell module that is installed on the servers used to run Azure Functions.

**Comment by gavinwoolley** [comment]
Any updates on this...

**Comment by paulbatum** [comment]
We don't have any plans to address this in the near future. See [here](https://docs.microsoft.com/en-us/azure/azure-functions/supported-languages) for the current status and guidance on PowerShell in Azure Functions.

**Comment by bergmeister** [comment]
This is a bummer for me as well because I have to FTP the required AzureRM modules up in order to use the latest features.

**Comment by KirkMunro** [comment]
@paulbatum Updating AzureRM in the Azure Function package has nothing to do with the lack of PowerShell on the Azure Function roadmap. You can invoke PowerShell from C#. C# functions are supported.

There is an AzureRM module package in the Azure Function payload, but it is quite old. You can manually update, but that is a pain. Don't use the lack of support for Azure Functions written in PowerShell as an excuse to keep the AzureRM module package old and crusty in Azure Functions.

**Comment by paulbatum** [comment]
The azure functions payload does not include AzureRM. Its actually installed on every App Service worker. You can confirm this yourself with these steps:

1. Navigate to: https://<appname>.scm.azurewebsites.net/DebugConsole
2. Run `dir "D:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager"`

When you do this exercise, you'll notice that there is no versioning here. And since its installed on the worker, any customer of App Service could be relying on this. That includes non functions users. So any change here could be breaking.

It is apparent that when this work was done, no thought was put in to versioning. This is extremely unfortunate because it makes any further work here even more difficult. 

In theory we could do some additional work to include a more recent version of AzureRM in the functions payload itself, and provide a functions specific setting that allows the user to opt into using that newer payload. But this would represent significant investment in the powershell experience for Azure Functions in V1 and as I've tried to communicate already, we consider that support experimental and we're not investing in it further.

Now that I've explained how the version of AzureRM exposed to you is provided by App Service and not functions specifically, I would encourage you to direct further feedback about the default version of AzureRM in App Service to the [App Service User Voice](https://feedback.azure.com/forums/169385-web-apps).

**Comment by Francisco-Gamino** [comment]
Hi @KirkMunro,

Do you still need AzureRM support in Functions? If you do, you could take a look https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell#dependency-management. This feature is available for PowerShell function apps. When you turn this feature on, we ensure that your function app has the latest dependencies up to date, including the `Az` module.

Thanks,
Francisco
