### ISSUE TITLE
Proxies: Complex route regexes only partially work

### ISSUE THREAD

**Issue by StephenCleary** [Azure/azure-functions-host#1988]
When using a proxy with a route set to something like `{prefix:regex((?!api$)^.*$)}/{*bob}`, it correctly matches the route and executes the proxy code, but the proxy doesn't execute correctly.

The example `{prefix:regex((?!api$)^.*$)}/{*bob}` is an attempt to forward all URLs that start with a prefix *other* than `api` to a specific backend URL. The WebAPI understanding of the routes does work (`/api/hello` is handled by a function not going through a proxy, and a request for `/bob` will write `Executing request via Azure Function Proxies` to AI). However, the proxy always returns `{ "statusCode": 404, "message": "Resource not found" }` instead of calling the backend URI.

This is using proxies preview 0.3.

- Timestamp: 2017-10-02 9:58:10 PM EST
- Function App name: dotnetapis2
- Function name(s) (as appropriate):
- Invocation ID: d7c393d6-723c-40df-bbbb-4b01d4a47003
- Region: North Central US

**Comment by SimonLuckenuik** [comment]
If you forward directly "http://httpbin.org/get" does it works? (just to isolate the source of the error message). Since you have the trailing slash mandatory in your rule, try '/bob/' instead of '/bob.

**Comment by sinapis** [comment]
I believe I face the same issue. Here are my proxies:

{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {

    "files": {
      "matchCondition": {
        "route": "/frontend/{filePath:regex(^[^.]*.[^.]*$)}"
      },
      "backendUri": "https://someblob.blob.core.windows.net/frontend/{filePath}"
    },
    "notfiles": {
      "matchCondition": {
        "route": "{root:regex(^[^.]*$)}"
      },
      "backendUri": "https://someblob.blob.core.windows.net/frontend/index.html"
    }
  }
}

I'm hosting a SPA inside frontend container. If I detect extension in route, I assume it's a file and I fetch it from container. Otherwise, it's an HTML5 route, so I call index.html.

The first rule works, but the second returns 404 Not Found in most cases, but not all (simply typing / does work, all others routes i tested do not). Note that when route is trying to access non existent blob, an XML is returned with the message "The specified blob does not exist", so the 404 I'm getting is from Azure Function Proxies.

Is this a bug? there a workaround? Is there a log where I can see how Azure Functions Proxies handled the request - i.e. request with route x was redirected to backend y?

**Comment by securityvoid** [comment]
@SimonLuckenuik FYI, I tried the calls to http://httpbin.org/get and I get the same results as the other people above. 

I am trying to do the same exact thing as @StephenCleary . I want to be able to host my static content from Azure Storage blobs, and my API on Azure Functions. As a result I want everything that DOESN'T match /api to be sent to grab the content from a certain storage container.

Since this is a very logical setup there should be an easy way to do this.

I'm open to suggestions since this way doesn't work. 

Is there a way to setup a proxy match that will send something to the function by way the proxy is, and then I can have a lower priority proxy that sends everything else to Azure Storage?

Any other possible work arounds?

**Comment by securityvoid** [comment]
In case its needed, this is my sample proxies.json:

```
{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "test": {
      "matchCondition": {
        "route": "{sendOver:regex(^\/(?!api).*$/)}"
      },
      "backendUri": "http://httpbin.org/get"
    }
  }
}
```

**Comment by fperreaultnv** [comment]
@securityvoid The regex above does not seem to be working for me.

It also seems that this regex would capture paths like /apiculture/, or any route fragment that would start by "api", given that it's the first fragment of the route. An easy fix for this is to make sure the matches end with a slash, like this : 

`^\/(?!api\/).*`

Regardless, setting the route parameter to `"{proxy:regex(^\/(?!api\/).*)}"` is still not working out for me.

Also, I'm not quite sure I understand how your regex can end with a simple `/`? Maybe this is just a copy paste issue, since I don't even think this regex is valid.

Finally, where is the documentation for all of this magic regex for route parsing? I can't seem to find anything about regexes in matchCondition.

**Comment by damienwebdev** [comment]
@safihamid as you're assigned to this issue, what's the status on this?

Additionally, I just want to highlight @fperreaultnv 's comment about docs.

> Finally, where is the documentation for all of this magic regex for route parsing? I can't seem to find anything about regexes in matchCondition.

This functionality is documented nowhere, unless I'm mistaken. Does this functionality even exist? Is this supposed to be an end-user facing feature?

**Comment by StephenCleary** [comment]
I've totally forgotten about this issue! I currently use a [much simpler solution](https://github.com/StephenClearyApps/DotNetApis/blob/781a7f5ef65a033c7acab68ec0130765bbc488bd/service/FunctionApp/proxies.json#L15-L36).

The regex route parsing was I believe due to a leaky abstraction exposing an implementation detail. It's been a long time, but I *think* I got the idea from [this SO answer](https://stackoverflow.com/a/45359345/263693), which states that functions uses WebApi 2 routing, which can include [regex as a route constraint](https://docs.microsoft.com/en-us/aspnet/web-api/overview/web-api-routing-and-actions/attribute-routing-in-web-api-2#route-constraints). I'm not sure if route constraints ever worked with proxy routes; that may have just been an assumption of mine.

The core goal was to avoid the proxy completely if hitting the API, so that I could serve a SPA (from any non-API route) as well as an API on the same hostname. In the early proxy previews, an API call would cost double - once to the proxy and once to the function. These days we can [call `localhost` functions directly from the proxy](https://docs.microsoft.com/en-us/azure/azure-functions/functions-proxies#reference-localhost), so this is no longer an issue.

**Comment by Amthieu** [comment]
@StephenCleary your *app* proxy would proxy both `/main.js` and `/specific-page`. Does that work for you? Working with a SPA `/specific-page` should be proxied to your index.html no?

I'm trying to separate those 2 usecase using regex, but it's not working. Any idea?

**Comment by StephenCleary** [comment]
I have a `appResources` proxy, too, which captures all `/static/` paths and allows them through. These are used for JS and images. Paths starting with `/api/` are proxied to the local function. All other requests go through the `app` proxy, which returns the response from `/`.

**Comment by Amthieu** [comment]
@StephenCleary is your SPA hosted in storage?

**Comment by StephenCleary** [comment]
No, [I host it on GH pages](https://github.com/StephenClearyApps/DotNetApis/blob/1ace73be6dc4d386637e0bca0ce1d69e98d8909d/doc/setup.md#deploying-dotnetapis-to-a-new-instance). When it goes live, I'll add a CloudFlare in front of it.
