### ISSUE TITLE
Java Support for Azure Functions

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#224]
Moved from https://github.com/projectkudu/AzureFunctions/issues/314

> Ideally, provide similar functionality as AWS see http://docs.aws.amazon.com/lambda/latest/dg/java-programming-model.html.

**Comment by wyldbill** [comment]
Though I love the idea, Functions is a non-starter for us w/o Java/JVM polyglot support.

**Comment by iwaldman** [comment]
Hi Paul, I see that this enhancement was added to the Next milestone.  I am not sure what this means; can you explain?  Thanks in advance.

**Comment by davidebbo** [comment]
@iwaldman milestone is for some initial classification of issues, but at this point, there is no clear timeframe for this. Next basically means it's something we think is a good idea, but have not done the groundwork to know what it would really take.

**Comment by iwaldman** [comment]
Thank you for the clarification.

**Comment by solvingJ** [comment]
@davidebbo Any updates on the timeframe for Java Support for Functions?  Or, can you at least confirm that it's being worked on?

**Comment by davidebbo** [comment]
@solvingJ it is still on the radar, but at this time we do not have a clear ETA.

**Comment by solvingJ** [comment]
Ok, from my point of view, for a first iteration it doesn't have to be a fully integrated runtime.  Even if a JDK/JRE was available on the filesystem, that would allow us to more easily deploy and run a JAR, and use environment variables to pass the args.

**Comment by davidebbo** [comment]
Note that the JDK is available on the worker, since it's hosted on Azure App Service (which has Java support). You can find it under `D:\Program Files (x86)\Java` (a bunch of versions, latest currently 1.8.0_73). You can use Kudu Console to look through the files.

But my guess is that if it were to launch the Java runtime each time it needs to run a Function, it would be unacceptably slow.

**Comment by davidebbo** [comment]
@solvingJ Ok, so I was curious how far I could get and played around with it. It turns out that it runs pretty well, at least on my super simplistic test.

I documented everything on https://github.com/Azure/azure-webjobs-sdk-script/wiki/Creating-a-Java-Azure-Function, so please give it a try, and let me know if it is along the lines of what you had in mind.

Needless to say that it is very experimental and unsupported. We're just playing around at this point :)

**Comment by solvingJ** [comment]
1. Thank you very much for effort
2. I will experiment tomorrow!
3. Your disclaimer fully acknowledged
4. This willingness to play around with new ideas is what excites me most about new Microsoft!

**Comment by solvingJ** [comment]
‪@davidebbo worked for me by deploying a JAR, hope to post a github example project. I also have a model for full runtime support.  email me if you'd like to discuss.

**Comment by davidebbo** [comment]
Glad to hear, and looking forward to hear more about what you achieve using this technique.

As for discussion, we'd prefer to keep it public in the spirit on Open Source, unless there are some specific things that you prefer not to discuss publicly. Thanks!

**Comment by solvingJ** [comment]
I  wanted to discuss native Java support in a bit more depth offline because I have a previous "on-premise" JVM project which works very similar to azure function. In fact, it's more mature in some ways which might be instructive for the platform.  However, in retrospect it seems likely that the reasons native Java support hasn't been added are not related to a lack of Java developer availability or expertise, but rather other factors which I probably can't help with.

Also, I just looked at how python and php are implemented, and found that they are implemented with the same mechanism as the Java example, so the current Java support now seems average and fair. Previously I assumed they were more runtime-integrated like the C# and NodeJs functionality. 

With that said, I would be happy to provide my time and insight if/when someone begins planning native Java integration.

**Comment by davidebbo** [comment]
Yes, you are correct that Python/PHP (which are only in Preview) currently work the same way. Basically, for each execution, we launch the process and pass it binding data via environment variables.

Right now, we don't have a clear timeframe for when the fuller support will happen. Though I am curious how far you are able to get using the limited approach I described.

**Comment by solvingJ** [comment]
I think your example clearly demonstrates it's capabilities.  It's great considering that just a few days ago using Java wasn't even considered possible.  The most common workflow I would see is to build and deploy FAT JARs with dependencies included, and run them via script.  It's certainly the only workflow I will use for Java.  Currently, the continuous integration benefits do not justify the additional scripting necessary to deal with compilation and manual dependency download. 

However, my primary interest lies in the dream of the combination of the continuous integration (git) workflow PLUS the native runtime support like what .NET enjoys: an always on runtime, automatic compilation, and the receiving POCOs for common triggers rather than strings, etc.  Also, for me a solution must have automatic dependency download included. 

Again, I'm happy to work on this for Java if it becomes a possibility.

**Comment by kpfaulkner** [comment]
I've taken whats been documented at https://github.com/Azure/azure-webjobs-sdk-script/wiki/Creating-a-Java-Azure-Function and am trying to apply that to Go. The input message is fine, but I don't have any environment variable called "outputQueueItem".  

Are there any other setup steps that I might have missed out that will create that?

**Comment by davidebbo** [comment]
@kpfaulkner did you add the Output binding of type Azure Queue Storage? If you keep everything default, the message parameter name is `outputQueueItem`, which then causes the env variable to exist.

**Comment by kpfaulkner** [comment]
Doh, that was it. Thanks :)

**Comment by ranjan545486** [comment]
@davidebbo, how can we get to run the Http GET (CRUD)/POST/PUT/DELETE for Java using the above way? Our requirement is to write Function App (REST) for our COTS layer.

**Comment by davidebbo** [comment]
@ranjan545486 I don't think so. The technique is limited to fairly simple scenario. Once we have fuller Java support later on, those scenarios will open up.

**Comment by abhijeetgps** [comment]
Do we have anytime frame on the same yet? As we are moving an EPG client to Azure Functions completely for all their web jobs to be more cohesively attached to Azure Services? As we have migrated all their C# jobs not only left are the Java blocks. This is a major blocker for us.

Any timeline on the same would help..!!

**Comment by AronT-Emelai** [comment]
As @abhijeetgps notes, not having JVM fully supported is a big barrier for porting over AWS work loads. Considering that Azure tends to match and exceed AWS in so many areas, this is a big shame. BTW, specifically mention JVM, not Java, as we package up scala code in a .jar and it works fine.

**Comment by abhijeetgps** [comment]
Hi @AronT-Emelai thanks for the +1, but I believe I can't deploy it at customer scenario till the time we have full support. Currently performing the same via WebJobs. But we need more Java support on every service and integration with J. Frameworks.

**Comment by AronT-Emelai** [comment]
Just was at a Microsoft Meetup today and apparently this is coming very soon
________________________________

**Comment by abhijeetgps** [comment]
@AronT-Emelai  that's a big relief :) though am interested to know if still I do a dev on functions with .jar and compile with Kudu console, what probably might go wrong? As we have the complete environment at the backend to support?

**Comment by AronT-TLV** [comment]
We will find out when it happens :)

**Comment by kevin-wang-cy** [comment]
Really look forward the full java support in Azure function

**Comment by donamk** [comment]
It would be great if it is possible to use Scala in Azure Function :)

**Comment by solvingj** [comment]
@davidebbo do you have any updated public information on a JVM function runtime you can share?

**Comment by davidebbo** [comment]
@solvingj the v2 Functions runtime is now GA as of last week. The Java support on top of it is still in Preview. We don't have a date yet that we can announce, but it is getting there.

**Comment by pragnagopa** [comment]
Java functions is GA. Closing this issue. 
For issues specific to  java functions please open issue here: https://github.com/Azure/azure-functions-java-worker/issues
