### ISSUE TITLE
Add Function Name to C# compile error logs

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-host#2255]
When we log compile errors (the ones that show up in FunctionLogs in Kusto), we don't include the Function name that failed to compile, which means it doesn't show up when you filter on just Function Name (you have to look at the whole Function app and guess which errors belong to which Functions).

We should correlate the name with the errors in FunctionLogs.

**Comment by davidebbo** [comment]
Seems it's missing from a number of other entries. e.g. the following don't have a FunctionName:

- Executing 'Functions.HttpOrders' (Reason='This function was programmatically called via the host APIs.', Id=47bc2761-3581-4990-8dde-c739149e9d2a)
- Exception while executing function: Functions.HttpOrders
- Executed 'Functions.HttpOrders' (Failed, Id=47bc2761-3581-4990-8dde-c739149e9d2a)

Maybe it's because some are targeting the host log instead of the function log? But then why have nearly identical entries in both? If something is specific to one function, it shouldn't go to the host log at all.

**Comment by pragnagopa** [comment]
This could be same issue as #2199.

**Comment by pragnagopa** [comment]
Fix checked in [V1](ttps://github.com/Azure/azure-functions-host/pull/2467). Tracking issue [here ](https://github.com/Azure/azure-functions-host/issues/2391)for V2
