### ISSUE TITLE
Create repo for proto file and setup CI

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#2296]
<strike>

- Proto file needs to be moved to it's repo
- Setup CI
- Update Javascript and Java worker to pull proto files from the new repo.
</strike>

- [x] Create repo (Done: https://github.com/Azure/azure-functions-language-worker-protobuf)
- [x] PR out for protobuf
- [x] Create release on protobuf repo
- [ ] Move script to download the protobuf release (https://github.com/Azure/azure-functions-host/pull/2696)
- [x] Move Node to download the protobuf release (https://github.com/Azure/azure-functions-nodejs-worker/pull/59)
- [ ] Move Java to download the protobuf release
- [ ] Move Python to download the protobuf release (https://github.com/Azure/azure-functions-python-worker/pull/101)
- [x] Document the process for future language workers

**Comment by christopheranderson** [comment]
- [ ] Create repo (Done: https://github.com/Azure/azure-functions-language-worker-protobuf)
- [ ] PR out for protobuf
- [ ] Create release on protobuf repo
- [ ] Move script to download the protobuf release
- [ ] Move Node to download the protobuf release
- [ ] Move Java to download the protobuf release
- [ ] Document the process for future language workers

**Comment by mhoeger** [comment]
I think we can do this by using **git subtrees** (note: subtrees compared to submodules, because subtrees require extra .git files as administrative overhead and require separate commands for updating... For more reasons why, google "sobmodules" or "submodules hell")

For git subtrees, we can either use the built-in `git subtree` command or manually do this using normal git commands, as detailed in [this article](https://medium.com/@porteneuve/mastering-git-subtrees-943d29a798ec).

Git subtree:
 + Pros:  
   + Lets us checkout specific TAG, not just branch
   + Is easier ? as in just one command.
 + Cons:
   -  **Leaves a messy merge history**

Git manually subtree: 
 + Pros:  
   + More control overall (ex: can have customized commit messages)
 + Cons:
   -  Does by branch, whereas `git subtree` can reference a tag. So I think initially we'll have to have a “v2.x” branch

### Instructions for Manual Git Subtree ###
#### Adding a subtree ####
1.	Define remote so don’t clutter paths
a.	`git remote add <child alias> <url>`
b.	`git fetch <child alias>`
2.	Index contents of remote child branch
a.	`git read-tree  --prefix=<path in parent repo> -u <child alias>/<branch>`
3.	Finalize with commit
a.	`git commit -m “Added subtree in <path in parent repo>”
_Example_
1.	Define remote so don’t clutter paths
a.	` git remote add child https://github.com/mhoeger/git-subtree-child.git`
b.	`git fetch child`
2.	Index contents of remote child branch
a.	` git read-tree --prefix=manualChild -u child/master`
3.	Finalize with commit
a.	`git commit -m “Added subtree in <path in parent repo>”
b.	`git push`

#### Pulling from a subtree ####
a.	`git fetch <child alias>`
b.	`git merge -s subtree –squash <child alias>/<branch>`
a.	If it can’t properly find subtree, reset merge and do this: `git merge -X subtree=<path in parent repo> --squash <child alias>/<branch>`
c.	`git commit -m “Updated the child subtree”`
_Example_
a.	`git fetch child`
b.	`git merge -s subtree –squash child/master`
a.	If it can’t properly find subtree, reset merge and do this: `git merge -X subtree=manualChild --squash child/master`
c.	`git commit -m “Updated the child subtree`
d.	`git push`

**Comment by pragnagopa** [comment]
@mhoeger - thank you for listing out options, pros and cons for each! 

Slight clarification on the runtime: The plan is to move out [Grpc](https://github.com/Azure/azure-functions-host/tree/dev/src/WebJobs.Script.Grpc) project to it's own repo and generate nuget which will be referenced from the runtime.

Another option would be to distribute using package managers for each language using Nuget, maven and npm.

**Comment by paulbatum** [comment]
What are the advantages of this approach vs having the build process download the proto file (at a given commit, or by downloading a given github release and extracting it from the zip)?

**Comment by mhoeger** [comment]
I think the main advantage is that the download step for the .proto template file is language independent. It’s a guaranteed and quick way to get the file in any repo and plug into the existing build pipeline that converts the .proto file into its respective language. The steps involved for setup are running the git commands and running subsequent update commands.

Another difference is that changes to the .proto file can be pushed from a git subtree, although this is probably a consideration against using subtrees.

**Comment by pragnagopa** [comment]
Git subtree does make sense as we have decided not to generate and distribute grpc client code for each platform.

**Comment by paulbatum** [comment]
Will a user be able to pull and build this repo without any additional steps?

**Comment by pragnagopa** [comment]
Yes. [azure-functions-language-worker-protobuf](https://github.com/Azure/azure-functions-language-worker-protobuf) repo would only be used to host the .proto file. This will keep it clean and any language worker will be able to get the proto file and run necessary tools to generate grpc client libraries

**Comment by mhoeger** [comment]
^what Pragna said :) (note: if using git submodules, there would be extra commands). Git subtrees is essentially a way to copy & paste a repo into another repo as a subdirectory and manage its updates using git commands. Pros? easy to setup and update in any repo. One solution for all languages.
Cons? doesn't enforce read-only behavior of copied content. Local modifications within the language worker would need to be enforced with an addition to a .gitignore file (which can be included in the steps, but isn't built-in).

**Comment by pragnagopa** [comment]
This is done. All the language workers now consume protobuf from https://github.com/Azure/azure-functions-language-worker-protobuf
