### ISSUE TITLE
Add support to handle gRpc messages > 4MB

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#2301]
gRpc has a max message size is limit  of 4MB.  We need to add support handle larger messages and in the meantime provide proper error message for messages larger than 4MB

**Comment by kevinhillinger** [comment]
@paulbatum @pragnagopa was there a decision on the size that we want to support? I'm currently running into this issue supporting a scenario with v2 and blob trigger on files greater than 4MB.  

Initial glance, to make the change, it's going to require changing line 20 in `GrpcServer` and incorporating `max_message_length` [ChannelOption](https://grpc.io/grpc/csharp/api/Grpc.Core.ChannelOption.html?q=ChannelOption), which is going to configure the [grpc_channel_args](http://nanxiao.me/en/message-length-setting-in-grpc/)

#### Gist
```csharp
public GrpcServer(FunctionRpc.FunctionRpcBase serviceImpl)
{
    _server = new Server(new[] { new ChannelOption("grpc.max_message_length", int.MaxValue) })
    {
        Services = { FunctionRpc.BindService(serviceImpl) },
        Ports = { new ServerPort("127.0.0.1", ServerPort.PickUnused, ServerCredentials.Insecure) },
    };
}
```

If a max message size has been determined for support, I could work on a PR.

**Comment by paulbatum** [comment]
@pragnagopa I know that the long term solution for this is to have proper stream support but in the meantime I do think we need to consider increasing this as it will be a rather tough breaking change for customers that are upgrading from V1. That said I do want to pick a sane default limit (better users get a clear error early than out of memory exceptions later). 

It occurs to me that the appropriate limit will vary depending on whether the app is in the consumption plan. In that case I want to pick a value that means we would stay WELL under 1.5GB for a function operating at default concurrency (which could be as high as 24). So maybe:

- consumption = 32mb
- otherwise = 128mb

We should consider allowing this setting to be configured by the user when running in a dedicated plan (probably through host.json).

Note that I suggest these defaults based on my understanding of the impact to memory usage - I don't know grpc well enough to be able to comment on whether these are reasonable settings from a grpc perspective.

**Comment by kevinhillinger** [comment]
@paulbatum An important part of this change is updating the documentation to explicitly call out our maximum file size supported. 

Technically right now, the grpc arg is an unsigned 32-bit integer, so the max file size is ~4gb. That size violates the light weight, single function design of Functions, IMO.

**Comment by pragnagopa** [comment]
Given that grpc max size ~4gb,  numbers suggested by @paulbatum sound reasonable. 

Making the setting configurable via host.json needs some investigation as there is no clear documentation on how max message size impacts performance.

**Comment by kevinhillinger** [comment]
While the design is being determined, is there a workaround for blob trigger to only receive metadata without the content of the blob as input, preventing the error?

I am seeing (and supporting 1 active case) situations where consumers of Functions are hitting this error but do not want the contents of the blob, just the blob metadata from the trigger.

**Comment by pragnagopa** [comment]
I have submitted PR to increase max message size on the functions runtime. Once checked in, I will follow up to get this setting honored in each of the language workers.
@kevinhillinger  - Currently we do not have support to just get the metadata. I have opened issue [Azure/azure-webjobs-sdk/issues/1667](https://github.com/Azure/azure-webjobs-sdk/issues/1667) to track this scenario

**Comment by kevinhillinger** [comment]
@pragnagopa thanks for opening up #1667 !
