### ISSUE TITLE
Function App not scaling properly when triggered from ServiceBus

### ISSUE THREAD

**Issue by hentie** [Azure/azure-functions-host#2499]
We have a Azure Function App that gets deployed via VSTS App Service deploy and it only has Azure ServiceBus triggers.  Last year the application was scaling normal, but since January this year we noticed that the app does not scale properly under heavy load.   This was after the app was recreated through an ARM template script and redeployed,

Previously it use to scale up to 50+ instances and now under the same load, it scales up to max four instances.

#### Investigative information

Please provide the following:

- Timestamp: 2018-02-22T16:39:21.528Z
- Function App version (1.0 or 2.0-beta): 1.0
- Invocation ID: 45afd920-8852-4cb3-bcc0-9fe789a21bff
- Region: West Europe

#### Repro steps

I run another app that places a hunderds of messages in the subscription, the function app reacts on while monitoring the Function App in Application Insights. 

#### Expected behavior

The Function App use to scale between 40 and 60 instances under the amount of messages in the servicebus subscription.

#### Actual behavior

The Function App scaled between up to 4 instances under the amount of messages in the servicebus subscription even when there are 1000+ active messages in the servicebus subscription

#### Known workarounds

I call the "Invoke-AzureRmResourceAction syncfunctiontriggers" call via Azure CLI on the Function App after it is deployed.

#### Related information

The host.json is empty and I have no *setting.json file in the app.
All the app settings (including the Servicebus connectionstring) are defined in the App Settings section the Azure Portal.

The app service for the Function App is using a Consumption plan

The function apps use the following packages:
Microsoft.Azure.WebJobs.ServiceBus 2.1.0-beta4
Microsoft.NET.Sdk.Functions 1.0.6

Sample of a function.json in the Function App that does not trigger automatically:
{ "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.0.0", "configurationSource": "attributes", "bindings": [ { "type": "serviceBusTrigger", "topicName": "SessionCompleted", "subscriptionName": "AddMissingItemResults", "accessRights": "manage", "name": "message" } ], "disabled": false, "scriptFile": "...", "entryPoint": "..." }

**Comment by paulbatum** [comment]
@hentie If you can share details as requested in our issue template I can investigate.

**Comment by hentie** [comment]
@paulbatum  I have update some of the details.  If anything more is required to get started, please specify which additional information I need to provide.  Thank you in advance

**Comment by paulbatum** [comment]
I had a look at our logs. Right now I can't see much evidence of under scaling. I pulled our stats for the last 3 days of activity, and it shows that the longest amount of time a message sat on the queue/topic for was just under 2 minutes, and the max number of queued messages we observed at any given time was 750. Also for the case where some messages took 2 minutes to process, it looks like it was due to some sort of slowdown in your application code. In application insights, take a look at invocations around this time:

UTC: 2018-03-15 08:54:37.7681995
InvocationId: 38e3e74d-5f2f-4ed5-a63b-fd85ab46a451

I'm seeing that there were a bunch of invocations that all took one minute, while most of your invocations only take a few seconds.

We have some bugs that cause overscaling (some are fixed now, some still outstanding), and perhaps this is why your app was previously running on so many instances. Your expectations might be skewed as a result.

**Comment by hentie** [comment]
Hi @paulbatum ,

The instance I sent you was in an environment that was already fixed by running the PS script mentioned "Known workarounds" above.  The environment is not very active at the moment.

The crux of the problem is that when I deploy my function app as per normal via VSTS using a stock standard Azure App Service deploy task, the app doesn't scale well until I run the "syncfunctiontriggers" mentioned above.  Worse of all, the app doesn't always respond to servicebus messages until I manually ping it or start monitoring it.   I found the initial workaround solution in this thread: https://github.com/Azure/Azure-Functions/issues/229  , but I cannot find any Microsoft documentation on the "central listener" mentioned and it gives me a bad feeling when I use a solution I cannot find info on.

I can reproduce the initial scenario before the workaround was applied easily.  I think it might be of use to you and your team and especially for me to know why the workaround mentioned actually works

**Comment by paulbatum** [comment]
Hi @hentie, my apologies - I misunderstood  your initial report. I now see that you identified the synctriggers step as a "workaround" and thats what this issue is about.

I think VSTS provides support for multiple deployment protocols, and the default is "zip" which requires the sync triggers action. Webdeploy should not. Can you try the following:

![image](https://user-images.githubusercontent.com/10663/37609187-ab65e9b4-2b59-11e8-850f-74c99a47c951.png)

**Comment by hentie** [comment]
Hi @paulbatum,

I can confirm that by setting the "Publish using Web Deploy" check, does indeed fix the issue I had and I do not need an addtional PS script to sync the Function triggers.  I would however suggest that when you select App type "Function App" in a Deploy Azure App Service step to automatically check this option or possibly check it and disable the option.

**Comment by emreertugrul** [comment]
I seem to be having a problem similar to this. I'm publishing the same function (thats triggered by service bus trigger):
1- Function that uses Consumption Plan does not scale at all, works only on 1 instance, and works inconsistently, would stop getting triggered after some time, or in between,
2- Function that uses App Service Plan works perfectly and the App Service Plan scales (based on CPU for example). 

This is the Consumption Plan live metrics:
![image](https://user-images.githubusercontent.com/12210206/42931972-bbc2055e-8b49-11e8-9fad-bf59cb42be7d.png)

And the same function, same config running consistently on App Service Plan:
![image](https://user-images.githubusercontent.com/12210206/42931994-d122a160-8b49-11e8-9a2e-abfcc8a6eb99.png)

Ofcourse, since the App Service Plan has instance limit of 10, its not ideal for my situation and the messages in the Topic increase, while if the Consumption Plan should scale to accommodate the load.. I'm not sure if this is the same issue, seemed the most relevant topic to post this..

Btw here's what I'm using:
NETStandard.Library  2.0.3
Microsoft.Azure.WebJobs.ServiceBus 3.0.0-beta5
Microsoft.NET.Sdk.Functions  1.0.14

**Comment by paulbatum** [comment]
This issue is closed because it related to problems that occur when using certain deployment methods. Since you're deploying with VS 2017 publish gesture, those issues should not apply to you so I suggest you file a new issue (I'd also encourage you to try stackoverflow first as there is more community particiption there and its not clear yet whether you are running into a bug or a configuration issue).
