### ISSUE TITLE
OutOfMemoryException 

### ISSUE THREAD

**Issue by MayankSri** [Azure/azure-functions-host#2501]
Hi, 
I have an http trigger Azure function which reads text in blobs and returning as a string in a JSON payload.
I am using the consumption plan.

I am trying to read ~400 Mb blob file and getting 500 response with the following response in postman:
`{`
`    "id": "3d66f897-8096-47f4-a4a7-73ee1fee889f",`
`    "requestId": "974892d7-2b28-49ae-860e-f2f78a3ee5c7",`
`    "statusCode": 500,`
`    "errorCode": 0,`
`    "message": "An error has occurred. For more information, please check the logs for error ID 3d66f897-8096-47f4-a4a7-73ee1fee889f"`
`}`

The questions I have are:

- What kind of memory limitation does the consumption plan have?
- Where can I go to see the error with error ID 3d66f897-8096-47f4-a4a7-73ee1fee889f"? I tried looking in the Application Insights, do not see anything in the Exception or Requests.

**Comment by paulbatum** [comment]
@MayankSri The consumption plan has a limit of 1.5GB per instance (see [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#how-the-consumption-plan-works) for info). A function that reads a 400mb file might push you over the limit, it depends on a few things:
- if you're reading the entire file into memory or if you process it as a stream
- how many other functions are defined and running within the function app
- how much overall concurrency is occurring per instance

Since you have App Insights hooked up, you should be able to see the details of your error in the `exceptions` table. You said you can't see anything which seems unusual, maybe check that you have your date range filter correct (I think it filters to last 24 hours by default). You can view memory consumption by looking at entries in the `performanceCounters` table with name `Private Bytes`.

**Comment by paulbatum** [comment]
Closing this as answered

**Comment by Tarmil** [comment]
I'm a bit confused at the exact meaning of the word "per instance" here. Can OOM happen due to separate function apps running concurrently on the same consumption plan? Or only functions in the same function app?

**Comment by paulbatum** [comment]
The latter. All billing/metering for consumption apps happens at the app level. There is no actual difference between having two function apps on the same consumption plan vs having them on separate consumption plans. The consumption plan mostly exists to disambiguate from the other ways of running functions (on a dedicated app service plan, in premium, etc).
