### ISSUE TITLE
Do you plan to support timezone in host.json?

### ISSUE THREAD

**Issue by wminos** [Azure/azure-functions-host#2506]
I will close this issue if I misunderstood.
If you have any other good ideas, please let me know.

Currently I know that I need to define a timezone in the WEBSITE_TIME_ZONE environment variable in my application settings.
But in azure world, some want to UTC and some want to EST (EST for dev funcs, UTC for product).
Of course it is still possible.
I need to set a different WEBSITE_TIME_ZONE environment variable for each Azure Function App Website.
However, if I can define it in host.json(or even for each function!), I think it will have the following advantages.

I can see this together with the code in the Visual Studio Azure Functions Project.
It is possible to test with the correct timezone even if F5 is executed without changing environmental variable in each development project.

**Comment by Clockwork-Muse** [comment]
....what problem are you trying to solve here?  Not, "I'm trying to set the environment timezone", _why_ are you trying to set the timezone.

Note that, generally speaking, an application should work regardless of the environment timezone.  In a server environment, the timezone of the server is rarely (if ever) relevant, because you're going to be far more interested in the timezone of your business unit (if then), which should be picked up based on the input to the function (either as part of the payload, or stored in a repository); it's extremely unlikely that you'd load-balance based on timezone.

**Comment by wminos** [comment]
@Clockwork-Muse 
I agree with your opinion that programs and systems (including time zones) should be independent.

The azure functions are all that used to be a secondary tool for development that day, 
and I have somewhat misunderstood the role of host.json.

I was thinking of host.json as a layer like publish profiles (pubxml), 
so I do not think that my code should include a timezone.

However, I would like to be able to see the two on the same screen in visual studio ide.

Now that I know I can check the time zone through the "Function App Settings" in the Publish menu, I no longer have to fix this issue.
