### ISSUE TITLE
[Question] Microsoft.NET.Sdk.Functions NuGet package references

### ISSUE THREAD

**Issue by felpel** [Azure/azure-functions-host#2529]
Is there a particular reason why the versions of many dependencies are set to a **specific version**, a.k.a. it doesn't allowed **a greater or equal version** when it comes to the `Microsoft.NET.Sdk.Functions` NuGet packages?

As for example, with the current latest version ([1.0.9](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/1.0.9)), we're _stucked_ with many fixed references. As an example, `Newtonsoft.Json` is locked to `9.0.1` and many other packages might have a more recent version of the package ([11.0.1](https://www.nuget.org/packages/Newtonsoft.Json/11.0.1)). As for the other `Microsoft.Azure.WebJobs.*`, it might be fair enough to say that it shouldn't be a problem if they're fixed.

In our current context, we can't update another NuGet package to the latest version because of that limitation. Is there a known workaround to deal with that that we might not be aware of? 

Thanks in advance! 👍

**Comment by fabiocav** [comment]
The reason why those are locked to specific versions is because in Azure Functions, you're running on a host that uses them, and many scenarios would be impacted (primarily binding ones) by mismatched dependencies, so to prevent an issue that would only be found at runtime, the SDK makes that happen at build/package installation time.

If you happen to be trying to leverage a scenario that doesn't rely on type exchanges with the runtime (e.g. binding to a type from your referenced package), then you do you have the ability to add an explicit reference to the version you want to use, which will override the version specified by the SDK.
