### ISSUE TITLE
Exception binding parameter 'input' on Cosmos trigger

### ISSUE THREAD

**Issue by btedev** [Azure/azure-functions-host#2570]
#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0-beta): 1.0
- Invocation ID: 2018-03-21T15:38:23.533, ef4ae65c-7a0d-487a-bd31-d976816d5997
- Region: East US 2

#### Repro steps

Provide the steps required to reproduce the problem:

1) Create a Cosmos DB trigger function app in Visual Studio.

2) Code is below:

```csharp
 public static class CosmosWatchFunction
    {
        [FunctionName("CosmosWatchFunction")]
        public static void Run([CosmosDBTrigger(
            databaseName: "PrimaryTest",
            collectionName: "AaronTest",
            ConnectionStringSetting = "pdocdbtest_DOCUMENTDB",
            LeaseCollectionName = "AaronTestLeases2",
            CreateLeaseCollectionIfNotExists = true)]IReadOnlyList<Document> input, TraceWriter log)
        {
            if (input != null && input.Count > 0)
            {
                log.Info("Documents modified " + input.Count);
                log.Info("First document Id " + input[0].Id);
            }
        }
    }
```

3. Change a document in the collection being monitored.

#### Expected behavior

Expect log should show "Documents modified", etc.

#### Actual behavior

Get exception:

Exception while executing function: CosmosWatchFunction
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: CosmosWatchFunction ---> System.InvalidOperationException : Exception binding parameter 'input' ---> System.ArgumentException : Binding can only be done with IReadOnlyList<Document> or JArray
Parameter name: type
   at Microsoft.Azure.WebJobs.Extensions.DocumentDB.CosmosDBTriggerValueBinder..ctor(Type type,IReadOnlyList`1 value)
   at Microsoft.Azure.WebJobs.Extensions.DocumentDB.CosmosDBTriggerBinding.BindAsync(Object value,ValueBindingContext context)
   at async Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindCoreAsync[TTriggerValue](ValueBindingContext context,Object value,IDictionary`2 parameters) 
   End of inner exception
   at Microsoft.Azure.WebJobs.Host.Executors.DelayedException.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) 
   End of inner exception

#### Related information  

I had no problem creating a Cosmos DB trigger function from the Azure portal that works well. I'm trying to create a version of it in VS to better integrate with other functions we're running. Note that the lease name is different from the .csx function so there's no conflict there.

**Comment by paulbatum** [comment]
@brettsam @ealsur any ideas on this one?

**Comment by ealsur** [comment]
This is a pre-compiled Function that has the DocumentDB package dependency changed to another version different than 1.13.2.

Since Runtime does not support binding redirects, this is the scenario we have seen in the past with @brettsam 

It is solved by removing the DocumentDB nuget package and letting the compatible version being pulled from the Webjobs.Extension.DocumentDB package.

**Comment by brettsam** [comment]
What version of the DocumentDB package are you referencing? This looks similar to https://github.com/Azure/Azure-Functions/issues/700. We likely can't match the `Document` type since the versions don't match.

Recommendation would be to either:
- downgrade any DocumentDB nuget to 1.13.2.
- Remove the DocumentDB reference completely and instead directly reference Microsoft.Azure.WebJobs.Extensions.DocumentDB, which will reference the correct version for you.

**Comment by btedev** [comment]
Downgrading DocumentDB to 1.13.2. fixed the issue. Thanks so much for your help.
