### ISSUE TITLE
Node serializer settings differ between v1 and v2

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#2571]
We used to make sure that binding property names were camelCased when sending the objects to node functions; that's no longer the case. I saw it when porting this test: https://github.com/Azure/azure-functions-host/blob/dev/test/WebJobs.Script.Tests.Integration/EventHubs/EventHubsEndToEndTestsBase.cs#L44. In v1, "SequenceNumber" came back as "sequenceNumber".

Here's where we took care of that in v1:
https://github.com/Azure/azure-functions-host/blob/v1.x/src/WebJobs.Script/Description/Node/NodeFunctionInvoker.cs#L523

**Comment by paulbatum** [comment]
This is an accidental break that has to be fixed.

**Comment by mhoeger** [comment]
It looks like doing the lowerCamelCase conversion was switched over to be [handled by the language worker](https://github.com/Azure/azure-functions-nodejs-worker/blob/bf84af77038476c76f769b6dcd863a6f1de026b8/src/Context.ts#L109-L123).

There is a bug where we aren't doing the formatting recursively (https://github.com/Azure/azure-functions-nodejs-worker/issues/39), which is why "systemProperties" is cased correctly and "SequenceNumber" isn't. 

Updating title and label.
