### ISSUE TITLE
Time triggered Azure function not scaling up with the increase in the instances of the App service plan

### ISSUE THREAD

**Issue by MayankSri** [Azure/azure-functions-host#2591]
I have an Azure function that is triggered every 1 second. Every time it is triggered, it reads a batch of messages from a Service Bus queue and processes them. It runs on App service plan which scales on the active messages in the queue. However as the service plan scales out I do not see any increase in the throughput of the function.

Does the Time triggered Azure function scale as the increase in the instances of the App service plan?

**Comment by paulbatum** [comment]
From the [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer#scale-out):

> If a function app scales out to multiple instances, only a single instance of a timer-triggered function is run across all instances.

For timer based workloads, the recommended approach is to make your timer write to a queue, and to have a queue triggered function do the actual work. This will allow concurrent executions to occur (if processing takes longer than the timer interval), potentially across multiple instances. 

For maximum throughput, you should consider converting to a service bus triggered function rather than a timer.

Closing this as answered.
