### ISSUE TITLE
Function invocation fails with HTTP 500 and no log.

### ISSUE THREAD

**Issue by mayerc-MSFT** [Azure/azure-functions-host#2612]
Function invocation fails with HTTP 500 and no log.

#### Investigative information

Please provide the following:

2018-03-30T17:03:48.417 [Information] Host Status: {
  "state": "Running",
  "version": "2.0.11651.0",
  "versionDetails": "2.0.11651.0-beta1 Commit hash: 626c20039fb17e1d5c79145d7b7c3579cf62a92a"
}
2018-03-30T17:03:50.196 [Information] Executing 'GetGraphVersion' (Reason='This function was programmatically called via the host APIs.', Id=1de72eb2-699f-457c-a219-cfd2f0a7d0d3)
2018-03-30T17:03:52.752 [Error] Executed 'GetGraphVersion' (Failed, Id=1de72eb2-699f-457c-a219-cfd2f0a7d0d3)

Region: South Central US

#### Repro steps

Provide the steps required to reproduce the problem:

1. Deploy function
2. Invoke

#### Expected
Logs to show up so I can troubleshoot.

#### Actual behavior
Nothing gets logged, not even the first `logger.Info` (see below) statement at the very top of the function, which makes me think invocation is failing before function code is actually executed.

#### Known workarounds

None.

#### Related information 

Provide any related information 

<details>
<summary>Source</summary>

```csharp
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = Route)]HttpRequest req,
            string requestId,
            TraceWriter logger)
        {
            logger.Info($"{nameof(GetGraphVersion)} called.");
            try
            {
                using (var scope = InjectConfiguration.ContainerInstance.BeginLifetimeScope())
                {
                    var graphEngine = scope.Resolve<IGraphEngine>();

                    if (req == null)
                    {
                        throw new ArgumentNullException(nameof(req));
                    }

                    if (string.IsNullOrWhiteSpace(requestId))
                    {
                        throw new ArgumentNullException(nameof(requestId));
                    }

                    var version = await graphEngine.GetGraphVersion(requestId);

                    // Fetching the name from the path parameter in the request URL
                    return (IActionResult)new JsonResult($"{version}");
                }
            }
            catch (Exception e)
            {
                logger.Error($"FAILED. {e.Message}", e);

                throw;
            }
        }
```
</details>

**Comment by ossentoo** [comment]
hi,

I'm having a very similar problem.  I am using Azure Functions 2.0 core runtime.  I get a 500 error when I invoke the function using Postman.

I've checked on kudu in the logs directory for the function, but can't see any meaningful error.

The weird thing is that I can run the function locally without any problem

I did have some problems locally after I mistakenly of upgraded nuget packages to latest version rather than those that are in my C:\Users\user\AppData\Local\Azure.Functions.V2.Cli\2.0.1-beta.22 folder.  For example, when upgrading Microsoft.AspNetCore* or Microsoft.Extensions* packages to 2.0.2 or greater, some of which are now available on nuget. I have now ensured that as far as I can see, all dependencies in my bin directory are the same as those in the Azure.Functions.V2.Cli\2.0.1-beta.22 folder (most of which are v2.0.1).

Please contact me if you'd like a copy of the source-code that produced this error in the Azure function, to get a link to the function.

**Comment by pragnagopa** [comment]
We recently fixed a logging issue. Related issue #[2244](https://github.com/Azure/azure-functions-host/issues/2244). Closing this for now.  We will be rolling out an update soon. Please reactivate if you still see no error details on function invocation.
