### ISSUE TITLE
Creating a Function App on Linux, using the Portal, Results in a non-functional App Service

### ISSUE THREAD

**Issue by martinpeck** [Azure/azure-functions-host#2631]
# Creating a Function App on Linux, using the Portal, Results in a non-functional App Service

It is possible to create a Function App on Linux via the Azure CLI and by using the Portal. 

However...

1.	If I create a Function App on Linux via the CLI I end up with a working app
2.	If I create a Function App on Linux via the Portal I end up with a non-functional app

Either there are some steps that need better documenting, or the Azure Portal needs to do a better job of setting these Function apps up.

## Repro Steps

The following describes the steps followed to create a Function App on Linux using the CLI and using the Portal. Prior to performing these steps there are some common steps that need to be followed.

### Common Steps
 
- Using the functions CLI, create a new docker based function app (func init –docker)
- Using the functions CLI, add a single JavaScript HTTP trigger endpoint, leaving the default “hello” code in place (func function new)
- Tag and push the docker image to Docker Hub (the same issue is present if you use Azure Container Registry)
- Create a resource group (mine is called xyzazfuncdocker)
- Create a storage account within the resource group (mine is called xyzazfuncdocker)

My docker image can be found here: https://hub.docker.com/r/martinpeck/azfuncdocker/

### Steps to Create a Function App for Linux using CLI

1.	Create an App Service Plan

`az appservice plan create --name xyzazfuncdocker8 --resource-group xyzazfuncdocker --sku S1 --is-linux`

2.	Create a Function App, using the App Service Plan

`az functionapp create --name xyzazfuncdocker8 --storage-account xyzazfuncdocker --resource-group xyzazfuncdocker --plan xyzazfuncdocker8 --deployment-container-image-name martinpeck/azfuncdocker:v1.0.0`

3.	Test the API using curl

`curl -i https://xyzazfuncdocker8.azurewebsites.net/api/http-trigger\?name\=Martin`

4.	Observe that the function app responds with an HTTP 200 and the test “Hello Martin”

### Steps to Create a Function App for Linux using Portal

1.	Create new Function App using the Portal

 
![image](https://user-images.githubusercontent.com/1524451/38368356-ff9c951a-38dc-11e8-8833-cdf8f965c5cc.png)

2.	Provide all of the information required to create the Function App, illustrated here with instructions

1.	Give it a name
2.	Use the resource group we’ve previously created
3.	Switch to Linux (Preview)
4.	Click on Service Plan
5.	Create a new Service Plan
6.	Name the Service Plan, set the location, then click OK
7.	Select the storage account we’ve previously created, and click “Create”

![image](https://user-images.githubusercontent.com/1524451/38368370-094f73ac-38dd-11e8-9061-25c2d8c4643e.png)

3.	Once deployed, observe that the Portal shows the two Function Apps using different icons. The one created using the CLI has the Functions logo, while the portal one has a generic logo.

![image](https://user-images.githubusercontent.com/1524451/38368414-24d09188-38dd-11e8-9d9e-c9c1d0eac436.png)

4.	Open the App Service Plan and configure it to use your container, making sure you select Docker Hub and provide the tag for your container. Additionally, turn on CD

![image](https://user-images.githubusercontent.com/1524451/38368458-43960aee-38dd-11e8-9740-bb123f329f6c.png)

5.	Test the API using curl and observe that an HTTP 404 is returned.

```
curl -i https://xyzazfuncdocker10.azurewebsites.net/api/http-trigger\?name\=Martin
HTTP/1.1 404 Not Found
Server: Kestrel
Date: Wed, 04 Apr 2018 15:40:49 GMT
Content-Length: 0
```

**Comment by paulbatum** [comment]
@ahmelsayed any ideas on this? I'm guessing this issue needs to be moved to a different repo.

**Comment by ahmelsayed** [comment]
Yeah, it probably doesn't belong here, but I'm not sure where it belongs. 
There should be another create flow in the UI for creating "Function App for Container" or whatever the marketing name for that is. 

The difference between the portal and the cli is that when using a custom image, the cli automatically sets `WEBSITES_ENABLE_APP_SERVICE_STORAGE = false` while when you create from portal, that setting isn't set, which defaults to true.

that setting tells the docker host to mount a persistent volume for your functions files. The reason is that if you create the app from portal, you want to be able to create functions from the UI, and you want these functions to persist container restarts.

When publishing a custom container with functions in it however, mounting that volume will mask any functions you might have in your container. 

Set that app setting to false on your app that you created from portal, and reload the app. It should work.

**Comment by martinpeck** [comment]
> Set that app setting to false on your app that you created from portal, and reload the app. It should work.

I'll give this a go and confirm whether it works after this change.

I wasn't sure is this was purely a Functions portal issue, or something else, hence I ended up logging it here.

**Comment by martinpeck** [comment]
Confirmed. I followed my repo steps, but then:

1. Created App Setting `WEBSITES_ENABLE_APP_SERVICE_STORAGE` and set it to `false`
2. Restart the App Service

This results in the function app that works. 

The App Service still shows up as a regular app service, and not a Function App. Clicking on the App Service from the list of resources in the resource group does *not* take me to the Functions UI but takes me to the regular app service UI. 

I can get to the Functions UI by clicking on the Function Apps menu (at the top level of the portal). 

i.e. it still feels like this App Service is being treated differently in the portal.

**Comment by paulbatum** [comment]
@ahmelsayed I still need to find the right home for this issue. Is it a portal bug?

**Comment by ahmelsayed** [comment]
There are 3 issues here:

1) Function App showing as a web app in the browse blade in ibiza. This is a UX bug (more of an ibiza bug than an azure-functions-ux bug, but open it on the ux repo anyway. The issue here is adding a new kind `functionapp,linux,container` instead of the old kind of `functionapp,linux`. 

2) No equivalent to `--deployment-container-image-name` in the UI. So this is another UX bug to add that new functionality. I believe @hartra344 has this already done `FunctionApp for Containers` I believe is the name.

3) Changing an app's `linuxFxVersion` for a function app that wasn't created with `--deployment-container-image-name` should not be a valid configuration. Or add `WEBSITES_ENABLE_APP_SERVICE_STORAGE` yourself. I think this is a documentation bug to explain the difference.

**Comment by fabiocav** [comment]
@ahmelsayed This is still generating support issues. Is the issue still an issue?

**Comment by ahmelsayed** [comment]
I believe all the issues I mentioned above should be already fixed. If there is a recent issue, can you point me to it?

**Comment by fabiocav** [comment]
It's an internal support case. Will forward you a link.

**Comment by ahmelsayed** [comment]
I think that was unrelated to this issue. The original issue reported here has been fixed for a while in the UX now. I'll close this one.
