### ISSUE TITLE
How do we correctly set IP Restrictions?

### ISSUE THREAD

**Issue by giemch** [Azure/azure-functions-host#2643]
I set an IP restriction on my Function App to limit access to our APIM instance. Once that was added I got the "runtime could not be started" error in the portal. I also saw 403 errors in my browser network traffic. Once I removed the IP restriction the error went away. Are there some additional Azure IP(s) that need to be included in the whitelist? To clarify, these are the Networking > IP Restriction settings in the Function App.

**Comment by paulbatum** [comment]
Ahh I get it, this isn't even a runtime bug, its a portal bug. The portal gave you the impression that your function app wasn't starting, but actually it was just failing to communicate (due to the IP restriction). That explains why there weren't any meaningful errors in your app insights instance.

That issue is already tracked here:
https://github.com/Azure/azure-functions-ux/issues/2471

So closing this one as a dupe.
