### ISSUE TITLE
Linux: vfs links have incorrect hostname

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-functions-host#2713]
e.g. instead of the FQ host name, it has http://david2/admin/vfs/root/

**Comment by ahmelsayed** [comment]
yep, I'm aware of that. It's happening because the frontEnd changes the HOST header from `app.azurewebsites.net` to `app`, and `https` to `http`. In Antares `dwasmod` (a native IIS module) takes care of flipping them. We will have to do something similar. In the mean time, the portal handles it correctly, but will need to fix it eventually

**Comment by ahmelsayed** [comment]
Actually now that i think about it, i think itll also impact any http function in which the iser tries to access the host header of the request. The fix is simple though, ill try to get it in

**Comment by davidebbo** [comment]
Would be a bigger deal for HTML sites that need to show links. Still, would be good to fix.
