### ISSUE TITLE
CosmosDB binding silently fails while connecting to CosmosDB Emulator

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#2766]
_From @jacktho on April 30, 2018 17:59_

CosmosDB extension: 3.0.0-beta7.
Node: 8.11.1
azure-functions-core-tools: 2.0.1-beta.25

- 'func host start' shows the extension successfully loads.
- No errors or warnings are seen in the console or log files.
- It does not matter if the connection string is correct or not.
- Removing the connection string altogether does produce a warning.
- The same local.settings.json and function files are able to connect to the emulator when using core tools v1.

I'm not sure what else to provide as I'm in the dark as to what the problem is.

Thanks.

_Copied from original issue: Azure/azure-functions-core-tools#450_

**Comment by brettsam** [comment]
@jacktho -- it looks like you need to manually create the `leases` collection in your emulator. I even tried setting `"createLeaseCollectionIfNotExists": true` in my functions.json, but the collection was not created.

@ealsur -- any idea why the emulator wouldn't work properly in this scenario? Since the lease collection didn't exist, I would have expected an error upon startup. But the auto-create flag didn't seem to work either.

**Comment by ealsur** [comment]
@brettsam Is this V2 or V1?

I'm trying to see if this is an issue between V2 (which uses the SDK Core package) and V1 (which uses the  normal SDK) and the Emulator.

**Comment by brettsam** [comment]
This is v2. I tried it from the full end-to-end, but you may be able to repro it directly in the sample in Extensions (or even outside of Functions entirely?)

**Comment by ealsur** [comment]
@jacktho Are you using the latest Emulator? Just to create a complete scenario in case this needs to be reported to the Emulator team.

**Comment by brettsam** [comment]
For v2 we can move CFP forward. Was there an error being thrown that we didn't log, or does it just silently fail?

**Comment by ealsur** [comment]
I'll address the version bump in a separate PR then 😄 
I did see the error throw, but it took some time, since the SDK seems to retry multiple times to run the operation and retries on each failure. Basically the SDK call to read a Database fails, but keeps retrying for a while and eventually throws.
