### ISSUE TITLE
Satellite/Referenced Assembly Functions - Generating 0 job functions

### ISSUE THREAD

**Issue by grahamehorner** [Azure/azure-functions-host#2836]
We have a project that has a number of AzureFunctions that are located in satellite assemblies, the WebJob.Host is not resolving/generating the job functions for that and preventing the execution of the functions which have [Function("")] with in the same namespace of the main AzureFunction project ?

Please allow resolution of Functions in satellite assemblies.

**Comment by paulbatum** [comment]
@grahamehorner Correct me if I'm wrong, but satellite assemblies are for managing resources/localization (based on what I'm reading [here](https://stackoverflow.com/questions/365569/what-is-a-satellite-assembly)). Can you help me to understand what the scenarios are for putting function definitions into satellite assemblies?

**Comment by grahamehorner** [comment]
@paulbatum we have a number of solutions/projects/customer(s) where we have to deploy azure functions as a unit, adding some additional functions (shared libraries in other projects) to be added as/when needed for a tailored customer deployment.  

While we could deploy all functions (entry point/triggers) as in assembly and configure them as enabled/disabled it seems counter productive and prone to error in configuration.

We would like the ability to have functions in a number of assembly and from references/satellite assemblies in that when included in the project the build tools would create the required functions.json by scanning the bin for assemblies marked with the [FunctionName("")] attribute.

NOTE: functions may/may not deployed per customer and/or be a multi-tenant or common shared deployment and may have a number function with culture differences/implementations

hope that answers your question with regards our aim;

**Comment by paulbatum** [comment]
@grahamehorner It sounds like the confusion here is around terminology. What you're describing is not satellite assemblies, which are for resources as discussed above. What you are describing is the ability to compose several class libraries that contain function definitions together into one function app.

This is technically possible today but the current VS tooling does not make it easy. Below is an example showing how its possible. Some more effort would need to be put into designing/defining the VS experience to make this work.

1. Create a new VS solution with two Function App projects. Choose for one to be the parent and one to be the child. Have the parent add a project reference to the child. Modify the function definition in the child to be "Function2" so that they don't clash.

In this screenshot, `MultipleFunctionAssemblies` is the parent:

![image](https://user-images.githubusercontent.com/10663/40323542-85ed467e-5cea-11e8-92e5-1b060985a533.png)

2. Build the solution. You should see that build output is generated for both projects. There are some important details to note here:
  - the directory for "Function2" **was not** copied into the build output for the parent
  - the dll for the child **was** copied into the bin folder of the parent

![image](https://user-images.githubusercontent.com/10663/40323663-f4498f4c-5cea-11e8-9071-f1eddaa83caf.png)

![image](https://user-images.githubusercontent.com/10663/40323692-0f686078-5ceb-11e8-96f3-2cf21123efad.png)

3. Make a new directory somewhere else on your computer, and copy the build output from the parent there and then also copy in the function definition folders from the child. It should look something like this:

![image](https://user-images.githubusercontent.com/10663/40323827-84c067c6-5ceb-11e8-8355-6e9e148202d5.png)

4. Run the azure functions core tools against this directory. You will see that both functions are loaded:

```
> cd D:\temp\function-composition
> C:\Users\pbatum\AppData\Local\AzureFunctionsTools\Releases\1.0.11\cli\func.exe host start
<SNIP>
[5/21/2018 6:25:28 PM] Generating 2 job function(s)
[5/21/2018 6:25:28 PM] Found the following functions:
[5/21/2018 6:25:28 PM] MultipleFunctionAssemblies.Function1.Run
[5/21/2018 6:25:28 PM] SharedFunctions1.Function2.Run
```

5. Zip up the contents to prepare for azure deployment:

![image](https://user-images.githubusercontent.com/10663/40324371-2fbb7214-5ced-11e8-83ab-7719e64d5300.png)

6. Deploy the zip to your function app. There are several ways to do this. For all the details see [here](https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push). I'm going to use the cloud shell.

7. I open the portal, open the cloud shell, and upload my zip:

![image](https://user-images.githubusercontent.com/10663/40324472-70b9f772-5ced-11e8-88e0-96ab9149cafb.png)

8. Then I run the deployment command:
`paul@Azure:~$ az functionapp deployment source config-zip -g pbfunctioncomposition -n pbfunctioncomposition --src /home/paul/function-composition.zip`

9. Finally I open the function app in the portal and confirm both functions are present and working:

![image](https://user-images.githubusercontent.com/10663/40324624-edab59ce-5ced-11e8-853b-8b719d628100.png)

Hope this helps. You should be able to run through these steps and prove that the approach can work and then turn it into an automated process.

**Comment by grahamehorner** [comment]
@paulbatum thanks for the above info, seem like the manual work around above maybe the only option, unless we can generate folders and functions.json at runtime after deployment for give.assembly files? would the azure functions host detected newly created folders/functions.jsons files dynamically?

**Comment by paulbatum** [comment]
The host doesn't have any built in capability to generate those function.json files. Its a build time step. So I would copy those files as part of your build script.

**Comment by fabiocav** [comment]
Yes, the host would pick up those changes at runtime.

I'm linking to the other issue you've opened against the VS tools here https://github.com/Azure/azure-functions-vs-build-sdk/issues/202 for tracking, as the work to support this should happen there.
