### ISSUE TITLE
Function should fail indexing if using a non-existent binding

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#2895]
I created a JavaScript function that was using a binding that I didn't have. I was expecting it to fail during indexing and be disabled, but the trigger continued to fire and, since I was attempting to access the binding value, the invocation failed.

I wasn't expecting it to behave this way, so wanted to call it out and see if it was by-design. It seemed like we would give a clear exception during indexing to explain that we couldn't find the extension.

To prove it -- add a binding like this and invoke it. If you don't try to access `busted` it will work.
   
    {
      "name": "busted",
      "type": "somethingThatDoesntExist",
      "direction": "out"
    }

**Comment by paulbatum** [comment]
Please do first pass investigation and make a recommendation about timing (is there an issue to fix here prior to V2 GA or can it be done after?)

**Comment by paulbatum** [comment]
potentially breaking depending on exact implementation

**Comment by jeffhollan** [comment]
When I think about experience I like the current C# assembly experience - in that if I don't have the right extension I can't even build.  Obviously with things like JavaScript there isn't a build step, but would prefer for things to fail outright than appear to work or give a yellow-text warning.

My preference is during host startup it evaluates the types in function.json and compares against types of included bindings.  If a type that doesn't map to anything exists, it throws a red-text error like "function.json specifies a binding of type {0} but no binding of that type is installed. You may need to run `func extensions install` to include extensions http://aka.ms/func-extensions" (which would link to our page on bindings like [this one](https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#local-development-azure-functions-core-tools)

There is still the possibility that the **type** may be accurate, but a **property** is invalid (e.g. `connection` instead of `connectionStringSetting`.  I'd prefer the same behavior but not sure if a separate item or possible with how bindings and extensions work.
