### ISSUE TITLE
Are ScaleManager/IScaleHandler going to land with 2.0 RTM?

### ISSUE THREAD

**Issue by drub0y** [Azure/azure-functions-host#2978]
I was looking into how to do auto-scaling for self-hosting functions beyond just watching system resources (e.g. memory/cpu) so that we can scale more intelligently based on actual workload (e.g. my queue is suddenly 10k msgs deep, I need to scale to 10 instances immediately).

I see that `ScaleManager` has been introduced along with an abstraction `IScaleHandler` (#1549) that looks like it aims to solve this in a nice way. Unfortunately I don't actually see it being used beyond the test suite right now. So I guess the initial question I have is: is this mechanism expected to land in time for 2.0?

**Comment by paulbatum** [comment]
Not by 2.0 RTM. Because the application developer is abstracted from the details of how scale is handled, we feel like we can continue pushing on this area beyond the RTM timeframe and in the meantime we need to focus on breaking changes, experience issues etc that would be much more impactful to users if not addressed by RTM.

Closing this as answered.
