### ISSUE TITLE
Bug Found - 500 Internal Server Error when Changing Azure Function Runtime from VS Code

### ISSUE THREAD

**Issue by wely** [Azure/azure-functions-host#3038]
Symptom:

Got the 500 Internal Server Error when publish a simple (even an hello world) function to Azure Function (with 2.0 beta runtime).

After investigation, looks like this is the culprit:
- If you deploy your function (with Runtime 2) from VS Code while the newly created Function is Runtime 1, it will prompt you this:
![image](https://user-images.githubusercontent.com/1658657/41714601-6ef5f216-7583-11e8-949b-415e0e8ee59f.png)

- Clicking "Update remote runtime" cause the issue.

- I've tried to change the Runtime (from 1 to 2 beta) from the Azure portal. Everything works well.

Hope this repro helps.

**Comment by kennetham** [comment]
Hi @wely , this has to do with the order of creating Azure Functions. If you are creating Azure Functions via Azure Portal, the general guidance is that you need to have it set to "beta". Otherwise, you'll get that error.
Two, you could alternative create from VSCode, that should not cause an issue.

My recommendation is to just run `npm install -g azure-functions-core-tools@core`. And you should also be able to run your functions locally (Azure Functions)[https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local].

**Comment by wely** [comment]
@kennetham  i did use the npm for running Function Runtime 2 locally, things worked well.
Only when i tried to deploy to Azure Function, the error happens.

Regarding:

> Hi @wely , this has to do with the order of creating Azure Functions. If you are creating Azure Functions via Azure Portal, the general guidance is that you need to have it set to "beta". Otherwise, you'll get that error.
> Two, you could alternative create from VSCode, that should not cause an issue.

Thx for the general guidance which sounds more like a workaround to avoid the bug. That said, i still think this is a bug which needs to be resolved :)

**Comment by zanechua** [comment]
@jeffhollan mentioned this to me previously when I deployed it via VSCode.

It's pending a fix if I am not mistaken.

**Comment by jeffhollan** [comment]
Correct - known issue and being tracked.  For now follow mitigation from @kennetham above and manually upgrade the node version in the Application Settings of the published app (can even do this from Azure Functions extension)

https://github.com/Microsoft/vscode-azurefunctions/issues/419

**Comment by pragnagopa** [comment]
Closing this as issue is tracked here https://github.com/Microsoft/vscode-azurefunctions/issues/419
