### ISSUE TITLE
functions-v2: Access to Table Storage very slow

### ISSUE THREAD

**Issue by henning-krause** [Azure/azure-functions-host#3077]
# Environment

Azure Functions V2, dotnet runtime

Microsoft.NET.Sdk.Functions version 1.0.14

Function runs in consumption mode.

# Setup

1. An Azure functionns which creates a few (5 in this case) jobs by putting job descriptions into a queue

2. Another function is triggered by the queue above, reads a file from Azure Blob Storage, parses it and creates a bunch of entities in a table storage (around ~120.000 per job).

When running this setup on my local computer, the whole thing completes in about 1:30-2:00 minutes and seems to be limited by my upstream bandwidth (40mbit).

When running on azure, execution time is around 6 minutes.

I have this code in my function:
```csharp
var account = CloudStorageAccount.Parse(Environment.GetEnvironmentVariable("StorageConnection"));
var tableServicePoint = ServicePointManager.FindServicePoint(account.TableEndpoint);
tableServicePoint.UseNagleAlgorithm = false;
tableServicePoint.Expect100Continue = false;
tableServicePoint.ConnectionLimit = 100;
```

In both cases (on-premise and cloud) I see that the functions triggered by the queue are running in parallel.

Any ideas what happens here? I would expect the cloud environment to be much faster because of lower latency and bigger bandwidth.

Can this be related to #850 ?

**Comment by mhoeger** [comment]
Hi @henning-krause, sorry about the delayed response!

It sounds like each of your functions is doing something that's pretty computationally intensive (namely, parsing that appears to take a long time). The machines that are running your consumption mode function app are likely significantly less powerful than your local machine. This sounds like expected behavior for us.

One way to choose a more powerful machine is to use an App Service plan. Please reopen if you think there is a separate platform issue!
