### ISSUE TITLE
Decouple dependency between language worker and their SDKs

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#3140]
Moving notes from email thread:

In v2 the dynamic extension loading that we’re doing means we don’t have to bake extensions into the runtime anymore. However, language workers have hardcoded bindings

-	For Python, there is a https://github.com/Azure/azure-functions-python-library (bunch of interfaces) that user code takes a direct dependency on.  Python language worker has implementations for these nicer types. Here is the [python bindings](https://github.com/Azure/azure-functions-python-worker/tree/dev/azure/functions_worker/bindings) list 
-	Java, has a similar library defined : https://github.com/Azure/azure-functions-java-library  but only has nicer types for HttpRequest and HttpResponse.  Here is [java bindings](https://github.com/Azure/azure-functions-java-worker/blob/0f83664f355d196654d7c67b00469302b0a8eeed/src/main/java/com/microsoft/azure/functions/worker/binding/BindingDefinition.java#L17) list
-	Node  does not have this dependency because we have not defined any sdk/library for java script functions

Adding a new binding in Java/Python requires updating their corresponding SDK and the language worker.

Need to investigate how to make the workers to be truly metadata driven

**Comment by pragnagopa** [comment]
cc: @mathewc

**Comment by mathewc** [comment]
We need to remove all binding extension specific stuff from the language workers. Workers should be able to handle all extensions purely based on extension metadata and operate on generic data types.

I'm also wary of the python-library/java-library helper libraries since it it just pushes the problem from the worker to another library, and that library now becomes dependent on extension specifics. E.g. if an extension Foo is added by a 3rd party and they see some first class APIs for queues coming from that library, they want to add some helpers there as well, and in general the size of that library grows with each extension.

I think the best place for us to be would be for the extension agnostic language worker to be rich enough such that it works for all extensions without any helper libraries being needed. If people need to operate against a service in a deeper way than exposed by Functions, they can pull in the corresponding language specific SDK (e.g. Azure Storage SDK, ServiceBus SDK, etc.). That's preferable than us owning a shim layer.

**Comment by fabiocav** [comment]
This, currently, only applies to Python.

Closing this in favor of https://github.com/Azure/azure-functions-python-worker/issues/66
