### ISSUE TITLE
Feature planning: first class Python support

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-host#335]
This is a tracking item for First Class Python Support. We'll be tracking the requirements and issues for first class Python support via this item. Feel free to leave comments about features/design patterns. 

The Functions team and the Microsoft Python team have engaged in a partnership to investigate first class Python support for the Azure Functions runtime.

## Programming Model : Basics
[https://github.com/Azure/azure-functions-python-worker/issues/2](https://github.com/Azure/azure-functions-python-worker/issues/2)

## Programming Model : Data Types
[https://github.com/Azure/azure-functions-python-worker/issues/3](https://github.com/Azure/azure-functions-python-worker/issues/3)

## HTTP Triggers and Bindings
[https://github.com/Azure/azure-functions-python-worker/issues/4](https://github.com/Azure/azure-functions-python-worker/issues/4)

## Execution Context
[https://github.com/Azure/azure-functions-python-worker/issues/5](https://github.com/Azure/azure-functions-python-worker/issues/5)

## Logging
[https://github.com/Azure/azure-functions-python-worker/issues/11](https://github.com/Azure/azure-functions-python-worker/issues/11)

## Environment variables
[https://github.com/Azure/azure-functions-python-worker/issues/12](https://github.com/Azure/azure-functions-python-worker/issues/12)

## Version & Package management
[https://github.com/Azure/azure-functions-python-worker/issues/6](https://github.com/Azure/azure-functions-python-worker/issues/6)

## Testing/CI
**TBD**

## Samples
- [HTTP Trigger example](https://github.com/Azure/azure-functions-python-worker/tree/master/Samples/HttpTrigger1/main.py)
- [Timer Trigger example](https://github.com/Azure/azure-functions-python-worker/tree/master/Samples/TimerTrigger/main.py)
- [Queue Trigger example](https://github.com/Azure/azure-functions-python-worker/blob/master/Samples/QueueTrigger1/main.py)

#### 1.  Entry point decorator
[https://github.com/Azure/azure-functions-python-worker/issues/8](https://github.com/Azure/azure-functions-python-worker/issues/8)

#### 2.  Access to bindings via **context**
TBD

## Change log

5/5 : Chris - Add basic list of feature areas
1/10 : Asavari - Elaborating on the feature areas and programming model
1/11 : Asavari - Adding info about package management and environment variables
1/18 - Adding Samples
1/19 - Incorporating community feedback
1/23 - Incorporating community feedback (part 2)
1/24 - Adding improvements to context and logger 
1/25 - Splitting into smaller issues and moving to the Python worker repo

**Comment by edevil** [comment]
Support a requirements.txt file and runtime specification for specifying Python 2 or 3.

**Comment by brettcannon** [comment]
I would take it further than "2 or 3" and make it be by major.minor version.

**Comment by anthonyeden** [comment]
The first step may be to publish some Python-specific documentation and examples.

For the benefit of anyone else trying to do HTTP Functions with Python right now, here's some basic example code I threw together: https://github.com/anthonyeden/Azure-Functions-Python-HTTP-Example/

**Comment by ryanga** [comment]
Add python examples for the Azure Functions DocumentDB bindings: https://azure.microsoft.com/en-us/documentation/articles/functions-bindings-documentdb/

**Comment by thdeltei** [comment]
Azure ML Studio currently let you publish Python and R webservices, which work in a similar way as Azure Functions. It would be great if Python in Azure Functions came installed with the Anaconda bundle. That would allow for a simpler integration between Azure ML and Azure Functions.

**Comment by paulbatum** [comment]
Support 64-bit Python.

**Comment by davidebbo** [comment]
Note that short term, it's possible to use a custom Python version using these steps: https://github.com/Azure/azure-webjobs-sdk-script/wiki/Using-a-custom-version-of-Python

**Comment by rawlukMike** [comment]
Solution above is not working anymore. I tried every step but in the end as long as you run inside home\site directory, you will always end up with Python 2.7.8.

Also why Python is so slow? It can takes up to 20s only at importing additional library. I tried virtual env and uploading full directory and running it from C# running cmd: "python.exe parameter". 
These should be instant, and yet is so long.

**Comment by davidebbo** [comment]
I just retested that technique and it works fine. Did you make sure to **expand** the zip as you dropped it in `D:\home\site\tools`?

The better perf will come with the first class support that this thread is tracking. No ETA, but we will get there.

**Comment by rawlukMike** [comment]
I am sorry for writing wrong. I tried Python 2.7.13 which have no embeddabled version.
Simply used zipped python with my site-packages.
Is there a way to use latest python 2.7.* with some libraries like pandas, xmltodict, numpy and so on... ?

**Comment by brettcannon** [comment]
See https://blogs.msdn.microsoft.com/pythonengineering/2016/08/04/upgrading-python-on-azure-app-service/ on how to upgrade Python.

**Comment by rawlukMike** [comment]
Is there any special step for functions? I managed to install python through site extension gallery, but how can i bind it to functions? Basicly how to translate Configuring Your Site from guide above to functions :). Sorry maybe its a simple dummy question.

**Comment by brettcannon** [comment]
Unfortunately for Functions I don't know.

**Comment by davidebbo** [comment]
@rawlukMike the instructions I liked to shoudl work for any Python version. If you drop Python in the Tools folder it should get picked up because it's on the path.

**Comment by rawlukMike** [comment]
Yep my bad. I used my python folder packed, but forgot msi installer puts python27.dll in system. Did not included it in library. When I used unpacked but not installed msi it works fine. Sorry for troubles.

**Comment by rawlukMike** [comment]
Coping fully working Python 2.7.13 to the \home\site\tools is not working.
It worked for 3.x for some reason.
@davidebbo You said that site\tools is in the PATH however Kudu show otherwise. It says '\site\deployments\tools' is in the path.
I unzip python in \home\site\deployments\tools (This one is IN PATH).
After that running in KUDU example: \home\python.exe -V started showing new one.
So it should work right?
Except its not.
I made simple Python function:
import sys
print(sys.version)
And it results with 2.7.8. With Python 2.7.13 installed in site\deployments\tools and being visible in Kudu as "primary".

So two questions here :).
1.Why even though KUDU is seeing Python from Path (actually there are two line in PATH pointing to python exe now : D:\home\site\deployments\tools, and D:\Python27), Functions still call old one?
2. Why coping Python 3.5 to D:\home\site\tools is working the first place since this one is not in PATH.

**Comment by davidebbo** [comment]
@rawlukMike `site\tools` is what's on the path for Functions execution. Kudu uses a different one which is for deployment tools, and is not on the path in the Functions runtime. Anyway, glad it's working for you now!

**Comment by rcarmo** [comment]
So I'm going down this particular rabbit hole, and keep bumping my head against the peculiarities of git deployment. 

As nice as the portal UI is, I think there ought to be a hard requirement/user story that a Mac/Linux developer should only need to `git push` source code to the service to get a function going, and libraries be deployed either via Kudu (which is tedious and quirky, but passable) or automatically upon detection of the function config files and a `requirements.txt`.

I'm also not very keen on the current environment variable approach, since it limits the kinds of data functions have readily available.

There ought to be an `import context from azure.functions` (or similar) to abstract that away and provide a nicer way to deal with inputs and outputs, somewhat like the current JS API.

**Comment by thdeltei** [comment]
I am running into extreme slowness when trying to run the [Azure Batch Shipyard](https://github.com/Azure/batch-shipyard) python-based CLI. A single call using the subprocess takes 2min30 which in turns brings my Function to timeout after 5min because I require two calls to do my orchestration. Any reasons why it is so dog slow to use Python on Azure Function? Is there a way I could make it faster?
Right now I do a subprocess call to the Python35 executable installed via the extension on the kudu platform.

**Comment by rcarmo** [comment]
Hmmm. My experience with wsgi apps on App Service has been very good (even before the new Python extensions came out) so I suppose there'a a penalty involved with forking a subprocess for whatever reason (maybe loading/startup time?).

Just a thought: can you output a log with some timestamps down to the millisecond? That might help figure out where the delay is.

**Comment by thdeltei** [comment]
I switched to the hosted plan and it became much more manageable ~5 seconds per subprocess call.
A simple subprocess call to a 'hello world' python script took between 2-7s.

**Comment by rcarmo** [comment]
Ah, right. But it's still a penalty. Can you figure out the split between startup time and your code execution? And if you're using 3.5, have you considered coroutines? (if they fit your problem, that is)

**Comment by quangv** [comment]
sorry slightly off-topic, but what are currently a first-class citizen on Azure?

Just from a short Google search, I'm guessing:

.Net
Node.js
Java
Docker
Linux
Windows (assuming)

is anything else a first-class citizen?

**Comment by paulbatum** [comment]
@quangv this issue is not the appropriate forum for such a general question. Please keep this issue focus on Python. Thanks!

**Comment by oribarilan** [comment]
Looking forward to Python support in VS Tools for Azure Functions and of course for Python templates in the Azure portal. Thanks!

**Comment by Krande** [comment]
Hey, could you provide some sample code for python using a blob storage trigger of a specific file and performing some operations on the content (say a simple textfile/xml/json) and return a new/updated version of the file back to the storageblob?

**Comment by Krande** [comment]
I used the portal for testing the sample code.

**Comment by rcarmo** [comment]
I think an update is in order here - I need visibility on when/how this is coming along...

**Comment by ttelfer** [comment]
An update would be much appreciated. It has been over a hear since this thread was started. Will Python ever be a first class language for Azure functions?

**Comment by fabiocav** [comment]
There has been a significant amount of work done in the language extensibility feature we're introducing in 2.0 (the next version of the Azure Functions runtime). And although that work is not Python specific (hence the lack of updates here) it is a foundational component that will enable the Python support with the model we have planned for the next iteration. 

We don't currently have dates for that, we'll keep this issue updated as things progress.

**Comment by LarsKemmann** [comment]
@fabiocav Is the "experimental" Python support that's visible in the Azure Portal today based on the 2.0 runtime?

**Comment by paulbatum** [comment]
@LarsKemmann No. In fact its based on an implementation that we do not intend to port to 2.0 because it will never perform well. So you'll notice if you make a function app and switch its version to beta (i.e. 2.0) and then go to make a new function, the python templates disappear (along with a bunch of others).

**Comment by asavaritayal** [comment]
Adding our current thinking on this. Please feel to leave comments about features/design patterns. @brettcannon thanks for your contribution and feedback on the first draft!

**Comment by Krande** [comment]
Is python 2.7 no longer supported?

**Comment by paulbatum** [comment]
@Krande It depends on what you mean by supported exactly. The experimental feature of creating python based functions still exists in functions v1 and it uses python 2.7.8. However as I mentioned above, there are significant performance issues with it and we don't plan to bring that implementation into general availability with full support, etc. This issue tracks implementing python support in functions v2 with an implementation that would have good performance characteristics and can be fully supported. The current plan would be for this implementation to target python 3.6, but I think there still needs to be more discussion and planning around this topic (can we support multiple python versions, etc).

**Comment by christopheranderson** [comment]
We are planning on making heavy use of the `async` library, which requires Python 3.4 or higher. That informs our current desire to avoid 2.7, but would love feedback on specific cases where 2.7 support would be required and 3.4+ wouldn't work.

**Comment by berndverst** [comment]
Pipenv and Python 3.6+ seem like the way to go IMO. For anything else customers will still be able to bring their own containers.

I imagine a lot of people will still provide a `requirements.txt` instead of `Pipfile` or `Pipfile.lock`. In that case I recommend installing packages via `pipenv install -r requirements.txt`. In the case where either `Pipfile` and/or `Pipfile.lock` are provided, `pipenv install` should do the trick.

**Comment by Krande** [comment]
Okay, I believe most of my python 2.7 code should be relatively easy to port to python 3.6. My experience with python 2.7 on azure functions is that once I add packages such as numpy and scipy I see a performance decrease running functions. Would that by any chance be related to the performance issue you mention (paulblatum) in v1? If so then that would be a welcome change!

**Comment by brettcannon** [comment]
@Krande I'm not on the Functions team, but based on how they have explained the v2 infrastructure to me I believe it will definitely be improved in v2 as functions will be imported once and so any start-up/import overhead will be cut out.

**Comment by pragnagopa** [comment]
@asavaritayal - over all looks good. 
- Add sample functions.json that uses  type property  - "Alternately, you can define the data type using the type property in the function.json configuration"
- Update table under Context section to use context instead of executionContext
- Need more details on what different log levels mean. For example, see [NodeJS Logging](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#writing-trace-output-to-the-console) and how to they can surface in AppInsight logs. Also, host.json has a [tracing ](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#tracing) setting we need to use that instead of defining "logging"

**Comment by asavaritayal** [comment]
Issue update: Incorporating community feedback and adding some samples.

**Comment by brettcannon** [comment]
One thing I realized is my suggestion to put the main function in a `__main__` module might be too "cute" as it would prevent people from conveniently e.g. starting a test instance by pointing Python at the directory that contains your function code. Not sure what others think or what module name I would recommend instead (I know Asavari has suggested index.py to match the Node side), but I'm starting to think my initial suggestion for this was bad.

**Comment by 1st1** [comment]
A few thoughts/questions:

1. We can support both async- and sync- functions: if the `main()` function is synchronous (no `async` qualifier) we automatically run it in an asyncio thread-pool:

    ```python
    # Would be run with asyncio directly
    async def main():
        await some_nonblocking_socket_io_op()

    # Would be run in an asyncio thread-pool
    def main():
        some_blocking_socket_io()
    ```

    This approach gives the user a choice of what libraries they want to use. This way async/await becomes an *opt-in*.

2. I agree with @brettcannon that using `__main__.py` module can be suboptimal. `__main__.py` has a very special meaning in Python: if an 'abc' package has a `__main__.py` file, it gets run on `python -m abc`.  So a Python package may have a few `__main__.py` files in it, that are not intended to be used by Azure Functions.  We probably want to pick another name to avoid potential problems here.  By the way, is it required to have a `function.json` file per runnable Python function?

3. `context` argument: is it optional?  Do we want to auto-detect it?  If it's the latter, we can make it a keyword-only required argument:

    ```python
    # The 'context' argument will be injected automatically
    async def main(my_input: str, *, context: Context):
        pass
    ```

    We can do the same for `context.logger`—decouple it from the Context and pass it as a separate keyword-only argument:

    ```python
    # 'context' and 'logger' arguments will be injected automatically
    async def main(my_input: str, *, context: Context, logger: Logger):
        pass
    ```

4. Will we have a dedicated Azure Functions user module?  That way we could provide functions to capture the current Context object instead of injecting it as an argument:

    ```python
    import azure_functions

    async def main():
        context = azure_functions.get_context()
    ```

    The package could also contain helpers and fixtures for writing unittests.

5. Having an explicit entry point decorator is a neat idea.  Maybe this should be the one and only way of marking a Python function as runnable?  I.e. it's perfectly fine to have a Python file with many helper functions none of which should be directly runnable:

    ```python
    import azure_functions

    # Private helper function
    def helper():
        return 42

    # Directly runnable function
    @azure_functions.export
    def main():
        return helper()
    ```

**Comment by asavaritayal** [comment]
Thanks Brett and Yury for taking the time to think through this. Some notes below - 

1. Agree that we should support both async and sync, to allow flexibility of library and enable straightforward demo scenarios. That said, our docs should emphasize why it's important to use async to get more out of the language worker. I'll add this to the docket for later. 

2. @1st1, @brettcannon  - A few options are: main.py or `__run`__.py . Let me know if one of these seems to resonate more, or you have other suggestions. To answer the second part : yes, we do require a function.json file per Function to define the corresponding bindings and their attributes. In fact, the portal UI lets you edit this file in the 'Integrate' tab beneath each function seperately. 

3. Since **logger** is going to be the only way to write trace outputs to the console, it makes sense to decouple it from context and provide as a keyword-only required argument. 

4. Open to the idea of having a dedicated module for Azure Functions. We've done this for a few other languages in the past and can discuss the pros/cons.

5. For consistency across all languages, we'd like to keep the **entryPoint** attribute of  function.json. Given the time, I'd love for us to have a decorator and promote it as the primary way to declare an entry point in the script.

**Comment by 1st1** [comment]
> @1st1, @brettcannon - A few options are: main.py or __run__.py . Let me know if one of these seems to resonate more, or you have other suggestions. To answer the second part : yes, we do require a function.json file per Function to define the corresponding bindings and their attributes. In fact, the portal UI lets you edit this file in the 'Integrate' tab beneath each function seperately.

If we require a `function.json` file, then maybe we don't need any special filenames for Python scripts?  We can require the user to specify the name of the Python file and the name of the function in it in their `function.json` file.

**Comment by rcarmo** [comment]
Yes, please. I’d like to be able to pick my own name for the entry point.

**Comment by brettcannon** [comment]
The idea that @1st1 had about just putting it into `function.json` works for me. That would let people specify the dotted name to the callable object and thus provide anything that they want to call, including an instance of an object for a specific method, e.g.:
```python
# In mypkg.mod
class MyFunc:
   def main(self, *args, **kwargs):
      ...

main = MyFunc.main
```
And then in `function.json`:
```json
...
'function': 'mypkg.mod.main`
...
```

That way users have more flexibility and the only real requirement is that the object be callable.

**Comment by asavaritayal** [comment]
We're moving this issue to its own repo - [https://github.com/Azure/azure-functions-python-worker](https://github.com/Azure/azure-functions-python-worker). For comments / feedback, please find the relevant issue in the new repo.

**Comment by sergei3000** [comment]
The links under "Samples" in the opening post are not working

**Comment by BhaskarDasari** [comment]
hi can you support requests module inside functions?

Hi azure function is not recognising the requests module . pasted the error and code please suggest the fix

exception:
File "D:\home\site\wwwroot\test\run.py", line 1, in 
import requests
ImportError: No module named requests
.
python code:
import requests
import timeit
import datetime

def run_gomupload():
try:

     start_time = timeit.default_timer()
     cdate =datetime.datetime.now()
     print('Cell Start Time: '+ str(cdate))
        
     # code you want to evaluate
     elapsed = timeit.default_timer() - start_time

     cdate=datetime.datetime.now()

     print('\nCell End Time: '+ str(cdate))

     print('Cell Run Duration: '+ str(elapsed))
     # Clean up resources. This includes the container and the temp files
     #os.remove(full_path_to_file) 
except Exception as e:
    print(e)

**Comment by paulbatum** [comment]
@BhaskarDasari - please post your question to stack overflow, msdn forum, or as a separate issue in https://github.com/Azure/azure-functions-python-worker - thanks!

**Comment by asavaritayal** [comment]
Closing thread as the discussion has moved to the repo here - https://github.com/Azure/azure-functions-python-worker/issues
