### ISSUE TITLE
Global Function Filters In v2.0.12050.0 (and above)

### ISSUE THREAD

**Issue by mayoatbm** [Azure/azure-functions-host#3401]
Hey folks,

How do we use global function filters in the newest version of the runtime? 

We did this in the past by using the Config property on the ExtensionConfigContext to get the IExtensionRegistry service. That Config property is now gone and our code does not compile (much less run).

What are we missing?

**Comment by ArtyomBaranovskiy** [comment]
@mayoatbm I'm not sure if it's well documented already, but it seems possible to add global filters to internal DI within custom Startup class Configure call:
```
[assembly: WebJobsStartup(typeof(Startup), "Test")]

namespace Test
{
    public class Startup : IWebJobsStartup
    {
        public void Configure(IWebJobsBuilder builder)
        {
            //previously I was registering global filters inside the custom extension config provider
            builder.AddExtension<ExtensionConfigProvider>();
            //now it's even easier to register it
            builder.Services.AddSingleton<IFunctionFilter, FunctionFilter>();
        }
    }
}
```
It's working like a charm when building and running locally (bin\extensions.json is generated correctly and contains my custom Startup type).
However, when trying to Pack & Publish to Azure Function App from Visual Studio 15.8.3, I'm observing the issue not having my custom Startup type added to the publish\bin\extensions.json automatically, so I just edit it in the portal after publishing and restart the app manually for now (investigating - maybe that's just my local setup issue).

**Comment by mayoatbm** [comment]
@ArtyomBaranovskiy Thanks for the heads up, that does work locally.

@mathewc @paulbatum The situation with Function Filters doesn't look good in GA and going forward. We now get the obsolete warnings message below. 

![function filters obsolete](https://user-images.githubusercontent.com/29760620/46384473-f8ee4d00-c66a-11e8-9bab-a916292e11fd.png)


We've built key parts of our function apps on Filters (e.g. Scope cleanup for DI as in Azure/azure-webjobs-sdk#1865) and we very much need the functionality they provide (being able to run code before and after function executions). 

Can you confirm that you'll be replacing this functionality and not removing it entirely? And what would the timeline be?

**Comment by mathewc** [comment]
We are not removing Filters - we applied Obsolete attribute to those APIs because unfortunately we didn't have time to finish the feature before we had to release the v3 SDK. The work remaining that we didn't have time to complete was to rationalize filters with all the new DI work that was done. I'm hoping we can get to this soon and finish the feature.

**Comment by mayoatbm** [comment]
@mathewc That's good news. The Obsolete warning was alarming because of how much we've built on filters. I would suggest adding this clarification somewhere in the release notes, function filter docs or even in the annotation message itself.

Thanks!

**Comment by jeevanbalanmanoj** [comment]
I’m looking to handle exceptions at a function app level for my http triggered azure functions similar to how it is done in dotnetcore apps with ‘ExceptionFilterAttribute’. My goal is to catch all uncaught exceptions  in the application at a single place and prepare the http response for the error scenario. I see that there is ‘IFunctionExceptionFilter’ which has a method ‘OnExceptionAsync’. However I’m not sure how I can get the context in this method so that I can manipulate Response to provide the right error messages. Also I believe this can only be done at a function level and not at the function app level. I also came across the [ErrorHandler] attribute here. However I’m not sure how I can use it.
Any help with this will be great. Below is the code that works in asp.net core mvc. I want to achieve the same in azure functions

OnException method in ExceptionFilterAttribute

public override void OnException(ExceptionContext context)
        {
            Exception ex = context.Exception;
            context.Result = ResponseHelper.GetErrorResponse(ex);
        }

Get ErrorResponse method returns an object which implements IActionResult

**Comment by AvinashRamalingam** [comment]
> I’m looking to handle exceptions at a function app level for my http triggered azure functions similar to how it is done in dotnetcore apps with ‘ExceptionFilterAttribute’. My goal is to catch all uncaught exceptions in the application at a single place and prepare the http response for the error scenario. I see that there is ‘IFunctionExceptionFilter’ which has a method ‘OnExceptionAsync’. However I’m not sure how I can get the context in this method so that I can manipulate Response to provide the right error messages. Also I believe this can only be done at a function level and not at the function app level. I also came across the [ErrorHandler] attribute here. However I’m not sure how I can use it.
> Any help with this will be great. Below is the code that works in asp.net core mvc. I want to achieve the same in azure functions
> 
> OnException method in ExceptionFilterAttribute
> 
> public override void OnException(ExceptionContext context)
> {
> Exception ex = context.Exception;
> context.Result = ResponseHelper.GetErrorResponse(ex);
> }
> 
> Get ErrorResponse method returns an object which implements IActionResult

Can we get this feature implemented part of V3? This article https://social.msdn.microsoft.com/Forums/en-US/98a7c43a-eac1-42bf-9fcc-23e3e9fff34d/should-we-go-ahead-and-implement-functionfilters-in-azure-function-in-production?forum=AzureFunctions

says we can go ahead and implement Azure Functions Filter with all the already implemented features. Warns only for the feature which is still in progress.

Please clarrify! Thanks.

**Comment by rohitgkr** [comment]
I am looking for a confirmation as well. Can someone confirm this is threadsafe based on the following comment?
https://github.com/Azure/azure-webjobs-sdk/issues/1934#issuecomment-425215908

**Comment by amang2205** [comment]
+1
What is the status on Function Filters?
