### ISSUE TITLE
Queue batchSize is not respected with function app version 2.0.11961-alpha on a consumption plan

### ISSUE THREAD

**Issue by scott-lin** [Azure/azure-functions-host#3499]
My function is running on a consumption plan. I have configured my queue `batchSize` to be `4`, but `16` messages are being processed concurrently still.

#### Investigative information

Please provide the following:

- Timestamp: `9:02:19.804 PM PST`
- Function App version: `2.0.11961-alpha`
- Function App name: `devautorest-functions`
- Function name: `autorestprocessor`
- Invocation ID: `84327cc6-b9bf-4381-b9c6-0bb69d5b9113` (there are 15 more invocations at the same timestamp)
- Region: `west us 2`

#### Repro steps

Provide the steps required to reproduce the problem:

1. Set function version to the above.
2. Configure host.json to:

```
{
  "version": "2.0",
  "functionTimeout": "00:10:00",
  "extensions": {
        "queues": {
            "maxDequeueCount": 5,
            "batchSize": 4,
            "newBatchThreshold": 2
        }
    }
}
```

3. Restart the function
4. Clear all messages in the queue
5. Pump a bunch of messages into the queue to trigger processing
6. Sixteen messages from the queue are processed concurrently

#### Expected behavior

At step six, I expect 4 items to be processed concurrently instead of 16.

#### Actual behavior

At step six, 16 items are processed concurrently.

#### Related information 

Provide any related information 

* Javascript
* Bindings used
```
{
    "bindings": [
        {
            "name": "clientLibraryId",
            "type": "queueTrigger",
            "direction": "in",
            "queueName": "clientlibraryrequest",
            "connection": "STORAGEACCOUNT_CONNECTIONSTRING"
        }
    ],
    "disabled": false
}
```

**Comment by scott-lin** [comment]
Actually, I believe my host.json file changes are not being picked up at all? After restarting my function app, I see a trace in App Insights that says `Host configuration file read: { "functionTimeout": "00:10:00" }`, which is not the complete configuration I saved. Unless of course, the `extensions` object is omitted for some reason from this trace... that'd be strange though.

**Comment by mathewc** [comment]
Thanks for all the details. Your queues configuration looks correct. However as you suspected, those settings only apply to each function app instance - they aren't global settings.

Regarding the host configuration log file statement - because host.json may contain secrets, etc. we employ a filtered whitelist strategy an only log certain values. However after recent changes, we didn't update that logging code, so we're no longer logging the "queues" section like we used to (since it moved under an "extensions" property). I logged https://github.com/Azure/azure-functions-host/issues/3507 for this.

What is your goal - you need to reduce concurrency?

**Comment by scott-lin** [comment]
> What is your goal - you need to reduce concurrency?

Yes, I'd like to reduce concurrency.

I only have one "function" in my "function app", so I expected the settings to kick in for my scenario. How can I achieve this behavior?

> those settings only apply to each function app instance - they aren't global settings.

Can you also define "function app instance" for me?

**Comment by mathewc** [comment]
A Function App is a collection of functions. That collection of functions can be scaled out to multiple VM instances based on load. The host.json config settings for the various triggers (e.g. queues) apply to a single instance.

So using those settings you're able to control concurrency on a single instance. To control global concurrency you need to control how much your app scales out. Since you're in Dynamic, we'll end up scaling you out if we see your queue is backing up, which it sounds like isn't what you want. Your options are to limit scale out via the WEBSITE_MAX_DYNAMIC_APPLICATION_SCALE_OUT setting detailed [here](https://github.com/Azure/azure-functions-host/wiki/Configuration-Settings), or to move to an AppService plan where you control the instance count.

**Comment by scott-lin** [comment]
> functions can be scaled out to multiple VM instances based on load

Thanks. Few more questions since I'm ultimately trying to performance test my function in a consumption plan.

- What are the specs of consumption plan VMs? I believe they're 1 core with 2GB memory if I'm not mistaken?
- When scale out occurs, does each new instance get their own 1 core/2 GB memory, or whatever the specs are?
- How many VMs can be scaled out to on a consumption plan?

I know the algorithm is hidden and tweaked all the time, but this information will help us understand the limits of our app.

**Comment by paulbatum** [comment]
Its basically 1 core, 1.5GB per instance. We have some artificially enforced limits that put the max number of instances around 200, but there are some scenarios that can go past this and we have some flexibility to help customers if they hitting this limit on a case-by-case basis.

**Comment by scott-lin** [comment]
@mathewc or @paulbatum, any insights into my observation? Let me know if more details are needed.

**Comment by dlalex83** [comment]
@scott-lin did you manage to understand what the issue was there? I'm currently having the exact same problem where batchSize: 1 and newBatchThreshold: 0 but the functions is invoked way more times (10+).

**Comment by paulbatum** [comment]
@scott-lin @dlalex83 please share your current host.json and invocation ID, UTC timestamp, region where this occurred (see [here](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)).

**Comment by scott-lin** [comment]
Since this issue was specific to Consumption Plan and by design/closed long ago, I had already create a separate issue specific to App Service Plans. See it at https://github.com/Azure/azure-functions-host/issues/3532, which was opened three weeks ago. Hopefully it can be used to track the issue.
