### ISSUE TITLE
función en azure, no me muestra el lenguaje python. No permite instalar librerias en el servidor

### ISSUE THREAD

**Issue by Dennis0095** [Azure/azure-functions-host#3530]
Buen día, he creado una función en azure con javascript, ya que no me permite crearlo .
No me permite realizar solicitudes con el REQUEST. Luego, intento instalarlo, pero no se puede
porque no tengo permisos para acceder al servidor.""

Alguien que le haya pasado lo mismo,? Alguien saber si una cuenta free de esos ciertos liits+

**Comment by pragnagopa** [comment]
Translated to english:

 function in azure, it does not show me the python language. It does not allow to install libraries on the server

Good day, I created a function in azure with javascript, since it does not allow me to create it.
It does not allow me to make requests with the REQUEST. Then, I try to install it, but you can not
because I do not have permission to access the server. "

Someone who has been the same ,? Someone know if a free account of those certain liits +

**Comment by pragnagopa** [comment]
@asavaritayal - Any ideas?

**Comment by pragnagopa** [comment]
This issue was moved to Azure/azure-functions-python-worker#211
