### ISSUE TITLE
Function 2.0: Table storage binding is not working if there are any reference to class library that references Windows.Azure.Storage 9.3.2

### ISSUE THREAD

**Issue by Anufriev** [Azure/azure-functions-host#3572]
#### Repro steps

1. Create a solution and create a new simple function app 2.0  project (FunctionApp) with a timer trigger function
2. Add Microsoft.Azure.WebJobs.Extensions.Storage 3.0.0 nuget package
3. Add '[Table("testTable")] CloudTable table' argument to the function
4. Run function - ok
5. Add a new standard 2.0 library (ClassLibrary) to the solution
6. Add Windows.Azure.Storage 9.3.2 nuget to the class library project. This version is the same as version that is used by Microsoft.Azure.WebJobs.Extensions.Storage.
7. Add reference to the class library project to the function app project
8. Run the app

#### Expected behavior

No exceptions

#### Actual behavior

System.InvalidOperationException: 'Can't bind Table to type 'Microsoft.WindowsAzure.Storage.Table.CloudTable'.'

#### Known workarounds

Do not use any library that references Microsoft.Azure.WebJobs.Extensions.Storage nuget.

#### Related information 

* [repository](https://github.com/Anufriev/functionAppTableStorageBindingBug)
* ![image](https://user-images.githubusercontent.com/1809671/46569653-9940bc00-c960-11e8-86b3-ce288742d5b6.png)

**Comment by Anufriev** [comment]
Anu updates?

**Comment by maiqbal11** [comment]
Hi Aliaksandr, 

When I use Visual Studio to create a TimerTrigger project and then reference Microsoft.Azure.WebJobs.Extensions.Storage 3.0.0, I am seeing WindowsAzure.Storage 9.3.1 as the default rather than 9.3.2. Are you using the default Visual Studio experience to create the Functions project?

Using WindowsAzure.Storage 9.3.1 for both the Function App and the Class Library, I did not see the exception. However, using 9.3.2 for the class library produces an exception - likely because there is a conflict there. You should be able to unblock yourself by using 9.3.1 as the Azure storage nuget package. Attaching a screenshot of my working configuration:

![capture](https://user-images.githubusercontent.com/42051041/47227399-9342d600-d377-11e8-9a4e-e8a3fa6d00a5.PNG)

**Comment by JohnReeson** [comment]
A blobtrigger with type `CloudBlockBlob`, simply reference 9.3.2 Storage package in the function project also causes similar error.

**Comment by Anufriev** [comment]
@maiqbal11 Thanks for the work around. 
Actually  app works if 9.3.1 was explicitly added to the function app.
But it still do not work with 9.3.2

**Comment by kashimiz** [comment]
Another incidence of this was reported on StackOverflow [here.](https://github.com/Azure/azure-functions-host/issues/3572)

**Comment by maiqbal11** [comment]
There is a known issue where users are unable to specify versions higher than 9.3.1 and  it is being tracked here: Azure/azure-webjobs-sdk#1942. Closing this issue in favor of the one currently tracking.
