### ISSUE TITLE
Every JavaScript V2 HTTP-triggered function gives 404 in Azure - runs fine locally

### ISSUE THREAD

**Issue by ChristianWeyer** [Azure/azure-functions-host#3602]
I have a created a very simple and plain HTTP-triggered JavaScript function in VS Code - all with the latest runtimes and tools.
You can find it here: https://github.com/ChristianWeyer/azure-functions-js-http-repro

Running it locally, everything is fine, e.g. http://localhost:7071/api/ping
However, after deploying it (via VS Code) to Azure, I get a 404. E.g. https://cwplayground.azurewebsites.net/api/ping

BTW: this happens with all the HTTP-triggered JavaScript functions I have tried to build and deploy.

**Comment by mhoeger** [comment]
@ChristianWeyer - I know you commented on https://github.com/Azure/azure-functions-host/issues/3584, but did changing or adding the App Setting FUNCTIONS_WORKER_RUNTIME => node work as a workaround to unblock you?

**Comment by ChristianWeyer** [comment]
Indeed, that helped. Sorry for not having seen this :-/

Is there any ETA for a fix?
Thanks!

**Comment by mhoeger** [comment]
@ChristianWeyer - glad that helped! Could you tell us how you deployed your function? And do you have FUNCTIONS_WORKER_RUNTIME defined in local.settings.json?

**Comment by ChristianWeyer** [comment]
I deployed it via the Azure tools in VS Code.
![image](https://user-images.githubusercontent.com/888718/46866192-afe38900-ce20-11e8-8cda-deae212dcbb3.png)

Yes, the setting is there:
![image](https://user-images.githubusercontent.com/888718/46866209-c853a380-ce20-11e8-9082-da2973812921.png)

**Comment by mhoeger** [comment]
@ChristianWeyer - I've haven't been able to repro your issue when creating a new function app and  deploying through VS Code (see image).
![image](https://user-images.githubusercontent.com/8888531/47032152-811e2900-d126-11e8-8b71-183c314640d5.png)

I think that the function app you're deploying to may have been created with runtime stack of "dotnet", which gave it the FUNCTIONS_WORKER_RUNTIME app setting of "dotnet". By default, local.settings.json environment variables are not copied over, as App Settings are often secrets and credentials.

We do want to improve this experience though, because FUNCTIONS_WORKER_RUNTIME does not change in local vs. prod. The tracking issue for that fix is here: https://github.com/Azure/azure-functions-host/issues/3120

**Comment by ChristianWeyer** [comment]
So, I guess we can close it for now.
