### ISSUE TITLE
[Question] Where is the correct way to WRITE temporary data folder locally in azure function?

### ISSUE THREAD

**Issue by andrew-vandenbrink** [Azure/azure-functions-host#3626]
I got this statement from azure support

![image](https://user-images.githubusercontent.com/12871379/47066557-cf92fc80-d1e6-11e8-92ea-89d6094a165a.png)

https://github.com/Azure/azure-functions-host/wiki/Retrieving-information-about-the-currently-running-function

01. Is this statement true?

> writing data to the D:\home\site\wwwroot\Data directory, and every file change under D:\home\site\wwwroot is signaling the function's host to recycle

Which causing this issue
https://github.com/Azure/azure-functions-durable-extension/issues/472
and this https://github.com/Azure/azure-functions-host/issues/1690

02. This statement,

> As a workaround, we suggest you write data files under D:\home\Data (NOT under site\wwwroot) instead to avoid recycling the function host so frequently. It will improve performance.

Should I really do write to D:\home\Data ? (its a workaround which I don't want to do btw)
How to refer to that directory? I don't want to hard code it
If I really have to do it, please put the recommendation somewhere in the wiki so everyone know
https://github.com/Azure/azure-functions-host/wiki/Retrieving-information-about-the-currently-running-function

**Comment by andrew-vandenbrink** [comment]
Statement 1 is true

![image](https://user-images.githubusercontent.com/12871379/47223884-9317fa00-d3ba-11e8-9dfd-b3d0cc46b19d.png)

**Comment by andrew-vandenbrink** [comment]
![image](https://user-images.githubusercontent.com/12871379/47225933-84801180-d3bf-11e8-8b3c-525d5015f710.png)

**Comment by cgillum** [comment]
Hi, I did the investigation for your issue and wrote the statement which you received from Azure Support. :)

The recommended location for writing data is `D:\home\data`.  If you don't want to hardcode it, you could alternately write to `%HOME%\data` (`%HOME%` refers to `D:\home`).

Alternatively, if it is transient data only intended for the local function execution, then writing to `%TEMP%` is also an option (and will probably be faster since it writes to the local VM storage instead of your app content storage).

More information can be found here: https://github.com/projectkudu/kudu/wiki/Understanding-the-Azure-App-Service-file-system

**Comment by andrew-vandenbrink** [comment]
Thank you!
