### ISSUE TITLE
Locking issue with DLLs in Functions

### ISSUE THREAD

**Issue by 4c74356b41** [Azure/azure-functions-host#3631]
Same issue as https://github.com/Azure/azure-functions-host/issues/569

#### Investigative information

Please provide the following:

- Timestamp: 
- Function App version (1.0 or 2.0): 2
- Function App name: mk-prd-we-kingfisher-FunctionApps
- Function name(s) (as appropriate): 
- Invocation ID:
- Region: west europe

#### Repro steps

go to the file storage behind functions and try to delete .pdb or .dll file
example: mk-prd-we-kingfisher/site/wwwroot/bin/Kingfisher.FunctionApp.dll
it doesnt work (file in use)

#### Expected behavior

Provide a description of the expected behavior.

go to the storage behind functions and try to delete .pdb\.dll file
it does work

#### Known workarounds
Provide a description of any known workarounds.

Use slots to do the swap and deploy to the new slot

We tried all the workaround in the linked article, none of those work

**Comment by fabiocav** [comment]
@4c74356b41 want to make sure I'm understanding this correctly. Are you stopping the application before trying to delete a file?
This behavior is expected if that is not the case. Files in the backing store will be locked while the Function App is running.

**Comment by 4c74356b41** [comment]
1. ???
2. no, portal
3. probably yes.

**Comment by fabiocav** [comment]
Somehow my first question was truncated, it was:
- Are you leaving the application in a stopped state when you try to delete those files? 
- To clarify, the portal UI are you are using is the storage account's Files blade, is that correct?
![image](https://user-images.githubusercontent.com/2507935/47169666-f9b4ef00-d2b8-11e8-86aa-fdf1f03620c5.png)

If you're sharing the storage account and Files share with other Function Apps, this could be problematic as if the other Apps are running, they would keep those files locked.

An approach that would work for you is, before attempting to delete any files, create/copy a file named `app_offline.htm` under `wwwroot`. This will cause the host using that backing store to restart and not load any of your files, leaving them unlocked.

**Comment by 4c74356b41** [comment]
1. yes
2. yes
3. we had that file in the root while trying
4. those particular files are not used by other functions

**Comment by fabiocav** [comment]
To scope this down, and make sure your other function apps aren't playing a role here, is this something you can repro on a new app with a dedicated storage account? 

What is your scenario? What flow requires you to delete those files using the UI interface?

**Comment by ma-gu** [comment]
Hello @fabiocav , I'm the one who met this issue. Let me clarify a situation a little bit.

My initial intention was to deploy a function after making some code changes. I've tried to deploy it via VS2017 and deployment was failed due to locked .dll file with function code. I've met such situation before, so I just went and stopped Azure Function - deployment still failed after. After I've found #569 and have itteratilvely added `<EnableMsDeployAppOffline>True</EnableMsDeployAppOffline>` to publish profile - no luck; `MSDEPLOY_RENAME_LOCKED_FILES=1` to application settings - still no luck. The only thing have changed after - now VS during deployment compalined about .pdb file of the same .dll. And only after that I've tried to delete it via Azure Portal in Files blade of related Storage. By the way - at this point app_offline.htm already was inside of wwwroot. And application still was in stopped state.
I went to sleep after, but in the morning I still found that .pdb file locked - at this point I just decided to add a slot, deploy application there and swap slots. 

We have several applications sharing the same storage, but they use separate file shares - I would expect it shouldn't be any impact from other applications (though maybe I wrong here). Here's a screenshot of file shares:

![image](https://user-images.githubusercontent.com/13116798/47174013-35cb6c80-d318-11e8-8c13-a46f7b17f31f.png)

So answering explicitly on your question - basically we don't have such scenario for direct deleting file via portal, that was last try because of hopelessness. We just need to be able to deploy application modifications smoothly.

I don't think it would be easy to reproduce - we have 17 applications and met such situation only once, I'm pretty sure that we won't be able to repro this on dedicated storage account.

**Comment by fabiocav** [comment]
Thank you for the additional details. That was very helpful, including the detail on which file was showing as locked. Having different shares does indeed mean that different function apps won't step over each other. It would be interesting to find out which process has a lock on the file you're having trouble with, as if `app_offiline.htm` is present, and particularly if the application is stopped, it's unlikely that the functions runtime would be the one holding those locks. 

Out of curiosity, do you  have remote debugging enabled on that function app? Have you performed a remote debugging operation on it?

**Comment by ma-gu** [comment]
Remote debugging is switched off. I remember I have switched on it on some application, but haven't used it for sure. I have used Kudu tool, which starting separate w3wp.exe, though I'm expecting it shouldn't use any of my application files. Also I remember that I have tried to run PerfView from d:\devtools\perfview\, but without much success - it has failed due security exception, seems there are not enough permissions for that. But I don't remember for sure if it was on kingfisher-FunctionApps.

As a theory - could any of dll/pdb files inside wwwroot be locked because of some actions in Kudu/console?

**Comment by soninaren** [comment]
Please re-open this issue if you are still experiencing this.

**Comment by jjr2527** [comment]
I continue to run into this issue with Visual Studio 2019 when deploying a function while the function s stopped in Azure.  I toggled the EnableMsDeployAppOffline publish profile setting to True and it resolved the issue.

Perhaps this setting should be set to true instead in the default publish profile?
