### ISSUE TITLE
Azure Function Visual Studio Debug Window Closes/Stops Running

### ISSUE THREAD

**Issue by aherrick** [Azure/azure-functions-host#3634]
Azure Functions V1 .NET 4.5.2

I am using latest Function tooling and nuget 1.0.22

I have a simple HTTP Trigger.

When running through Visual Studio, half the time the Azure Function window will just close. The other half I get messages like this:

![image](https://user-images.githubusercontent.com/586671/47154108-60350f80-d2af-11e8-97f4-4bfd5fab43b8.png)

**Comment by soninaren** [comment]
This is actually by design. 

Following the is develpment workflow when running function apps from visual studio
1. Create a function app
2. Build / compile the function app
3. Run the function app via F5. This should start the CLI instance for you,
4. Anytime you change the code and rebuild, VS forces you to stop debugging and close the CLI window.
5. After you rebuild the project / solution, you press F5 again to start the function app which will launch a new instance of core tools with fresh assemblies

Anytime a dll files are updated / changed the host needs to restart essentially to load the dll files. This is essentially done by re-running `func host start` command.
