### ISSUE TITLE
Azure Function executes twice for same message

### ISSUE THREAD

**Issue by victoriatrimboli** [Azure/azure-functions-host#3880]
We have a function app with multiple functions. All of them working with Service Bus Topic trigger. Sometimes, the functions execute twice for the same message. I have read that this could be caused due to the message lock expiring, but in the example I provide below we can see that the function took less than 1 second to finish with no errors and then started again after a minute:

![image](https://user-images.githubusercontent.com/45757845/49861670-51bd2d00-fdf4-11e8-9773-67b727981de9.png)

Row keys:
d917c04f-c54c-4c4f-8567-aaf3d103dbd3
a0fad1df-080e-4b24-af3e-7220189fb0bb

Time stamps:
2018-12-07T13:21:07.238Z
2018-12-07T13:22:41.161Z

Subscription: SUB BIBBYFS ITS-ITOPS OPS LIVE
Region: North Europe
Resource Group: RG-APP-AuraPortal
Function App: EUA1-LASB-01-FunctionApp
Function Name: UpdateCRMRecord (just for the example above, but same happening with other functions)
Service Plan: EUA1-LASB-01-FunctionAppPlan (consumption)

We are using consumption plan. Would this issue be gone if we move to Service Plan?

Please I need to get your help as soon as possible as this problem is happening in PRODUCTION.

Thanks.

**Comment by victoriatrimboli** [comment]
@paulbatum @mathewc

**Comment by paulbatum** [comment]
Hi @victoriatrimboli, I spent some time looking at our logs but unfortunately I can't get the information I need from them because they do not contain the message IDs. We actually very recently made an improvement in this area, but its not in production yet:
https://github.com/Azure/azure-webjobs-sdk/pull/2021

Right now my recommendation is that you should handle the possibility of duplicates within your code as this is something you generally need to do anyway. However I do want to be clear that the behavior you are getting is suspicious and needs to be investigated.

I would like to take another look at this in January, after the logging improvements I mentioned above are deployed.

**Comment by victoriatrimboli** [comment]
Hi @paulbatum, many thanks for your response.

Do you have an ETA for the 'logging improvements' deployment?

**Comment by arasium** [comment]
Hi,

we encounter the same bug. If we take a look at the azure function monitoring, we can see that the message is processed twice but with an error on the first try: "Precondition failed".

We are using multiple subscription on the same topic (one subscription for one azure function) but with different filters. I will try to create multiple topics instead of multiple subscription.
