### ISSUE TITLE
debugging error when ts-check finds a violation

### ISSUE THREAD

**Issue by johnpapa** [Azure/azure-functions-host#4093]
When I add `// @ts-check` to a javascript file that uses `process.env.xxx` it shows `process` in a red underline because it is unknown. Then after running the debugger a few times (doesn;t always happen right away) I get this message.

![image](https://user-images.githubusercontent.com/1202528/52880325-a69c5d00-312f-11e9-8f96-4f0bc611ee5b.png)

```
 Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.
```

## More details ...

why is there an error? because process is undefined

why is it undefined? because its not recognized by `//@ts-check`

why is it not recognized by ts-check? because we need the node types for it

why did we need the node types? because we added ts-check

why did we add ts-check? to avoid real errors

**Comment by Hazhzeng** [comment]
Hey, @mhoeger @ColbyTresness 

Do you suggest this is a tslint issue in TypeScript extension?
I don't think this is a function host related issue

**Comment by mhoeger** [comment]
Hey @johnpapa ! I was able to repro your issue, but it looks like an issue where VS Code is doing some automatic smarts to integrate with ts-check and failing if the ts-check fails. Do you mind opening the issue on either https://github.com/Microsoft/vscode or https://github.com/Microsoft/vscode-azurefunctions ? 

Closing this issue here since it feels un-actionable on our end, but let me know if I misunderstood!
