### ISSUE TITLE
queueTrigger not working for linux functions? 

### ISSUE THREAD

**Issue by m4recek** [Azure/azure-functions-host#4191]
#### Investigative information

Please provide the following:

- Timestamp: 12. march 2019
- Function App version (1.0 or 2.0): 2.0
- Function App name: dev-dashboard-gs3
- Function name(s) (as appropriate): queueProcessor
- Invocation ID:
- Region: us-central

#### Repro steps

We have recently deployed our functions to Linux version 2.0 just to find out that our queueTriggers are not firing. When I visit function page in Azure Portal it shows following error: 
![image](https://user-images.githubusercontent.com/1221226/54219800-735faa80-44f0-11e9-8547-cdca5a4d76f7.png)

But when I try to install site extentions I see this
![image](https://user-images.githubusercontent.com/1221226/54219977-a73ad000-44f0-11e9-9dec-1e36cff6c850.png)

So queueTriggers are not supported on linux at all? Or how should I get it to work?

#### Expected behavior

Queue triggers should work for linux...

#### Actual behavior

Doesnt work.

#### Known workarounds

none

#### Related information 

used programming language: javascript
used functions.json:
```
{
	"disabled": false,
	"bindings": [{
		"type": "queueTrigger",
		"direction": "in",
		"name": "queueItem",
		"queueName": "general-queue",
		"connection": "solverQueue"
	}]
}
```

**Comment by mhoeger** [comment]
@m4recek - how did you deploy your function app?

**Comment by m4recek** [comment]
Hi, we have used zip deploy, everything was working except queue triggers. We have reverted to window function since then. 

To be fair as far as I know there no mention of queueTriggers on linux in documentation. But it also does not say that it is not supported... which is a bit misleading since linux functions are not in beta.

**Comment by mhoeger** [comment]
I think the difference is in the payload you're deploying. I'm guessing that the zip file you're creating has an extensions.csproj file, but not `bin` or `obj` files that are created on [`func extensions install`](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#register-extensions). 

In Windows, extensions.csproj is found and artifacts are automatically built. In Linux, I think you're running into an issue because the built artifacts are not included in your zip deployed payload.

We're working on a new feature to remove the need to ever build for extensions (https://github.com/Azure/azure-functions-host/issues/3562), that we hope is going to significantly reduce the complexity around registering binding extensions!

Let me know if this isn't the correct or doesn't help you and we can keep digging!
