### ISSUE TITLE
Funсtion 2.0 ServiceBusTrigger is not fired

### ISSUE THREAD

**Issue by denikqwerty** [Azure/azure-functions-host#4242]
#### Investigative information

Please provide the following:

- Timestamp: 2019-03-28 06:58:36.333
- Function App version (1.0 or 2.0): 2.0 (Microsoft.NET.Sdk.Functions-1.0.26)
- Operation ID: 8f7ba2e82c279245ac223772aebdc708
- Region: North Europe

#### Repro steps

Provide the steps required to reproduce the problem:

1. Wait 15-20 minutes
2. Push message to ServiceBus
3. Nothing heppened. Message is still in queue

#### Actual behavior
When the function is published or eny other function was triggered the messages are processed as expected. But is there will be at least 15 minutes break - the function trigger will not be triggered anymore until I will open the function manually throught Azure Portal. I tried to re-create function, to update NuGet packages. I tried to re-sync function triggers throught PowerShell but nothing works.

#### Related information 

Provide any related information 

* Programming language used - C#

**Comment by mhoeger** [comment]
@denikqwerty - can you share your function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? 

Also, is there any chance that you are polling from the same service bus endpoint from multiple functions (ex: if you used the same connection strings for a local instance and one running in Azure)?

**Comment by denikqwerty** [comment]
@mhoeger here is the Id of my function from the log stream Id=eea4c9bb-3c86-47d2-8133-290fecf84ca0

No, it is not possible that i`m polling multiple messages from functions, because there is only one instance of this function app, there cannot be any other instance of this function.

Thank you! :)

**Comment by mhoeger** [comment]
It looks like we're not able to scale properly because the connection string you've provided does not have "Manage" rights for the queue. Is your connection string for the queue or for the namespace? Per [these docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#trigger---configuration), the connection string has to be for the Service Bus namespace. You can also follow these steps to [get the connection string](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-get-started-with-queues#get-the-connection-string) that will have the right permissions!

**Comment by denikqwerty** [comment]
@mhoeger Thank you for the reply.
I replaced the ServiceBus connection string. But there were the same connection string except of ; as the last symbol. 
There is still some latence present, after some time when we push message, there is 2-5 minutes delay until it will be processed. But at least message is processed :)

**Comment by mhoeger** [comment]
@denikqwerty - glad to hear things are better! 

@tohling - the customer was facing scale issues from the following issue in the scale controller: `Connection string does not have Manage claim for queue '<queuename>'. Failed to get queue description to derive queue length metric. Falling back to using first message enqueued time.` The issue ended up being a missing trailing `;`. Is there anything we can do on the scale controller side to handle that better? Or is this a limitation outside of our control?

**Comment by mhoeger** [comment]
@denikqwerty - could you also tell us where you got the connection string that had the trailing `;`?

**Comment by denikqwerty** [comment]
Actually, I don`t remember that, maybe I got this while migrated connection
string from AppService. I had one more parameter in connection string:
entityName. After the migration to AzureFunctions I just removed the
parameter, but not the ;

**Comment by denikqwerty** [comment]
@mhoeger I noticed that some messages are processed with a big delay. For example I know that there was a message added to the queue near 2pm yesterday. But this message was processed only at 6am today, that`s because I have another function which is starting at 6am every day. So I think when the other function was triggered, my servicebus trigger was actually called...
This is not an expected behavior...How can I resolve this? I expect that delay should not be more than 15 minutes

**Comment by mhoeger** [comment]
@denikqwerty - I think that the exact message is misleading and we have an internal work item tracking that. There was a change in the service bus SDK that we depend on and it no longer handles trailing semicolons well, so that is a known issue.

Could you also give UTC times for the issue you saw? I do see at 6:01am on 4/9 UTC that we detected 12 queue messages (this was detected _before_ the timer, which is set to ping at 6:58:30 am on 4/9). Before that, we do not detect any messages in your queue. The last running instance was stopped at 13:29:35 on 4/8, which was triggered because we detected 3 queue messages at 13:06:33 on 4/8. From our end, everything looks to be behaving as we expect (we are polling for new messages every ~ minute). Do you have any other details or repro information that would suggest otherwise? Any data from service bus showing exactly when you queued new messages would be the most helpful!
