### ISSUE TITLE
Failed to execute Queue trigger function for Python CLI

### ISSUE THREAD

**Issue by sunxinhuan** [Azure/azure-functions-host#4244]
**Azure Functions Core Tools** 2.5.539 
**Function Runtime Version**: 2.0.12382.0

Please refer to the snapshot:
![PythonQueueTrigger](https://user-images.githubusercontent.com/39791546/55150193-9ba10780-5186-11e9-9455-15cdd0df0ae1.PNG)

**Repro steps**:
1.Create and activate a virtual environment;
2.Create a local Functions project. Choose "Azure Queue Storage Trigger" when Creating a function;
3.Create stroage and queue, modify the function.json for the storage account;
4.Run the function locally and verify.

**Comment by maiqbal11** [comment]
@sunxinhuan, I am not able to repro this on my local machine. From inside the virtual environment, can you run `pip freeze > requirements.txt` and share the `requirements.txt` generated?

**Comment by maiqbal11** [comment]
Hi @sunxinhuan, this issue is happening because the function was named `queue`. This causes it to conflict with the existing `queue` module within Python because imports are attempted from the `queue` function which does not have the required files. In the future, it would be best to use a name like `QueueTrigger` to avoid this.
