### ISSUE TITLE
Supportability: User Story - Help customer write better code

### ISSUE THREAD

**Issue by cts-shrahman** [Azure/azure-functions-host#4299]
#### What problem would the feature you're requesting solve? Please describe.
Customer code issues are biggest call drivers in support. Here is a sample of the different varieties of issues that come in: 

•	HOW TO configure VS for Functions
•	High CPU consumption (memory-dump)
•	Blob Trigger not firing (batchSize/2)
•	HOW TO Key Vault integration
•	404 not found - creating 0KB file, removed
•	GenerateIfNotExistsCondition() 
•	Download files from remote FTP server, 1 by 1 and processes it
•	Cosmos DB - leaseCollectionPrefix  leaseContainers
•	HOW TO configure VS Code
•	local.settings.json not migrated by default
•	HOW TO configure MSI
•	Cosmos DB remove Provision Throughput 
•	HOW TO access ENV variables from code
•	HOW TO Use SQL Lite, scale out
•	High CPU Consumption (memory-dump)
•	HOW TO configure MFA
•	Debug SB local needs port 9354
•	Random Intermittent errors, no changes
•	Customer code, no check for NULL
•	University project help :-) 
•	Entity Framework best practise
•	HOW TO Functions on ASE
•	4 x IoT Hub (How To)
•	Increase partition count (here and here)
•	Trigger not registered in ScaleController (SYNC)

#### Describe the solution you'd like
1. Need to build a repository [find top 4/5 areas to focus on first; e.g. dependency injection] and need to point engineers to where to look first.
2. Also docs on how to use a feature - if you are landing a big feature set, it has to be accompanied by docs and samples.
3. Developer support:

i.	Roslyn Compiler detecting outside of the Best Practices and things like RunOnStartUp for TimerTriggers
ii.	JavaScript\TypeScript Lint doing the same thing for JavaScript Async\Promises\Context.done. 
iii.	Detect Trigger\Bindings and link to Best Practices.
iv.	If they deploy without Run From Package then output a warning.

**Comment by ankitkumarr** [comment]
@cts-shrahman, we usually always accompany any big feature set with docs and samples. Was there any particular feature that you think we are missing documentation on? Additionally, https://serverlesslibrary.net/ is a community built library for samples and serverless applications. That might be of interest to you.

A few of those:
- [Configure VS code for functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code)
- [Keyvault integration](https://azure.microsoft.com/en-us/blog/simplifying-security-for-serverless-and-web-apps-with-azure-functions-and-app-service/)

For things like-
>HOW TO access ENV variables from code
HOW TO Use SQL Lite
HOW TO configure MSI
University project help
Customer code, no check for NULL
Random Intermittent errors, no changes

These sound unrelated to Functions. I am not sure what we can do to help here.

> i.	Roslyn Compiler detecting outside of the Best Practices and things like RunOnStartUp for TimerTriggers

For compiler warnings, we do have a few for things like missing `AzureWebJobsStorage` setting in function.json. If you think we need to add additional warnings, please open an issue [here](https://github.com/Azure/azure-functions-vs-build-sdk).

For,
> ii.	JavaScript\TypeScript Lint doing the same thing for JavaScript Async\Promises\Context.done.

We do have a detector for async issues. I am not sure if we want to force users to install specific linters config in order to achieve this.

> iii. Detect Trigger\Bindings and link to Best Practices.

Can you please elaborate on what you mean by this? When would we detect triggers, and what kind of best practices you had in mind?

> iv.	If they deploy without Run From Package then output a warning.

Our tools, like Functions core-tools, usually do run from packages by default. If users specifically chose to not use the default, I don't think a warning is necessary. And for deployment outside of our tools, we do not have control to output a warning. Did you have a specific flow in mind?
