### ISSUE TITLE
Best practice for using Azure Functions runtime version

### ISSUE THREAD

**Issue by PingPongSet** [Azure/azure-functions-host#4346]
What is the best practice for using runtime version given that the runtime introduced breaking changes, and using specific version will cause issue given that runtime will be removed regularly.
https://github.com/Azure/app-service-announcements-discussions/issues/90

Please let me explain below:

**Scenario 1:**
When below is used,

FUNCTIONS_EXTENSION_VERSION =~2

Our code broke with the latest runtime. Because ~2 means it uses the latest version.
https://github.com/Azure/azure-functions-host/issues/4203

**Scenario 2:**
However, when below is used,

FUNCTIONS_EXTENSION_VERSION = specific version

Our code brok again with the latest runtime. Because the specified runtime is removed by Azure Functions, and the latest runtime with breaking changes is used instead, 
https://github.com/Azure/app-service-announcements-discussions/issues/90

Again, what is the better way to reduce the error?

**Comment by fabiocav** [comment]
The best and recommended practice is to use the latest. It is a rare occurrence, but unfortunately, a regression was introduced with a new release impacting your app. 

If you want to perform validation on new versions, the recommendation is to:
- Subscribe to new release notifications at https://github.com/Azure/app-service-announcements/issues
- Pin yourself to the current release you've validated against
- As a new version is introduced, update a test environment to adopt that new version (or have a test environment that auto updates, using `~2`). If you have a test environment set with auto-updates and automated tests, this makes the process significantly simpler. 
- Once validated, update the production environment to that new version
- If you find an issue, reporting allows us to ensure we don't remove the version that works

We always maintain the newly deployed version and the previous release, and, aside from hotfixes and small ad-hoc deployments, the release cadence is ~2 weeks. Anything that has been flagged as a version that needs to be kept due to issues intruduced by a release (forcing customers to pin) is also kept.

**Comment by PingPongSet** [comment]
Hi @fabiocav ,


In terms of time frame, how a latest runtime works when it is publicly downloadable and it is rolled out on Azure Functions? For example, how advance is the runtime available before it is rolled out to Azure fucntions?

How long will an old runtime be kept for on Azure Functions after latest runtime rollout? Based on what factors are an old runtime decided to be deteled?

**Comment by fabiocav** [comment]
Can you clarify what you mean by publicly downloadable? If you're referring to the Core Tools, a release of that doesn't happen until the Azure deployment completes. This is required because artifacts tested and built with a newer version of the runtime are not guaranteed to work with previous versions (e.g. customers may start using new features introduced and not available in previous versions).

An older version of the runtime is usually kept on Azure for two release cycles.
