### ISSUE TITLE
Allow v2 function to run with unbounded timeout in dedicated

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-host#4528]
Today in v2 we enforce a 30 min run duration if functionTimeout is empty.  However, in dedicated you should be able to define "unbounded".  There should be some value that people can but in `FunctionTimeout` that would cause the runtime to run unbounded in run duration.

/cc @mathewc

**Comment by mathewc** [comment]
The functionTimeout config value is a TimeSpan, so in host.json string form, we'd want a value that is a valid TimeSpan string, rather than using something like "-1" and treating that specially during parsing, which would introduce a difference between Azure Functions and core SDK.

TimeSpan.MaxValue in string form is "10675199.02:48:05.4775807". Can't users just specify some large value rather than needing "unbounded"?

**Comment by jeffhollan** [comment]
That's what we tell them today but feels a bit strange to document that a run duration is unbounded and then in order to get it put in 10000000 as the functionTimeout.  I don't recall how Newtonsoft does this but what if an explicit `null` is unbounded.  Whereas empty could still default to 30 min

**Comment by mathewc** [comment]
Changes to the way we interpret null/0 would be breaking, right? Since the value maps to a TimeSpan, it feels a little strange to allow invalid timespan values like "0" or "-1" - we'd also have to update our json schema to allow for that.

However strange, "-1" would work - when we see this, we interpret it in the Azure Functions layer and skip leave the options [FunctionTimeout](https://github.com/Azure/azure-functions-host/blob/8f830855365b0c0080a2847513633db94dbe8a98/src/WebJobs.Script/Config/ScriptJobHostOptions.cs#L117) null, which tells the underlying SDK there is no timeout.
