### ISSUE TITLE
ILogger<T> not injected at function level but is Injected at Class level.

### ISSUE THREAD

**Issue by zippy1981** [Azure/azure-functions-host#4538]
This might be as intended, but its annoying.

I am using DI in Azure functions, non static classes.  I can inject a Generic Logger at the class level e.g.

```C#
        public Functions(IDbConnection cn, ILogger<Functions> logger)
        {
            this.cn = cn;
            this.logger = logger;
        }
```

However, if I do it at the log level:

```
   [FunctionName("GetThings")]
        public async Task<IActionResult> GetThings(
            [HttpTrigger(AuthorizationLevel.Function, "get", Route = null)]
            HttpRequest req, ILogger<Functions> log)
        {
```

I get the following:

```
[2019-06-05 16:07:26] The following 1 functions are in error:
[2019-06-05 16:07:26] GetPrincipals: Microsoft.Azure.WebJobs.Host: Error indexing method 'GetStuff'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'log' to type ILogger`1. Make sure the parameter Type is supported by the
binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
```

#### Investigative information

Please provide the following:

I ran locally. will try to stand up a function service later.

- Timestamp:
- Function App version (1.0 or 2.0): 2
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by brettsam** [comment]
This is by-design. We don't use DI to inject parameters into your function method, so we create that logger for you with a specific category and pass it in. Since we use a specific category, we don't create a generic logger for you.

We do have plans to support something like `[FromServices]` that will allow you to inject directly from DI into your function. It's the one item left unchecked here: https://github.com/Azure/azure-functions-host/issues/3736. @fabiocav -- did we have a separate issue tracking this that I can link to? If not, I'll create one.
