### ISSUE TITLE
Functions fail with "Number of initialized language workers exceeds:2"

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#4559]
For dedicated Java function apps, we see some functions failing with the following error:

> ErrorSystem.InvalidOperationException : Number of initialized language workers exceeded:2 exceeded maxProcessCount: 1   

This is due to a race condition that starts 2 java.exe processes when we only expect one.

Workaround:
Since it is a race condition, sometimes restarting the app gets it in a healthy state.

If this does not work, you can try removing `FUNCTIONS_WORKER_RUNTIME` until the fix is rolled out

cc: @pragnagopa

**Comment by pragnagopa** [comment]
[RpcInitializationService](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/RpcInitializationService.cs) is an IHostedService which runs in the background.

[InitializeChannelsAsync](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/RpcInitializationService.cs#L62) takes longer specifically for Java ~30secs and does not complete before [FunctionDispatcher ](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/FunctionRegistration/FunctionDispatcher.cs#L143) gets initialized.

This leads to spinning up another Java.exe. 
**Note: This does not effect consumption apps as they go through placeholders giving enough time for process initialization before specialization kicks in**

@brettsam / @fabiocav  - Any ideas on alternative approaches for initializing Rpc server and channels before scripthost initialization instead of using HostedService?

**Comment by pragnagopa** [comment]
Related pattern discussed here: [running-async-tasks-on-app-startup-in-asp-net-core-part-1](https://andrewlock.net/running-async-tasks-on-app-startup-in-asp-net-core-part-1/)

**Comment by fabiocav** [comment]
Currently in PR, will remain in 51
