### ISSUE TITLE
Azure Storage queue trigger with custom name resolver not firing 

### ISSUE THREAD

**Issue by MauriRojas** [Azure/azure-functions-host#4625]
We have a custom queue name resolver that using the value `%valueForQueueNameResolver%` from the `queueName` parameter of the `QueueTrigger` applies a logic that searches for the queue name in a another class and adds a suffix, resulting on the actual queue name.
When the project is built, the `queueName` property of the function.json file has the original value that is passed in the queue trigger attribute.
After being deployed to Azure in a consumption plan, the function reads messages from the queue up to thirty minutes after the deployment. Then it doesn't wake up until a time trigger, HTTP trigger or another function with the actual name of the queue in the function.json is triggered in the same Function App.
We think this issue is related to [3493](https://github.com/Azure/azure-functions-host/issues/3493)

```
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.27",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "queueTrigger",
      "connection": "QueuesConnectionString",
      "queueName": "%valueForQueueNameResolver%",
      "name": "command"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/MyFunction.dll",
  "entryPoint": "MyFunction.Function"
}
```

#### Repro steps

Example: 
1. Create a Function App project with the following class:
```
namespace MyFunctionApp
{
    public class CustomQueueNameResolver : INameResolver
    {
        public string Resolve(string name)
        {
            // Custom logic ...
            return anotherName; 
        }
    }
}
```
2. In the startup class of the Function App register the name resolver:
```
public virtual void Configure(IWebJobsBuilder builder)
{
    ServiceDescriptor serviceDescription = null;

    serviceDescription = builder.Services.FirstOrDefault(x => x.ServiceType.Name.Equals(typeof(INameResolver).Name));

    if (serviceDescription != null)
    {
        builder.Services.Remove(serviceDescription);
     }

     builder.Services.AddSingleton<INameResolver, CustomQueueNameResolver >();
}
```
3.Use the name resolver in the function, note that the value we pass to the queue trigger attribute is not an app setting:
```
[FunctionName("MyFunction")]
        public static async Task MyFunction(
            [QueueTrigger("%ThisIsNotAnAppSetting%", Connection = "MyConnectionQueuesConnectionString")] string message)
        {
            // Function logic
        }
```
3. Deploy the function and add messages to the queue after thirty minutes.

#### Expected behavior

Whenever there are messages in the queue, the function should wake up and process them.

#### Actual behavior

After thirty minutes of the deployment, the function stops reading messages from the queue.

#### Known workarounds

Adding a time triggered function in the same Function App to wake up the function like the following is the most practical (but not ideal) workaround:
```
[FunctionName("KeepAlive")]
        public static async Task KeepAlive(
            [TimerTrigger("0 */5 * * * *", RunOnStartup = true)] TimerInfo timerInfo)
        {
        }
```
A HTTP or queue triggered function without the custom name resolver will work too.

#### Related information 

Provide any related information 

* Programming language used: C#
* Service plan: Consumption

**Comment by kashimiz** [comment]
Hi @MauriRojas, thanks for reporting this issue. In order to investigate, we'll need more information, specifically: 


- Timestamp:
- Function App version (1.0 or 2.0):
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

If you don't want to share your Function App name or Functions names on GitHub, please be sure to provide your Invocation ID, Timestamp, and Region - we can use this to look up your Function App/Function. Provide an invocation id per Function. See the [wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately) for more details.

**Comment by MauriRojas** [comment]
@kashimiz Thank you for your answer. We will collect that information and upload it the next days.

**Comment by fabiocav** [comment]
While this works with the WebJobs SDK and in Azure Functions with App Service Plans (dedicated), this is not a supported scenario in Azure Functions using the consumption model, as the infrastructure will not be using your name resolver in order to get the name of the queue it needs to monitor. Please see this section of the documentation (we'll update this with a list of services you can override if/when that happens): https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#overriding-host-services
