### ISSUE TITLE
Requesting ILogger<T> in Startup throws InvalidOperationException

### ISSUE THREAD

**Issue by benmollet** [Azure/azure-functions-host#4685]
I am trying to use the logger in my dependency injection Startup class but it's throwing this exception because the providers have been registered but their dependencies have not been registered.

I am trying to get the logger because I was debugging an exception that was occurring in my code but since the exceptions caused by custom implementations don't bubble out to Application Insights it makes it very very difficult to debug.

System.InvalidOperationException: 'Unable to resolve service for type 'Microsoft.Azure.WebJobs.Script.IFileLoggingStatusManager' while attempting to activate 'Microsoft.Azure.WebJobs.Script.Diagnostics.HostFileLoggerProvider'.'

```csharp
    public class Startup : FunctionsStartup
    {
        public Startup()
        {
        }

        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.BuildServiceProvider().GetRequiredService<ILogger<Startup>>();
        }
    }
```

**Comment by brettsam** [comment]
You can't request an `ILogger<>` during service initialization -- some of the loggers haven't had all of their dependencies registered at this point. You should be requesting an `ILogger<>` in the constructor of the class that needs it -- where is that?

What do you mean by "exceptions caused by custom implementations don't bubble out to Application Insights"? Any exceptions should be getting logged to App Insights. 

Maybe if you could share a code snippet, that would help.
