### ISSUE TITLE
Offline Hoststate

### ISSUE THREAD

**Issue by FilipVanRaemdonck** [Azure/azure-functions-host#4702]
Hi, 

I have a function written in C# (netcoreapp2.2, azurefunction v2, latest sdk from function sdk's). this function is running for a few months already and we have been deploying to it with a gitlab pipeline using the zipdeploy functionality. However, the when we deployed yesterday (22/07/2019 at about 03:32 PM) the function received a 'config update': File change of type 'Changed' detected for 'D:\home\site\wwwroot\app_offline.htm'. After this config update the function started loading a lot of stuff (looks like it was restarting) but it never got started correctly, instead was in a sort of idle state and kept on logging the message: 'Ping Status: { "hostState": "Offline" }'. A stop and start of the function made it work again. However, I'm really wondering what caused this problem as this is not a likely behaviour and I really want to avoid this error on our production environment. It looks a bit similar to this issue: https://github.com/Azure/azure-functions-host/issues/4289. Also: the always on functionality is enabled on the function.

Do you know what caused this behaviour of the function or how I can avoid this behaviour in the future.

Thanks, 

Filip

**Comment by fabiocav** [comment]
@FilipVanRaemdonck can you please share the application information requested in the issue template? That will help us take a closer look at exactly what happened to your app.

**Comment by FilipVanRaemdonck** [comment]
- Timestamp: 22/07/2019 03:27 until 03:33 PM (and offline until the morning after)
- Function App version (1.0 or 2.0): 2.0
- Function App name: buhler-dev-we-ingestion-pipeline
- Function name(s) (as appropriate): all stopped
- Invocation ID: /
- Region: West Europe



#### Repro steps

Provide the steps required to reproduce the problem:



#### Expected behavior

Provide a description of the expected behavior.



#### Actual behavior

Provide a description of the actual behavior observed.



#### Known workarounds

Provide a description of any known workarounds.



#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by soninaren** [comment]
@FilipVanRaemdonck, We would have to further understand the deployment set up you inorder to understand what is going on. To provide a little information on `app_offline.htm` file. I am aware of two methods that would cause the host_offline.htm file to be added. 
1. When you are deploying an app via Visual studio using msdeploy.
2. When installing extension via portal.

In both cases the file should be removed afterwards.  In case of portal there was a potential issue where the file was not removed after the extension installation because the browser was closed. The portal experience is now in the process of being retired. 

Going to close this issue, Please open a new issue in case you are still looking for answers and we can follow up. Please reference this issue in your new issues.
