### ISSUE TITLE
Thread.CurrentPrincipal not being populated

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-functions-host#4860]
Trying to enable Google auth for functions v2 using a provider SDK but Thread.CurrentPrincipal is never populated.

#### Investigative information

Please provide the following:

- Timestamp: 2019-08-29T12:08:03.051
- Function App version (1.0 or 2.0): 2.0
- Function App name: -
- Function name(s) (as appropriate): ExternalProviderLogin
- Invocation ID: 4e4d7f61-7bc1-4a3d-9c2b-3c02fb5f561e
- Region: West Europe

#### Repro steps

1) Configure the functions project to enable authentication, configure Google credentials (key + secret) and disable tokens store (although if tokens store is enabled will get same results). Configure WEBSITE_AUTH_HIDE_DEPRECATED_SID parameter to "true". Enable "Action to take when request is not authenticated" option with "Allow Anonymous Requests (no action)" value.

2) Authenticate on mobile using Google's SDK and then send the token to FUNCTIONS_HOST/.auth/google which returns azure's authentication token.

3) Perform a call to a different function which requieres authentication, including azure's authentication token from the previous step in X-ZUMO-AUTH header.

4) Retrieve user information through Thread.CurrentPrincipal in the function's body.

#### Expected behavior

Thread.CurrentPrincipal is populated with the authenticated user information

#### Actual behavior

Thread.CurrentPrincipal is always empty

#### Related information 

* Programming language used: C#

The function's definition is the following:

```
[FunctionName("ExternalProviderLogin")]
public static async Task<IActionResult> ExternalProviderLogin([HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = null)] HttpRequestMessage req, ILogger log)
```

**Comment by brettsam** [comment]
@ConnorMcMahon -- are you the expert here?

**Comment by pizerg** [comment]
If it helps with the issue, I've been doing further testing and it appears that if I inject `ClaimsPrincipal principal` as a parameter in the function, then I'm able to retrieve user data from it (but it still fails to get the information from Thread.CurrentPrincipal)

**Comment by ConnorMcMahon** [comment]
@pizerg, this is intentional. .NET Core made the decision to [not assign `Thread.CurrentPrincipal`](https://davidpine.net/blog/principal-architecture-changes/). Since Functions V2 is .NET Core, we decided not to set it ourselves as that goes against the design principals of the framework.

Instead, we did the work that you have already discovered that allows you to populate the `ClaimsPrincipal` object as a parameter. You can read more about[ this feature here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook#working-with-client-identities).

Hope that clarifies matters.

**Comment by pizerg** [comment]
Thanks for the clarification, it's now working again!
