### ISSUE TITLE
Add CORS middleware for Linux consumption

### ISSUE THREAD

**Issue by balag0** [Azure/azure-functions-host#4889]
Config will be injected as part of specialization.

**Comment by fabiocav** [comment]
To add more detail:
 - To leverage the existing experience exposed by App Service, the configuration injected as part of specialization needs to be augmented to include the CORS information for the site (managed through the portal). This information should be used to configure CORS in the runtime during spectialization
 - Ideally, we'll use the Easy Auth/CORS middleware once that is published by the team, but since this work is time sensitive, we may need to use the ASP.NET CORS middleware, exposing the same surface supported by the App Service CORS middleware, which should be used when ready.
 - Registration should happen using the JobHost middleware pipeline.

**Comment by fabiocav** [comment]
Moving this to sprint 60

/cc @dariagrigoriu
