### ISSUE TITLE
Introduce SameSiteMode.Unspecified equivalent in 3.x

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#4890]
It looks like `samesite=lax` is not present by default in ASP.NET Core 3.0. See test `RawScriptResultTests.AddsHttpCookie()` -- it has been removed. Need to evaluate.

**Comment by brettsam** [comment]
This changed from 2.2 -> 3.0 -> 3.1. The value here went from `samesite=lax` to blank, to `samesite=none`. 
- Link to test in `dev` branch: https://github.com/Azure/azure-functions-host/blob/dev/test/WebJobs.Script.Tests/Binding/ActionResults/RawScriptResultTests.cs#L83.
- 3.0 announcement change: https://github.com/aspnet/AspNetCore/issues/8212

**Comment by mhoeger** [comment]
The linked test actually represents an invalid case :) there will never be CookieOptions where "SameSite" is not set, because it is always set with a default value of "None" (code [here](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Workers/Rpc/MessageExtensions/RpcMessageExtensionUtilities.cs#L80))

What we need to introduce with V3 is the ability to set a value of "ExplicitNone", where this adds a value of "SameSite=None", and change the current v3 to treat SameSite=None as unspecified

**Comment by mhoeger** [comment]
Linking to this test item: https://github.com/Azure/azure-functions-host/issues/5384

**Comment by fabiocav** [comment]
Closing as done.
