### ISSUE TITLE
Activity.Current.RootId used as OperationId in Azure Application Insights, instead of context.InvocationId

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-functions-host#5014]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#, but might be applicable to all.

#### Question
The [documentation](https://github.com/Azure/azure-functions-host/wiki/Retrieving-information-about-the-currently-running-function) lists `context.InvocationId` as "invocation ID, uniquely identifying the current invocation".

However, `Activity.Current.RootId` is used for assigning the `OperationId` in Azure Application Insights. Is this intentional?

If we were to get the correlation id for a given run, what should we use? `Activity.Current.RootId` seems like the best fit, but then it makes me wonder what `context.InvocationId` is for.

UPDATE: I've noticed that `context.InvocationId` is used in text logs and part of the Application Insights trace, but not as OperationId.

Am I missing something?

#### Repro
Function:
```csharp
#r "Newtonsoft.Json"

using System.Net;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Newtonsoft.Json;

public static async Task<IActionResult> Run(HttpRequest req, ILogger log, ExecutionContext context)
{
    log.LogInformation($"Invocation Id: {context.InvocationId}");
    log.LogInformation($"Activity Id: {Activity.Current.Id}");
    log.LogInformation($"Activity Root Id: {Activity.Current.RootId}");

    return (ActionResult)new OkObjectResult($"Repro");
}
```

Logs:
```cli
2019-10-03T10:10:58.465 [Information] Executing 'Functions.HttpTrigger1' (Reason='This function was programmatically called via the host APIs.', Id=5e4717e8-8856-46f5-99de-134fdc712872)
2019-10-03T10:10:58.474 [Information] Invocation Id: 5e4717e8-8856-46f5-99de-134fdc712872
2019-10-03T10:10:58.474 [Information] Activity Id: |6730e6929130b84da405adc7ede9d6a1.da6658ac_
2019-10-03T10:10:58.474 [Information] Activity Root Id: 6730e6929130b84da405adc7ede9d6a1
2019-10-03T10:10:58.475 [Information] Executed 'Functions.HttpTrigger1' (Succeeded, Id=5e4717e8-8856-46f5-99de-134fdc712872)
```

Application Insights:
![image](https://user-images.githubusercontent.com/4345663/66119022-13d60300-e5d8-11e9-8fdc-9e06a0464512.png)

**Comment by pvmraghunandan** [comment]
@tomkerkhove  which runtime are you using? Because in v2 Activity.Current is empty/null.

**Comment by tomkerkhove** [comment]
I've seen it not being empty locally with latest Azure Function Tools in Visual Studio:
```cli

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.7.1585 Commit hash: 9a2b7239b937148e3b76e6f7999798629a82134a)
Function Runtime Version: 2.0.12641.0
```

It worked in Azure before but now that is no longer the case while I did a "New > Azure Function" before the report and just now with different outcome 🤔

**Comment by pvmraghunandan** [comment]
@tomkerkhove strange.AFAIK, it's not supported as of now & Invocation Id should match operation Id.

**Comment by tomkerkhove** [comment]
I'll try it again next week to verify!

Tom Kerkhove
Azure Architect at Codit, Microsoft Azure MVP

________________________________

**Comment by mhoeger** [comment]
Hey @tomkerkhove ! Any update on this issue? Or do you have a function app name/time period for the screenshots you posted?

**Comment by tomkerkhove** [comment]
I've used the above repro to run it in a new Azure Function with following scenarios:
- **Windows Function in Azure** (uses `Activity`)
- **Windows Function in VS** (Uses `context.InvocationId`)
- **Linux Function in Azure** (uses `Activity`)

## Windows
**Subscription:** `0f9d7fea-99e8-4768-8672-06a28514f77e`
**Resource Group:** `function-repro`
**Name:** `function-repro-windows`

Function setup:
![image](https://user-images.githubusercontent.com/4345663/67145428-dfbe3b80-f281-11e9-9724-e9052eeeda9d.png)

Outcome:
![image](https://user-images.githubusercontent.com/4345663/67145413-b30a2400-f281-11e9-96d7-c38bd28d3c51.png)

## Visual Studio

I'm on a different machine today with `Azure Functions and Web Jobs Tools   16.3.282.33872` where Activity is indeed null.

## Linux
**Subscription:** `0f9d7fea-99e8-4768-8672-06a28514f77e`
**Resource Group:** `function-linux-repro-2`
**Name:** `function-linux-repro-2`
**Package:** Deployed via CLI, same code as VS section above which failed

Function setup:
![image](https://user-images.githubusercontent.com/4345663/67145726-fcf40980-f283-11e9-8af3-dbb3be2729c4.png)

Outcome:
![image](https://user-images.githubusercontent.com/4345663/67145733-1d23c880-f284-11e9-8cf9-e25971c53d98.png)

**Comment by tomkerkhove** [comment]
Sorry for the delay btw!

**Comment by tomkerkhove** [comment]
Any update on this?

**Comment by mhoeger** [comment]
@tomkerkhove - so sorry, missed your update on this! thanks for checking in, looking into it now

**Comment by BoricuaEnLaLuna** [comment]
Hi, I am also noticing that the value coming up for OperationId is different to the value coming up in ExecutionContext.InvocationId. As was mentioned above the value being used for operation id seems to be matching the value of Activity.Current.RootId instead.

So I was also trying to understand what is the purpose/meaning of invocationid vs operationid? Is this difference intentional?

I am using Azure Functions v2 (with .net core 2.2) and I am running my Azure Functions locally in my VS2019 hooked up to my AppInsights instrumentation key.

Additional note: In this other thread below @yantang-msft provided as an answer to use System.Diagnostics.Activity.Current.RootId as the source of the operation id, but that does not clarify the purpose of invocation id vs operation id.
https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/444 

Looking forward to clarification on this.
Thanks!

**Comment by tomkerkhove** [comment]
Bump @mhoeger

**Comment by Hurtyto** [comment]
For example on Web Jobs, the operation Id is used when you want to process an item and have end-to-end id. In case where the message (for example with Service Bus) needs to be reprocessed, then you have new invocation of your original operation. In that case the operation Id will persist (because you are retrying), but the invocation will be new.
Hope this helps.

**Comment by tomkerkhove** [comment]
Bumping.

**Comment by mhoeger** [comment]
@brettsam or @lmolkova - mind helping weigh in on this question?

**Comment by brettsam** [comment]
InvocationId is the Azure Functions identifier of a unique function invocation (note that in App Insights, we put this into a custom property). It is currently unrelated to Application Insights and is used by the Azure Functions team to identify individual invocations in our logs.

We originally also used InvocationId as the identifier for operations in Application Insights. However, that got more complicated as [distributed tracing](https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation) started being implemented across different services. App Insights has a lot of logic around setting up the current Activity with the correct Id and ParentId based on distributed tracing -- and propagating this to downstream calls. This made using the Functions InvocationId here almost impossible if we wanted to retain all of that behavior. So we've moved to having all tracing in App Insights be based on the Activity rather than on our custom InvocationId. To put it more simply -- Application Insights now "owns" all of the OperationIds it sets, and we merely append our internal InvocationId onto the telemetry via a custom property.

The comment by @Hurtyto (https://github.com/Azure/azure-functions-host/issues/5014#issuecomment-591987779) shows one example where this is useful. You can see a full logical Service Bus operation in Application Insights, and you can also use the InvocationId to identify the individual invocations as Functions sees them.

Also, if you have a repro where `Activity.Current` is still null, please let me know -- there've been a handful of fixes around that lately and I'd like to investigate if you can still repro it. Those issues revolved around the custom AssemblyLoadContext we use when executing your function. Our host still had all the relevant Activity, but we may not have been sending it to the function invocation as expected.

**Comment by tomkerkhove** [comment]
I don't have a recent repo as it's been a long time but this is ok, thanks for the update!

Maybe it would be good to have this elaborated more in the docs @mhoeger?

**Comment by swervinerv** [comment]
@brettsam I have been running into issues where the `Activity.Current` is null for one of our Azure Functions projects.  I have also tried creating a new project to replicate the issue but in this new project `Activity.Current` is not null and appears to be working as expected. To try and keep things simple I have the exact test function code below in both projects but am getting different results:

```[FunctionName("ActivityTest")]
public IActionResult Testing(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "test/activity")] HttpRequest req,
    ExecutionContext executionContext,
    ILogger log)
{
    var activity = Activity.Current;

    log.LogInformation("C# HTTP trigger function processed a request.");

    return new OkObjectResult(new
    {
        activity,
        executionContext
    });
}
```

The result from the main project where it is not working looks something like the following:
```
{
    "activity": null,
    "executionContext": {
        "invocationId": "415def8f-7ce7-453c-ae79-270aa64d1199",
        "functionName": "ActivityTest",
        "functionDirectory": "D:\\home\\site\\wwwroot\\ActivityTest",
        "functionAppDirectory": "D:\\home\\site\\wwwroot"
    }
}
```

The result from the project where we tried to replicate the issue but is working looks like:
```
{
    "activity": {
        "operationName": "Microsoft.AspNetCore.Hosting.HttpRequestIn",
        "parent": null,
        "duration": "00:00:00",
        "startTimeUtc": "2020-07-17T21:10:15.4772251Z",
        "id": "00-146517b46ac7694b809dbdd805ab0d0a-38ad40068bbaec4e-00",
        "parentId": null,
        "rootId": "146517b46ac7694b809dbdd805ab0d0a",
        "tags": [
            {
                "key": "ClientIp",
                "value": "24.21.11.161"
            },
            {
                "key": "LogLevel",
                "value": "Information"
            },
            {
                "key": "Category",
                "value": "Host.Results"
            },
            {
                "key": "Succeeded",
                "value": "True"
            },
            {
                "key": "FunctionExecutionTimeMs",
                "value": "8.8668"
            },
            {
                "key": "TriggerReason",
                "value": "This function was programmatically called via the host APIs."
            },
            {
                "key": "Name",
                "value": "Function1"
            },
            {
                "key": "InvocationId",
                "value": "c6bfce46-0a39-45d6-bbbc-392e5cc9091e"
            },
            {
                "key": "FullName",
                "value": "Function1"
            }
        ],
        "baggage": [],
        "traceStateString": null,
        "spanId": {},
        "traceId": {},
        "recorded": false,
        "activityTraceFlags": 0,
        "parentSpanId": {},
        "idFormat": 2
    },
    "executionContext": {
        "invocationId": "c6bfce46-0a39-45d6-bbbc-392e5cc9091e",
        "functionName": "ActivityTest",
        "functionDirectory": "D:\\home\\site\\wwwroot\\ActivityTest",
        "functionAppDirectory": "D:\\home\\site\\wwwroot"
    }
}
```

I have verified:
- Both projects are using the 3.0.13901.0 runtime
- Both projects are using the latest 3.0.9 version of the Microsoft.NET.Sdk.Functions SDK
- Both projects are using the same Application Insights instance/instrumentation key

The only difference between the projects is that our main one uses Dependency Injection and a `Startup.cs` file, but we do not have any custom logging implemented and do not register App Insights manually since [this article says that should not be done](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#logging-services).

Any insights into what else to look into would be much appreciated.

**Comment by brettsam** [comment]
+@fabiocav 
 
Could you also include your csproj file for the repro project? I'm assuming there's some kind of assembly unification that's happening incorrectly.

**Comment by swervinerv** [comment]
Here is the project file for the non-working project. Let know if there is any other information I can provide.
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.ServiceBus" Version="4.1.3" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.1.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.9" />
    <PackageReference Include="RestSharp" Version="106.11.4" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by tomkerkhove** [comment]
Did you see this locally or in Azure? I saw differences based on OS (see above)

**Comment by swervinerv** [comment]
@tomkerkhove I am seeing these results in Azure and both projects are hosted on Windows. When running locally on Windows 10 I am getting a `null` result for `Activity.Current` in both of my projects.

**Comment by ByMitta** [comment]
I encountered the same issue where Activity.Current is null. When I downgrade the `System.Diagnostics.DiagnosticSource` package from 4.7.1 to 4.6.0. It wasn't null and it worked for me. I did this explicitly in my project file.

```
<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="4.6.0">
      <NoWarn>NU1605</NoWarn>
 </PackageReference>
```

The `<NoWarn>` is there because other packages depend on the newer version in other projects

Can somebody else try this and see if it fixes it for them?

**Comment by johannesoenema** [comment]
We have the same problem as described by @ByMitta and I made a simple repro of the issue. We use `EFCore.BulkExtensions` which has a dependency on version `4.7.1` of `System.Diagnostics.DiagnosticSource` and because of that `Activity.Current`  isn't working anymore. See repro here: [https://github.com/johannesoenema/ActivityIssue](https://github.com/johannesoenema/ActivityIssue)

Also very weird, `Activity.Current` is null according to the code, but in the debug window it isn't null...
![image](https://user-images.githubusercontent.com/12686691/88380041-1c383e00-cda4-11ea-9539-2633a03e3532.png)

**Comment by jctlp** [comment]
In #5014([comment](https://github.com/Azure/azure-functions-host/issues/5014#issuecomment-654863513))> @brettsam states "Application Insights now "owns" all of the OperationIds it sets, and we merely append our internal InvocationId onto the telemetry via a custom property."

How can I access that custom property in AI? I would like to use the InvocationId generated during invocation of our v2 Queue and Table triggered functions to "join" our logs, thus allowing us to evaluate each call individually.

**Comment by ThejaChoudary** [comment]
@brettsam can you please look into this further.

**Comment by brettsam** [comment]
@fabiocav -- do you remember why we removed `System.Diagnostics.DiagnosticSource` from unification? If someone moves forward, suddenly accessing `Activity.Current` seems to not work. Looks like that was done here -- https://github.com/Azure/azure-functions-host/pull/4941.

**Comment by johannesoenema** [comment]
@brettsam and @fabiocav Any update on this issue?

**Comment by cveld** [comment]
It would make sense to be able to return the OperationId to the caller so that one can easily correlate the logging with the original request. How would I do that since it is not accessible anymore?

**Comment by markusfoss** [comment]
We are running a series of (windows) dotnet core based functions in our infrastructure. 

We just tried to upgrade to newer versions of:

Microsoft.ApplicationInsights (from 2.14.0 to 2.15.0)
Azure.Storage.Blobs (from 12.6.0 to 12.8.0)
Microsoft.Azure.Cosmos (from 3.15.0 to 3.16.0)
Microsoft.Azure.Functions.Extensions (from 1.0.0 to 1.1.0)
Microsoft.Azure.ServiceBus (from 4.1.4 to 5.1.1)
Microsoft.Azure.WebJobs.Extensions (from 3.0.6 to 4.0.1)
Microsoft.Azure.WebJobs.Extensions.ServiceBus (from 4.1.2 to 4.2.1)
Microsoft.Azure.WebJobs.Extensions.Storage (from 4.0.3 to 4.0.4)
Microsoft.Extensions.Configuration.AzureAppConfiguration (from 3.02 to 4.1.0)
Microsoft.Graph (from 3.13.0 to 3.24.0)
Microsoft.Identity.Client (from 4.18.0 to 4.26.0)

Using all the "from" versions in combination with Microsoft.NET.Sdk.Functions v3.0.9 works across all our functions/services both locally and in all our environment

When using the "to" versions: this fails in at least ONE function locally using Microsoft.NET.Sdk.Functions v3.0.11

In addition: We are experiencing the **excact** same behavoir as @johannesoenema : In one function Activity.Current is set, in another its null - and at the same time Activity.Current has values when debugging the function in Visual Studio.

We also tried to add 
```
<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="4.6.0">
        <NoWarn>NU1605</NoWarn>
    </PackageReference>
```
without any luck in the function that fails with Activity.Current being null. (Not that weird, since we upgraded Microsoft.ApplicationInsights to v2.15.0 instead of v2.16.0. v2.15.0 has a dependency on DiagnosticSource v4.6.0, while v2.16.0 has a dependency on DiagnosticSource v4.7.0.

Runtime info:
Azure Functions Core Tools
Core Tools Version:       3.0.3284 Commit hash: 98bc25e668274edd175a1647fe5a9bc4ffb6887d
Function Runtime Version: 3.0.15371.0

Does anyone know of any workaround this issue - it blocks us from updating our packages & we have spent a lot of time trying to figure out what is causing this behaviour?

**Comment by markusfoss** [comment]
Can add some more details to my previous comment: This particular package upgrade causes Activity.Current = null in the function host runtime:

```

<PackageReference Include="Microsoft.Graph" Version="3.13.0" /> --> <PackageReference Include="Microsoft.Graph" Version="3.24.0" />
<PackageReference Include="Microsoft.Graph.Auth" Version="1.0.0-preview.4" /> --> <PackageReference Include="Microsoft.Graph.Auth" Version="1.0.0-preview.6" />
<PackageReference Include="Microsoft.Identity.Client" Version="4.18.0" /> --> <PackageReference Include="Microsoft.Identity.Client" Version="4.26.0" />

```

**Comment by markusfoss** [comment]
@brettsam | @fabiocav : Should I move these to another more suitable ticket?

**Comment by v-anvari** [comment]
cc: @fabiocav / @brettsam / @anthonychu

**Comment by fabiocav** [comment]
@markusfoss If you don't mind, given the context and different problems covered in this issue, it would be helpful to have a new issue tracking the specific problems we're seeing with this and, if there are no objections/further clarification needed, close this one.

**Comment by sidkri** [comment]
Closing this issue as the original question has been answered by @brettsam and the issue around Activity.Current is being tracked in #7278
