### ISSUE TITLE
Strings localization resx

### ISSUE THREAD

**Issue by raissetto** [Azure/azure-functions-host#5018]
I have developed an Italian / English application.
I have created 2 resx files to manage the texts, in the local everything works perfectly, on azure, instead only the texts of the default resx file are displayed (in Italian in this case)

Thanks to @andreatosato who created a sample project to better understand the issue.

```csharp
[FunctionName("ResourceFunc")]
public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequestMessage req, TraceWriter log)
{
    log.Info("C# HTTP trigger function processed a request.");
    log.Info(Thread.CurrentThread.CurrentCulture.DisplayName);
    log.Info(Thread.CurrentThread.CurrentUICulture.DisplayName);
    System.Resources.ResourceManager rm = new System.Resources.ResourceManager("ResourceApp.Prova", System.Reflection.Assembly.GetExecutingAssembly());
    log.Info(rm.GetString("Nome"));
    return  req.CreateResponse(HttpStatusCode.OK, rm.GetString("Nome"));
}
```
I Have 2 file resources, Prova and Prova.en 
the key "Name" have value "Italiano" in the file "Prova" and "Inglese" in the file "Prova.en"
this is the result:
local:
```
Thread.CurrentThread.CurrentCulture.DisplayName: English (United States)
Thread.CurrentThread.CurrentUICulture.DisplayName: English (United States)
rm.GetString("Nome"): Inglese
```
Azure:
```
Thread.CurrentThread.CurrentCulture.DisplayName: English (United States)
Thread.CurrentThread.CurrentUICulture.DisplayName: English (United States)
rm.GetString("Nome"): Italiano
```

file:
https://github.com/andreatosato/FunctionApp

**Comment by bragma** [comment]
Same problem here. I have an azure function using Razor for email templating and I'd like to put localization resource files in the same razor class library containing the views. The problem is that the resulting directory structure is:

...
bin/FuncName.dll
...
bin/RazorClassLibrary.dll
bin/RazorClassLibrary.Views.dll
bin/en/RazorClassLibrary.resources.dll
bin/es/RazorClassLibrary.resources.dll
bin/fr/RazorClassLibrary.resources.dll
etc...

I've not been able to use resource dlls using any of the built in localization facilities. Neither HtmlLocalizer nor StringLocalizer work, and got mad trying to work around this using their respective factories by specifying the assembly and namespace names.

**Comment by fabiocav** [comment]
@bragma and @sandeepnmenon can you share the version of Azure Functions you're using? I'm assuming this is V2 and V1, respectively, is that correct?

This issue is tracking the problem in for V1, which will not be addressed (please refer to some of the suggested workarounds above), so I'm closing. For V2, could you please open a separate issue with details?

**Comment by bragma** [comment]
> @bragma and @sandeepnmenon can you share the version of Azure Functions you're using? I'm assuming this is V2 and V1, respectively, is that correct?
> 
> This issue is tracking the problem in for V1, which will not be addressed (please refer to some of the suggested workarounds above), so I'm closing. For V2, could you please open a separate issue with details?

You are right, I am using V2. Sorry for the confusion.

**Comment by sandeepnmenon** [comment]
We were using V1. But now have migrated to V2.
Is there any new issue open for V2?

**Comment by mo3bius** [comment]
Any update? I'm working on an azure function for Alexa (ttps://blogs.msdn.microsoft.com/appconsult/2018/11/02/build-your-first-alexa-skill-with-alexa-net-and-azure-functions-the-basics/). I need to localize the response based on request. I tried with resx but they doesn't work. I also used the hack written in this thread and in local host it work but than when I published my azure function on Azure and I try to execute, appear an error that say me that not found any dll in path. How can I localize my AF? Thanks
