### ISSUE TITLE
Intermittent 404 errors on HTTP triggered function

### ISSUE THREAD

**Issue by davidjnet** [Azure/azure-functions-host#5247]
An HTTP-triggered function intermittently returns 404 status code.

#### Investigative information

- Timestamp: Started happening around 2019-11-06, then more frequently from 2019-11-09T01:41Z until present. A recent example from a few hours ago is around 2019-11-14T03:29Z.
- Function App version (1.0 or 2.0): 2.0.12858.0
- Function App name: alienta-diag-2
- Function name(s) (as appropriate): StatusPage

#### Repro steps

This HTTP function is polled every minute by a monitoring tool. Intermittently, starting 5 days ago, it returns a 404 some of the time. It recovers and goes back to working normally after a couple of minutes.

#### Expected behavior

The function should execute and generate an HTML page.

#### Actual behavior

Intermittently, HTTP 404. The problem persists for a minute or so and goes away. Sometimes the problem happens again a few minutes later. Sometimes it goes for hours without a problem.

#### Known workarounds

None known.

We have tried stopping, starting, restarting, redeploying, and there does not seem to be a pattern to it.

#### Related information 

C#, .NET Core, consumption plan in Australia East.

This may be the same problem @jacobgunnarsson mentioned in a comment https://github.com/Azure/azure-functions-host/issues/5149#issuecomment-552799279 (the original issue was apparently a different problem, and was closed).

The AzureWebJobsHostLogs201911 table usually shows the StatusPage function getting invoked every minute, which is expected because it is being polled by a monitoring tool. When the 404s happen, there is a gap in the logs.

As well as the StatusPage function which runs every minute, there is a SiteCheck function in the same Function App which fans out to ~80 invocations every minute.

**Comment by balag0** [comment]
The linked comment from https://github.com/Azure/azure-functions-host/issues/5149 is specific to Linux function apps. Given this is a windows function app this is likely a different issue.

**Comment by Noituri** [comment]
We are having the same issue again. It seemed to be fixed here https://github.com/Azure/azure-functions-host/issues/5149 but the problem came back. We are using 2.0.12835.0 (~2) version.

**Comment by OShevnin-Quest** [comment]
We experience the similar issue as well. 
version 1.x, consumption plan. C#, different regions.
It started happening more or less constantly about Nov, 11th 
Opened support case 119112722002265

**Comment by OShevnin-Quest** [comment]
Some interesting findings are observed while investigating the issue as a part of support case. 
@Noituri @davidjnet do you have (or ever had) any slots in your app with the issue?  Trying to find any commonalities.

**Comment by davidjnet** [comment]
@OShevnin-Quest We're not using slots in our app

**Comment by Noituri** [comment]
@OShevnin-Quest Same as @davidjnet. We don't use slots.

**Comment by fabiocav** [comment]
@OShevnin-Quest since you're experiencing this with 1.0, can you please open an issue with the details requested on the template so we can take a closer look?

@davidjnet Are you still experiencing the problem? Could you give us another recent timeframe for investigation?

@Noituri can you please also share your app information? (the information on the template doesn't require you to disclose the app name)

**Comment by hughesjon** [comment]
@fabiocav I'm a colleague of @davidjnet - he's currently on a well-earned sabbatical, so I hope he's not going to see this!

This problem was causing a lot of false alarms for our on-call team as a result of the monitoring failing, not the thing that was supposed to be being monitored.  As a result, we refactored to not use Functions any more and moved to a normal App Service.
