### ISSUE TITLE
Set HostId returns a warning. Why?

### ISSUE THREAD

**Issue by alallo** [Azure/azure-functions-host#5267]
I have got a timer triggered Azure Function deployed to two different regions and I have to set the HostId manually in order to get the cross-region singleton behaviour and have only one timer trigger running at the time. But I now get the following warning?

> Host id explicitly set in configuration. This is not a recommended configuration and may lead to unexpected behaviour.

What are the unexpected behaviour that I may encounter? 

Thanks

**Comment by fabiocav** [comment]
The main issue this could cause happens if you're sharing the storage account between different instances of that function app (including local development scenarios). The host ID is used as a scoping property that uniquely identifies that application (in things like distributed locks, storage operations, application insights logs, etc.). If those applications share those resources, you may run into issues where they'll be doing things like competing for locks across deployments/local.

**Comment by alallo** [comment]
Hi Fabio and thanks for your quick response. Are you saying that as long as the storage account used by the function is not used locally or in any other environment it should be safe to manually define an host id for that function?
