### ISSUE TITLE
Do not load private binaries from the root bin folder of the function app when bundle is configured for non-dotnet app

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#5347]
Assemblies in the bin folder of the function app and the assemblies files in the extension bundle could conflict if we try to load different versions of the same assemblies in both locations.

**Comment by gzuber** [comment]
Closing this.

This ended up not being an issue after @soninaren was able to repro the original bug. Turns out the issue only occurs when the runtime probes bin folders for individual functions (not the bin folder at the app level where extension dlls are). Non-dotnet languages don't have these bin folders.

Relevant code here: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Description/DotNet/FunctionAssemblyLoadContext.cs#L429
