### ISSUE TITLE
Azure Functions Timer Trigger Unexpected Fire

### ISSUE THREAD

**Issue by kingkino** [Azure/azure-functions-host#5348]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
I made Azure Functions with TimerTrigger that run unexpectedly.
For example, it fires when the application settings are saved, restarted, stop and start.
runonstartup is false.

Is there any cause?

[Runtime Version]
{"id":<BatchName>,"state":"Running","version":"2.0.12888.0","versionDetails":"2.0.12888.0 Commit hash: 107be00e9a1d752c4a4ee2c3f0d03580d09d2c40","processUptime":342307384}

[functions.json]
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.29",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "timerTrigger",
      "schedule": "%SyncMerchantData_CRON%",
      "useMonitor": true,
      "runOnStartup": false,
      "name": "myTimer"
    }
  ],
  "disabled": "",
  "scriptFile": "",
  "entryPoint": ""
}

**Comment by mhoeger** [comment]
@kingkino - can you share your function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly) to help us investigate? 

One thing that may be happening too is (depending on the frequency of your timer), there may be missed invocations while your function app is down and restarting. By default, missed executions (due to an app restarting, for example) will execute after the scheduled time, as soon as the function app is available again. You can read more on "schedule monitoring" and configure the behavior through the [`UseMonitor` property](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=csharp#configuration).

**Comment by mhoeger** [comment]
@kingkino - I'd also recommend checking the [diagnose and solve probems](https://docs.microsoft.com/en-us/azure/azure-functions/functions-diagnostics) pane in the Portal. There's a timer trigger-specific diagnostics page that's helpful!

**Comment by kingkino** [comment]
Thank you for your reply and infromation.
These are a  information that you want.(Indirectory Infromation) 

subscription : 27790b...3d7f7
functions : Batch-SyncExt...Prod
functionname : SyncMer....TimerFunction

Is this enough?

**Comment by kingkino** [comment]
Thank you for your reply and infromation.
These are a information that you want.(Indirectory Infromation)

subscription : 2779...d7f7
functions : Bat...Ext...Prod
functionname : Sy...Mer....tion

Is this enough?

**Comment by kingkino** [comment]
I found the following webjob article:

https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger

I will try setting monitor property to false as you suggested.

Thank you very much. Issue is closed.

**Comment by kingkino** [comment]
I understand the contents of UseMonitor.
I understand that when Timer's 「IsPastDue」 is True, the scheduled time of 「myTimer.ScheduleStatus.Next」 has passed and it will be executed.
I solved that Implemented not to process when 「IsPastDue」 is True.
Thank you for the information.

**Comment by mhoeger** [comment]
Good to hear, thanks for the update!
