### ISSUE TITLE
Difference between Premium Functions and Functions running on an App Service plan with auto scaling

### ISSUE THREAD

**Issue by FrankGagnon** [Azure/azure-functions-host#5354]
Hi,

I asked a question in the Azure Docs repo (https://github.com/MicrosoftDocs/azure-docs/issues/42232). They answered part of it but advised to ask the unanswered part here.

What is the difference between Premium Functions and Functions running on an App Service plan with auto scaling? From what I gather, the Premium Functions have the same functionnal advantages as the App Service plan, mainly VNet connectivity and always on. 

Now, there is a difference in the dynamic scaling/pricing features but it's kind of a blur.

How are they different exactly?

Thanks,
Frank

**Comment by paulbatum** [comment]
Autoscaling on a dedicated app service plan is going to be based on whatever rules you manually configure and works on the timescale of minutes. The scaling for the elastic premium plan is based on monitoring your event sources, and happens within seconds. The fact that the monitoring is based on the event source is important because not every scalability problem is the result of high cpu load. 

To help drive home the distinction regarding the timescale differences, you could try doing a HTTP load test comparison between the two plans. If you drive load that is well beyond the initial size of your dedicated plan with autoscale rules set, you should see significantly degraded response time and possibly a large number of 5XX class errors while you wait for the system to catch up. You should dramatically better results on the elastic premium plan.

The elastic plan also has a higher maximum instance count, because our infrastructure is able to run elastic plan apps across multiple scale units if required.

Also if you have a number of apps assigned to the same elastic plan, the system will allocate those apps to your VMs based on the load requirements of each individual app. This is in contrast to the default behavior of an app service plan where **every app** assigned to that plan will run on every VM.

Closing this one as answered!
