### ISSUE TITLE
Background trigger sync should only run on home stamp

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#5436]
As per @suwatch we should only allow background trigger sync to run on the home stamp.

**Comment by mathewc** [comment]
Investigation into cases showed that non-home stamp wasn't the issue. Instead we had cases where the site temporarily had incorrect site content. We're following up on that, but for now the fix we'll make is to avoid doing a background sync with empty functions. In such situations when a site has been updated by the user to have empty site content, the direct sync performed at deployment time will correctly update the sync cache to empty. So avoiding empty background syncs won't cause problems.

Background sync triggers has been flushing out platform issues with site content, due to its frequent nature. We're following up those issues, but in the meantime we can be defensive here.
