### ISSUE TITLE
Using appsettings and not loosing host.json values

### ISSUE THREAD

**Issue by clouddna-au** [Azure/azure-functions-host#5466]
#### Is your question related to a specific version? If so, please specify:
Latest host for V3 of functions

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#
#### Question
I have implemented the changes as discussed in this issue #4464 from @martinfletcher but it doesn't seem to work and my host.json is still being overwritten with my extension settings lost.

There seems to be no ImplementationInstance when reading the `IConfiguration` from the services.
```C#
public override void Configure(IFunctionsHostBuilder builder)
 {
            ConfigureServices(builder.Services);
}
public void ConfigureServices(IServiceCollection services)
{
    var providers = new List<IConfigurationProvider>();
    foreach (var descriptor in services.Where(descriptor => descriptor.ServiceType == typeof(IConfiguration)).ToList())

    {
        var existingConfiguration = descriptor.ImplementationInstance as IConfigurationRoot;
        if (existingConfiguration is null)
        {
            continue;
        }
        providers.AddRange(existingConfiguration.Providers);
        services.Remove(descriptor);
    }

    var executioncontextoptions = services.BuildServiceProvider()
        .GetService<IOptions<ExecutionContextOptions>>().Value;
    var currentDirectory = executioncontextoptions.AppDirectory;

    var config = new ConfigurationBuilder()
        .SetBasePath(currentDirectory)
        .AddJsonFile("appSettings.json", optional: false, reloadOnChange: true)
        .AddEnvironmentVariables();

    providers.AddRange(config.Build().Providers);

    services.AddSingleton<IConfiguration>(new ConfigurationRoot(providers));
}
```

**Comment by clouddna-au** [comment]
Any update?

**Comment by martinfletcher** [comment]
You should also check for an instance factory if the instance is null! The original solution I provided was not supposed to be a copy and paste silver bullet!

**Comment by tekking** [comment]
For anyone else with this problem: We ran into a similar issue (overriding our host.json settings by injecting a custom IConfiguration) after moving to v3. We used to add the implementationinstance when running v2 functions, but it seems they moved away from that to an implementationfactory with v3 functions. 

The easiest way we found to add to IConfiguration without overriding host.json was by requesting IConfiguration from a serviceProvider in startup as follows (example from our function startup): 

```
            var serviceProvider = builder.Services.BuildServiceProvider();
            var existingConfig = serviceProvider.GetService<IConfiguration>();

            var rootPath = Directory.GetCurrentDirectory();
            var config = new ConfigurationBuilder()
                .AddConfiguration(existingConfig)
                .SetBasePath(rootPath)
                .AddJsonFile("local.settings.json", true)
                .AddAzureKeyVault($"https://{keyvaultName}.vault.azure.net/")
                .Build();

            builder.Services.Replace(new ServiceDescriptor(typeof(IConfiguration), config));
```

**Comment by alrod** [comment]
cc: @brettsam, is it known issue for V3?

**Comment by brettsam** [comment]
There wasn't a known issue here, but it looks like .NET changed how IConfiguration is registered in v3 (from instance to factory as @tekking pointed out):

https://github.com/dotnet/extensions/pull/1361/commits/a8a3cc16247471077566fb70e951ff444240e3ac#diff-9e9cba0278df6f1227eb36f7be70598b

This is a tricky way to handle configuration, and we've never liked it because it's susceptible to changes outside of our control like this. If it works for you, then that's great (which is why we haven't blocked it), but we have a feature in PR now that will allow you to add configuration sources to the builder at the correct point in the host setup. I'm hoping to get it in within the next few weeks.

For reference:
- https://github.com/Azure/azure-webjobs-sdk/pull/2407
- https://github.com/Azure/azure-functions-dotnet-extensions/pull/33
- https://github.com/Azure/azure-functions-host/pull/5484

Because there's a workaround and it's outside of our control, I'm going to close this.
