### ISSUE TITLE
Azure Function fires multiple times for the same Blob storage event

### ISSUE THREAD

**Issue by riccardotrevisan** [Azure/azure-functions-host#5503]
My Python Azure Function configuration file (`function.json`) defines a Blob storage trigger.

When the Azure Function wakes up (i.e. the server shown in Live Metrics becomes online after some sleeping time) it processes all the existing blobs regardless which ones have already generated trigger events.

I noticed that the `azure-webjobs-hosts/blobreceipts` folder is populated with `sandboxhost637nnn` folders. A new _sandboxhost_ folder is created **every Azure Function wake up event**. This way the function forgets previously processed blobs (no old receipts found). In the past (Dec ’19), I remember that a unique _webjobs-hosts_ folder containing all receipts persisted across invocations.

**Comment by pragnagopa** [comment]
cc @divyagandhii @anirudhgarg 

We have recently identified and fixed an issue around unique name functions host uses to keep track for blobreceipts. PR#https://github.com/Azure/azure-functions-host/pull/5507

The fix is deployed to production. Please let us know if this is still an ongoing issue. If yes, please share function app name or invocationId, function app region and appx time you saw the issue.

**Comment by riccardotrevisan** [comment]
Dear @pragnagopa, 

Apparently, the issue is solved. Webjobs host names now reflect the function app name and persist in time.

Thank you all!
