### ISSUE TITLE
System.Data.SqlClient is not supported on this platform.

### ISSUE THREAD

**Issue by adamvan101** [Azure/azure-functions-host#5535]
Our Dev/QA function runtimes were updated by Azure to 2.0.12961.0 sometime this week and have since been failing to load the System.Data.SqlClient package with error `System.Data.SqlClient is not supported on this platform.` Note that we made no changes, this happened without our knowledge. 

Our Production functions have not yet been upgraded and are still running normally **but we fear a ticking timebomb**. Is version pinning not supported this time around?

`Runtime version loaded from Application Settings: 2.0.12888.0
Warning
Unsupported Runtime Version
Your custom runtime version is not supported. As a result 2.0.12961.0 runtime is being used.`

**Comment by mhoeger** [comment]
@adamvan101 - A temporary mitigation is to pin to `2.0.12950`.
Can you also check two that your function app was built with the following two configurations?
`"Microsoft.NET.Sdk.Functions" Version="1.0.31"`
and
`<TargetFramework>netcoreapp2.2</TargetFramework>` (as opposed to netstandard).

We're still confirming that this is the root cause of the issue, but we strongly believe that changing these and re-building will fix the missing native dependency

**Comment by adamvan101** [comment]
@mhoeger thank you, switching to Netcore instead of Standard did the trick! And to confirm, I am on v1.0.31 of the SDK.

I will pin to the runtime version you mentioned if the problem rearises. Thanks!
