### ISSUE TITLE
HttpTrigger returns 401 when using AddSignalR() in Startup

### ISSUE THREAD

**Issue by domenichelfenstein** [Azure/azure-functions-host#5814]
In my Azure functions app, I want to use a Redis backplane to send notifications to another app that is connected to the same Redis backplane and offers a SignalR endpoint for our clients.

I connected to the Redis SignalR backplane with this code:
```csharp
using Microsoft.Azure.Functions.Extensions.DependencyInjection;

[assembly: FunctionsStartup(typeof(Startup))]

namespace SampleFunctions
{
    using Microsoft.Extensions.DependencyInjection;

    public class Startup : FunctionsStartup
    {
        public override void Configure(
            IFunctionsHostBuilder builder)
        {
            builder.Services
                .AddSignalR()
                .AddRedis("<connectionString>");
        }
    }
}
```

Unfortunately, after adding `AddSignalR()`, all my HttpTrigger functions stopped working correctly and instead only returned a 401 HTTP status code.

So far it looks like this line is causing the problem:
https://github.com/dotnet/aspnetcore/blob/ec8304ae85d5a94cf3cd5efc5f89b986bc4eafd2/src/SignalR/server/SignalR/src/SignalRDependencyInjectionExtensions.cs#L48

because within `AddConnections()` `AddAuthorization()` (https://github.com/dotnet/aspnetcore/blob/7669cf0d036cc0cb3b481aba49253cd35d85c633/src/SignalR/common/Http.Connections/src/ConnectionsDependencyInjectionExtensions.cs#L25) gets called.

Does anyone have an idea how to connect to a Redis backplane without adding authorization, which interferes with all the HttpTriggers?

\* This issue has its origin here: https://github.com/Azure/azure-functions-signalrservice-extension/issues/104

**Comment by kashimiz** [comment]
Hi @domenichelfenstein, my apologies for the delay in response. This is happening because the `.AddSignalR()` service registration call overrides services provided by the host, [which is currently unsupported](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#overriding-host-services) - in this case, the authorization policy provider and the policy within it.

.AddSignalR() bundles a bunch of service registrations. To avoid this situation, you'll need to register only the services necessary for SignalR, omitting the registrations that override services used by the host.

@anthonychu (for SignalR) and @fabiocav - this is the second time I've seen this situation reported by a customer; it seems like a common use case. 

Closing as answered, but there may be room for improvement here.
