### ISSUE TITLE
Custom handlers - Forward path from original request

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-host#5921]
When proxying HTTP requests, it doesn't appear the worker is able to access the route from the original request.

For instance, given this host.json and function.json to create a function that triggers on every route:

```json
{
  "version": "2.0",
  "httpWorker": {
    "description": {
      "defaultExecutablePath": "node",
      "defaultWorkerPath": "server.js"
    }
  },
  "extensions": {
    "http": {
      "routePrefix": ""
    }
  }
}
```

```json
{
  "bindings": [
    {
      "type": "httpTrigger",
      "authLevel": "anonymous",
      "direction": "in",
      "name": "req",
      "route": "{*restofpath}"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ]
}
```

It doesn't look like the worker is able to access the original route (`restofpath`). Perhaps this can be made available as an HTTP header?

**Comment by btrepp** [comment]
Also it would be nice if the folder name wasn't so coupled to what is called in the custom handler.

Eg It seems we must have a url that matches the folder name, this makes sense but means the handler must match and can't do any routing of it's own.

Even as a simpler one, maybe the folder name can just function as the route prefix?. So that
say api/MyCustomHandler/a/b/c gets called to the custom hanlder with the path MyCustomHandler/a/b/c

**Comment by pragnagopa** [comment]
@anthonychu - Sent a PR where the request will be sent to the Url path in the HttpTrigger. For example, if routePrefix is specified in host.json:
```
"extensions": {
    "http": {
      "routePrefix": "foo"
    }
```
and http binding specifies a route:

```
 "route": "testPath"
```
Host will forward request to localhost:<port>/foo/testPath

I think this is more useful than adding Url path as a header. Let me know what you think.

**Comment by pragnagopa** [comment]
cc @yojagad
