### ISSUE TITLE
Provide git credentials to Azure Function

### ISSUE THREAD

**Issue by Melifarosky** [Azure/azure-functions-host#6038]
Hello

I have an Azure Function that is being used for git caching.
The function is deployed to the Azure via Azure DevOps defined definition.
How I could provide credentials for private repositories?

Currently, I am using `https://_pat@url` syntax to provide secret token and I don't l like this approach due to many insecure things.

Is there a better option to handle it?

Thanks

**Comment by Jusas** [comment]
@Melifarosky How about using a Key Vault to store the PAT? What I mean is:
- Saving the PAT to a Key Vault as Secret
- Enable Managed Identity for the Function App
- Add that identity to the Key Vault's Access Policies so that it can read the secrets
- Add an AppSetting to the Function App's Configuration, with the value being a Key Vault Secret reference, like `@Microsoft.KeyVault(SecretUri=https://my-keyvault.vault.azure.net/secrets/MySecretName/)`
- After this the setting should be available for you in the IConfiguration instance with the AppSetting name, just inject the IConfiguration into your function and there you have it.

This way you'll have your PAT sitting in a safe place.

**Comment by Melifarosky** [comment]
Well, I have figured out several ways how to solve my problem:
1) Using `git -c http.extraheader="AUTHORIZATION: Basic {pat}" {command}` for each git command
2) Using `git config --global http.extraheader="AUTHORIZATION: Basic {pat}` which creates `~/.gitconfig` file and uses it but `~/` is Storage Account's file storage which is not a good way also because pat is stored unencrypted.
