### ISSUE TITLE
RenewBlobLease - Is it normal for this to be constantly triggered on storage account? (Costs)

### ISSUE THREAD

**Issue by nothingto** [Azure/azure-functions-host#6188]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#
#### Question
I am currently looking at Insights on the storage account, and it seems like there is a constant stream of 5 RenewLeaseBlobs transactions that are happening every single minute that is neverending. Over the course of 5 minutes, there are 25 RenewLeaseBlobs that are happening. I'm worried this is going to increase any unwanted storage costs. 

Is this normal? Also, even when the function receives no traffic, there are often bursts of around 5-100 storage account transactions that happen within a span of 5 minutes. What are the causes of these transactions? Coming from AWS, these were pretty abstracted from me and I never had to worry about storage costs somehow piling up so this is new to me. Are storage costs something I'd have to worry about using functions?

**Comment by ankitkumarr** [comment]
I think this is normal for certain "Bindings" or "Triggers". @brettsam or @paulbatum, do either of you know?

**Comment by paulbatum** [comment]
Yes when the functions host is running, it will interact with storage as part of its normal operation, even when there are no functions being triggered. The lease related operations you are seeing are normal (or sound normal based on your description).

As @ankitkumarr mentioned, some trigger types rely more heavily on storage - for example timers also relies on lease operations. Eventhub triggered function perform storage transaction because the checkpoints are in storage.

However when running on the consumption plan, you should find that when there are no function executions to run, the application goes completely idle after 20 minutes or so and then you should see not see those lease related transactions. 

When you're talking about mostly idle function apps that are activated just occasionally, your monthly storage cost should be well under $1 USD (most of my idle function apps have a monthly storage cost of ~ $0.01 USD).

Closing this one as answered, but I can re-activate if you have followup questions.
