### ISSUE TITLE
Official guidance on AddHttpClient

### ISSUE THREAD

**Issue by APIWT** [Azure/azure-functions-host#6325]
#### Is your question related to a specific version? If so, please specify:
No

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
My team has grown very fond of the `AddHttpClient` extension that can be used to created typed HTTP clients. That being said, after doing some digging it appears that the clients are created using the transient lifetime, meaning that a new one is created for every activation of the service.

The documentation says to try to stick with static clients: https://docs.microsoft.com/en-us/azure/azure-functions/manage-connections#static-clients

This seems like it adds yet another thing that we need to be extra careful about when trying to re-use code across ASP.NET Core APIs and Azure Functions applications.

So, simply put: Are we not supposed to be using AddHttpClient in Azure Functions applications? Or are we simply supposed to ensure that any service that activates our typed HTTP client is registered as a singleton?

For example, is this okay:
```
services.AddHttpClient<IMyService, MyService);
services.AddSingleton<IMyConsumingService, MyConsumingService>();

...

class MyConsumingService : IMyConsumingService
{
  private readonly IMyService _myService;

  public MyConsumingService(IMyService myservice)
  {
    this._myService = myService;
  }

  public async Task DoSomethingAsync()
  {
    await this._myService.MakeRequestAsync();
  }
}

class MyService : IMyService
{
  private readonly HttpClient _httpClient;

  public MyService(HttpClient httpClient)
  {
    this._httpClient = httpClient;
  }

  public async Task MakeRequestAsync()
  {
    await this._httpClient.GetAsync("https://example.com/hello");
  }
}
```

I would argue that even if this is okay, this still limits the structure of our code quite a bit. For example, what happens if we want to use `IMyService` directly inside a function handler?

**Comment by mhoeger** [comment]
@anthonychu - are you the right person to help address a doc enhancement for c#?

**Comment by anthonychu** [comment]
@fabiocav what’s the guidance here?

**Comment by mhoeger** [comment]
Chatted with @fabiocav about this -

The point of the guidance is to avoid holding more connections than necessary, reuse client instances rather than creating new ones with each function invocation, so yes it's ok to use `AddHttpClient` as long as this principal holds true (like you said @APIWT).

@fabiocav - I see in the [ASP.NET docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#httpclient-and-lifetime-management) this:
 > Keeping a single HttpClient instance alive for a long duration is a common pattern used before the inception of IHttpClientFactory. This pattern becomes unnecessary after migrating to IHttpClientFactory.

This is just from my lack of knowledge... but it seems like you don't have to worry about a singleton instance as long as it comes from IHttpClientFactory? Maybe we need to update our "managing connections" docs to have a sample using DI.

Also - we were going to point you to this sample using [dependency injection](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#use-injected-dependencies)... but it's actually following the wrong pattern (should be using IHttpClientFactory instead of HttpClient)

**Comment by madushans** [comment]
I think the latest guidance is this one 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1

- `HttpClient` 
  - a collection of config for requests (headers, base address .etc.) and can be transient. Needs a `HttpMessageHandler` to make an actual request with the config.
- `HttpMessageHandler` 
  - Handles and reuses connections, applying config from the HttpClient that initiated the request. Longer lifecycle, usually not bound to your application, rather a time period. I think is so you don't get stuck with outdated DNS .etc.
- `IHttpClientFactory`
  - Creates `HttpClient` objects to apply config to them?

**Comment by v-anvari** [comment]
Hi @APIWT , Apologies for the delayed response. Were you able find a solution? do let us know if a follow up is required
