### ISSUE TITLE
[Custom Handlers] [Go]SocketException when accessing key vault from the handler

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-host#6346]
https://github.com/Azure-Samples/functions-custom-handlers/issues/10

**Comment by fabiocav** [comment]
Scoping this to validation only in sprint 86

**Comment by yojagad** [comment]
I dug deeper at this. If Zach was working off of the example from here https://github.com/Azure-Samples/azure-sdk-for-go-samples/tree/master/keyvault/examples to try and access secrets, it didn't work for me. But it wouldn't fail either and `GetSecret()` would just get stuck. Since he was using it in the context of `init()`, initialization would have ended up getting stuck and not completed.

To work around this, I had to additionally make AZURE_CLIENT_SECRET available as an environment variable for keyvault access to work and once I did that, it worked in the context of custom handler without any issues.
