### ISSUE TITLE
Invalid CRON expression (5 instead of 6) still runs sometimes

### ISSUE THREAD

**Issue by liranc** [Azure/azure-functions-host#6389]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app => `Platform features` => `Diagnose and solve problems` and the relevant dashboards before opening your issue.

#### Investigative information

Please provide the following:

- Timestamp: 2020-07-21T05:51:33.2606227Z
- Function App version: ~3 (SDK: 3.0.9)
- Function App name: N/A
- Function name: Orchestrator
- Invocation ID: 56071486-cb2c-464c-955e-fb8046b8da1d
- Region: West Europe

#### Repro steps

The function is supposed to be triggered once every 5 minutes (using the expression: `"*/5 * * * *"`), but after a few triggers, the timer stops. There are no apparent errors in the logs.

The function uses a consumption plan.
Deployment is done using an ARM template and ZipDeploy.

#### Expected behavior

Function should be triggered once every 5 minutes.

#### Actual behavior

After being triggered a few times, the timer stops triggering the function (after a while, it might start firing it again ... until it stops yet again after a while).
The execution count is missing from the metrics and my own application logs are missing as well.

#### Known workarounds

None.

#### Related information 

* Programming language used: C#
* Bindings used: Timer, Blob.

```csharp
[FunctionName("Orchestrator")]
public async Task Orchestrator(
  [TimerTrigger("*/5 * * * *")] TimerInfo timer,
  [Blob("pathToBlob", FileAccess.ReadWrite)] ICloudBlob blobA,
  [Blob("pathToOtherBlob", FileAccess.ReadWrite)] ICloudBlob blobB,
  ILogger logger)
{
}
```

Timer trigger executions analysis:
```
Is runOnStartup enabled?	
False     

TimeZone	
(UTC) Coordinated Universal Time     

Cron Expression	
*/5 * * * *
View Schedule Description
Lastest 3 execution(s)	
 2020-07-21T05:46:33.1615952+00:00
 2020-07-21T05:41:33.1430663+00:00
 2020-07-21T05:36:33.1238187+00:00
 2020-07-21T05:31:33.1154761+00:00
 2020-07-21T05:26:33.1108173+00:00
 2020-07-21T05:21:33.0876447+00:00
 2020-07-21T05:16:33.0617804+00:00
 2020-07-21T05:11:33.0535979+00:00
 2020-07-21T05:06:33.0396693+00:00
```

Invocation count metric
![image](https://user-images.githubusercontent.com/1437075/88035242-8786d380-cb4a-11ea-8871-aa0c7b0fe8f3.png)

**Comment by mhoeger** [comment]
Hi @liranc , one of your issues i think is that you have log sampling enabled (this is enabled by default to keep app insights from being overbilled). you should try disabling log sampling, which can cause missing logs especially in timer trigger scenarios: https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring?tabs=cmd#configure-sampling

I also see that you have a few "past due" executions. Function executions will be past due when the current function invocation is later than scheduled. Two examples of when this would happen: a function app restart might cause an invocation to be missed or a previous execution might run longer than your execution interval (ex: I see many executions that are going > 5 seconds), causing the next execution to be delayed. Note that only one execution of a timer-triggered function can happen at a time. So if you have executions every 5 seconds but each execution lasts 10 seconds, you will have executions that are skipped due to the previous execution being in progress.

I see that you've changed your app around a bit - could you give us the UTC timeframe of that screenshot? then we can validate if the executions were actually happening and they just weren't showing up in monitoring

**Comment by liranc** [comment]
Hi @mhoeger , thanks for your quick reply!
I've disabled log sampling as you've suggested but the issue remains.
Below is that "new" count metric (the new function was deployed a couple of minutes after 8AM UTC, when the first "spikes" start).
There are missing activations between 8:40AM - 9:13AM and again from 9:40AM until 10:43AM.
The timestamp of the last activation seen here is: 2020-07-23T10:45:00.0935377Z

![image](https://user-images.githubusercontent.com/1437075/88278634-60b3d300-cceb-11ea-819d-3d1c7833707d.png)

Updated diagnostic output:
![image](https://user-images.githubusercontent.com/1437075/88278693-7e813800-cceb-11ea-92f1-56ce8270b14d.png)

**Comment by mhoeger** [comment]
@liranc - looking at your logs, it looks like our scaler isn't doing what it's supposed to be doing (keeping an instance alive) because: "'*/5 * * * *' is an invalid crontab expression. It must contain 6 components of a schedule in the sequence of seconds, minutes, hours, days, months, and days of week."

I'm not sure why your function sometimes runs though! We'll look into that. In the meantime, can you try changing your cron expression to '*/5 * * * * *'?

**Comment by liranc** [comment]
@mhoeger seems like it sorted it out, thanks!

![image](https://user-images.githubusercontent.com/1437075/88382781-d8e4cc00-cdb1-11ea-8946-d1214feafbac.png)

**Comment by mhoeger** [comment]
Closing this issue as resolved. Added an extra section to the timer trigger issue analysis diagnostic (detector) to detect functions with startup errors too
