### ISSUE TITLE
Impossible to exclude `node_modules/.cache` from watch

### ISSUE THREAD

**Issue by afillatre** [Azure/azure-functions-host#6418]
I'm trying to run e2e tests with in-memory database on local functions, but for each request done to the database, a change is done in the `node_modules/.cache` folder, and the function is restarted... so does the in-memory database.

In order to solve this issue I would "only" need to exclude the `.cache` folder from the watchlist, but looking at the `azure-functions-host` code, I see this is hard coded (ScriptHostOptionsSetup:31 => `options.WatchDirectories.Add("node_modules");`)
#### Repro steps

1. Start a node function
2. Update something in `node_modules/.cache`
3. See the function get restarted
#### Expected behavior

There should be a way to exclude this folder, or at least the very specific one I need to be excluded

#### Actual behavior

Neither setting a "watchDirectories" in the `host.json` or adding `node_modules/.cache` in the `.funcignore` works.

#### Known workarounds

None

#### Related information 
* Programming language used : Node 12x

**Comment by ankitkumarr** [comment]
@mhoeger, do you have any suggestion for this?

Do we suggest users to not publish `node_modules/.cache` along with their app?

**Comment by afillatre** [comment]
@ankitkumarr since its during e2e tests (executed locally), I'm not publishing this folder (or maybe it should be excluded somewhere in the configuration ?)

**Comment by ankitkumarr** [comment]
I see. If it's for local e2e testing, do you require that directory? What if you have a step in your test process to manually delete the `node_modules/.cache` to help unblock you, while we figure out the best recommendation?

**Comment by afillatre** [comment]
It’s actually the in-memory database that uses this folder to track things. I was able to configure this component to make it use another folder, but I need to manually clean up, then, which is not ideal

**Comment by kuba-lilz** [comment]
Just chipping in, since I have a closely related problem.

My project directory contains `node_modules` dir with loads of packages, and `func start` tries to watch all of them, over 30k of files it shouldn't concern itself with. It's silly, and makes my system hit max inotify watcher limit.

`watchDirectories` option seems to only add new directories to list of watched directories, but doesn't remove default ones, which is everything in current directory path.

It would be really great if there was a way to specify whitelist or blacklist of directories to watch.

**Comment by v-anvari** [comment]
Hi @afillatre , Apologies for the delayed response. Were you able find a solution? do let us know if a follow up is required
