### ISSUE TITLE
Azure functions cosmosdb input binding throws 500 internal server error in nodejs when key not found in container.

### ISSUE THREAD

**Issue by pavinan** [Azure/azure-functions-host#6454]
Azure functions cosmosdb input binding throws 500 internal server error in nodejs when key not found in container.
I am trying this tutorial

https://docs.microsoft.com/en-us/learn/modules/chain-azure-functions-data-using-bindings/5-read-data-with-input-bindings-portal-lab?pivots=javascript

#### Investigative information
In logs it is showing "Value cannot be null. (Parameter 'key')".

#### Repro steps
Provide the steps required to reproduce the problem:

#### Expected behavior
key is not in the container so it should give 0.

#### Actual behavior
500 Internal server error.

#### Related information 

```javascript
module.exports = function (context, req) {
    
    var bookmark = context.bindings.bookmark
    
    if(bookmark){
            context.res = {
            body: { "url": bookmark.url },
            headers: {
            'Content-Type': 'application/json'
            }
        };
    }
    else {
        
        context.res = {
            status: 404,
            body : "No bookmarks found",
            headers: {
            'Content-Type': 'application/json'
            }
        };
    }

    context.done();
};
```

**Comment by mhoeger** [comment]
Hi @pavinan ! This sounds like expected and correct behavior. When you use input/output bindings or connect to a trigger, internally, we instantiate a new Cosmos DB client inside of our runtime process. If you tried to instantiate a Cosmos DB client inside of your code too with no credentials, your function would be failing similarly (unless you did some check for the existence of the key and decided not to instantiate). Not failing would be more harmful behavior because then you would expect your function app to be connecting to Cosmos DB when it isn't.

When you said the expected behavior is to give 0, do you mean that it should run your function but just not add information from Cosmos DB (so input is undefined or 0)?

**Comment by pavinan** [comment]
No, connection string is fine. According to tutorial. The binding, ```context.bindings.bookmark``` returns "1" if the "id" exists in container and "0" if not exists.
So now it is returning "1" if "id" exists, but when "id" not exists it is throwing error instead of "0". I think function failing before execution and while resolving the input binding.

I am referring this line ``` var bookmark = context.bindings.bookmark```.

Sorry @mhoeger I have given wrong URL in the issue. I have corrected it. Here is the reference.

![image](https://user-images.githubusercontent.com/8724933/89370533-98187b80-d6fe-11ea-94c3-bcdff3a96dbe.png)

**Comment by mhoeger** [comment]
Ahh ok thanks for the correction! I'll repro this and see what's going on

**Comment by mhoeger** [comment]
@pavinan - thanks so much for the report, we're putting out a fix ASAP: https://github.com/Azure/azure-functions-host/pull/6478
