### ISSUE TITLE
Azure Function Blob Storage Trigger is not running

### ISSUE THREAD

**Issue by khmerforce** [Azure/azure-functions-host#6533]
Please help. I enabled the Azure Function but for some reason when I upload the file. The Azure Function does not process when I check the log. I waited for like 30 mins the process is still not running. Please help me. I'm not sure where to check or how to debug it in order to make it run. Thank you!

**Comment by v-anvari** [comment]
Hi @khmerforce , We tried to reproduce the issue, but the function app is running fine with every blob uploaded. 

Can you share the name of function app, time stamp & region, so that we will be able to check the issue with the function app that you are running.

Also, please check the logs in the "[application insights logs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring?tabs=cmd#view-telemetry-in-application-insights)", to find the detailed log history.

Choose "[Logs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring?tabs=cmd#query-telemetry-data)" to explore or query for logged events of the function app.

Let us know, if the information helps you to resolve the query.
