### ISSUE TITLE
Function-level API to to pull all errors for each function to display on the Function's overview page.

### ISSUE THREAD

**Issue by apawast** [Azure/azure-functions-host#6536]
Portal ask: a Function-level API that allows them to pull all errors and misconfigurations for each function separately. This will be used for a notification tab in the individual function's overview blade.

Work items:
- https://github.com/Azure/azure-functions-host/issues/6979
- https://github.com/Azure/azure-functions-host/issues/6980
- https://github.com/Azure/azure-functions-host/issues/6981

**Comment by brettsam** [comment]
Part of this will be working with @ehamai and @apawast to come up with exactly what we need to be returning and how it will be used. We likely already have this data -- and may just need to surface it through the status calls the portal already makes.

**Comment by pragnagopa** [comment]
@soninaren  please follow up with @brettsam.

**Comment by ehamai** [comment]
Hey guys,

Sorry for the delay.  Here's a rough sketch below of the experience we'd like to build which I think has changed a bit since the original ask was made.  Basically, we'd like to be able to show users a quick top-level status of their functions without needing App Insights because:

1. Not all customers want to use AI and requiring it of them just to get a quick status view of their app seems like overkill.
2. Even if customers did use AI, it still takes a while for us to query.  Portal performance goals are to load our blades within 4s at the 95th percentile and just trying to figure out which AI resource to query can take that long.  In this case, we're trying to get a summary of all functions at once, so I'm sure we wouldn't even come close to our perf goals.

We had a quick discussion with @fabiocav about a month ago where we discussed the possibility of just storing the last run state somewhere in our API layer.  If the last run succeeded, then we store lastRun = succeeded.  If it didn't, then we say failed but also include the error details of that failure.  Then when we do a list functions operation, we could get all of these status/error details.

This isn't in the mock, but perhaps a better improvement would be to also include an aggregate of number of success/failures in the last hour or day or something which would paint a better picture of the overall health of their function.

**Add a "Last Execution" status column to the functions list.  Or a better idea is to include number of success/failures in X-time**
![image](https://user-images.githubusercontent.com/5695405/92953216-31316500-f416-11ea-9154-a109cb03b203.png)

**Clicking on the error status could show the last execution error with a link to the monitor blade for more details**
![image](https://user-images.githubusercontent.com/5695405/92953257-48705280-f416-11ea-828f-7358b04b588b.png)

**Comment by fabiocav** [comment]
We need to ensure the requirements outlined in #6534 are in scope here.

**Comment by fabiocav** [comment]
Working through the design on this item.

**Comment by ehamai** [comment]
Thanks @fabiocav.  Would you mind letting me know when you have an idea for the API content/shape before you folks get too far into the design?

**Comment by fabiocav** [comment]
Not at all! We'll keep you updated.

/ @soninaren

**Comment by soninaren** [comment]
Linking the granular workitem
- https://github.com/Azure/azure-functions-host/issues/6979
- https://github.com/Azure/azure-functions-host/issues/6980
- https://github.com/Azure/azure-functions-host/issues/6981

**Comment by mhoeger** [comment]
@soninaren - this API will surface function indexing errors right?

**Comment by mhoeger** [comment]
ack didn't mean to close!!

**Comment by soninaren** [comment]
> @soninaren - this API will surface function indexing errors right?
Yes it should.

**Comment by anthonychu** [comment]
@ehamai @annaji-msft @miwebst Any way we can surface this info from managed functions in Static Web Apps?

**Comment by fabiocav** [comment]
@soninaren all of the associated work items have been closed. Should this be closed as done?

**Comment by soninaren** [comment]
yes this can be closed
