### ISSUE TITLE
Azure  database connections 

### ISSUE THREAD

**Issue by IDONTSUDO** [Azure/azure-functions-host#6544]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
JavaScript
#### Question
I have an MSSQL database. And there are your Azure Timer triggers that run every 5 minutes. They go to the MSSQL database and rake the task queue. And as I understand it new, every 5 minutes when establishing a connection to the database. Can I somehow open one connection just in the case of a regular connection server, I open it once.

**Comment by soninaren** [comment]
@IDONTSUDO we have documentation on using connection pooling and using static clients. This should help you avoid opening a new connection on every invocation. Here is the link to the documentation.

https://docs.microsoft.com/en-us/azure/azure-functions/manage-connections

Closing the issue since this is not a function runtime issue.
