### ISSUE TITLE
BlobTrigger is not working,Function 'pii' will wait 2000 ms before polling queue 'azure-webjobs-blobtrigger-dqml1'. Container 'test1' does not exist.

### ISSUE THREAD

**Issue by Gandharv30** [Azure/azure-functions-host#6570]
I have created an Azure functions app with a blob storage trigger. Now in my storage account, there is container 'test1' in which there is a folder 'my-directory' which I am tracking. I tested the code on my local machine, the function fires whenever a file is uploaded to blob storage mentioned above. But when I am running this on the azure portal, the function does not fires at all when a file is uploaded to blob storage and shows the following two statements in the logs:

**_Function 'pii' will wait 2000 ms before polling queue 'azure-webjobs-blobtrigger-dqml1'.
Container 'test1' does not exist._**

Also to mention I have only one functions app created in my account and there is only one function 'pii' in it as this was a fix suggested to someone.
Other resources in my account are dqml, an Azure machine learning service, and dqml, a storage account

I tried to these paths in function.json:-
**_"path": "test1/{name}.csv"
"path": "test1/my-directory/{name}.csv"_**

PS: I am using a free trial account!

**Comment by Gandharv30** [comment]
@soninaren , can you please help me out ?

**Comment by soninaren** [comment]
@Gandharv30 , Please check the storage account you are using on the function app on azure, verify it is the same storage account that has the test1 container. The polling wait is expected in blob trigger.

**Comment by Gandharv30** [comment]
Its the same storage account because when I run it on my local machine ie I also upload  file through a python script to that storage account, it correctly detects a change in blob storage and fires the function. @soninaren

**Comment by soninaren** [comment]
The only reason you would get `Container 'test1' does not exist.` is if the storage account does not have the container present. Please check the value of the connection property in the function.json.  Also please fill out the bug report template.

#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app => `Platform features` => `Diagnose and solve problems` and the relevant dashboards before opening your issue.



#### Investigative information

Please provide the following:

- Timestamp:
- Function App version:
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:



#### Repro steps

Provide the steps required to reproduce the problem:



#### Expected behavior

Provide a description of the expected behavior.



#### Actual behavior

Provide a description of the actual behavior observed.



#### Known workarounds

Provide a description of any known workarounds.



#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used
