### ISSUE TITLE
Dependency injection in Azure Functions injects null if dependency is missing

### ISSUE THREAD

**Issue by thomaslevesque** [Azure/azure-functions-host#6587]
#### Investigative information

Please provide the following:

- Timestamp: (not relevant)
- Function App version: 3.0.7
- Function App name: (not relevant)
- Function name(s) (as appropriate):  (not relevant)
- Invocation ID:  (not relevant)
- Region: (not relevant)

#### Repro steps

Provide the steps required to reproduce the problem:

- Create a function app with a FunctionsStartup class to register dependencies.
- Create a function that depends on Service1 that depends on a Service2
- Register Service1, but "forget" to register Service2

```csharp
public class MyFunction
{
    public MyFunction(Service1 service1) { }

    [Function("MyFunction")]
    public void Run(...) { ... }
}

public class Service1
{
    public Service1(Service2 service2) { }
}

public class Service2 { }

...

builder.Services.AddSingleton<Service1>();
```
#### Expected behavior

An exception should be thrown because Service1 can't be constructed, because Service2 is not registered

#### Actual behavior

`null` is injected into Service1 for parameter service2.

This is surprising, because the usual behavior of Microsoft.Extensions.DependencyInjection is to throw in that situation.
But if my understanding is correct, Azure Functions uses DryIoC for DI (why?)

#### Known workarounds

Check for null in the constructor of Service1. It works, and is good practice anyway, but it's not usually necessary outside Azure Functions.

#### Related information 

Provide any related information 

* Programming language used: C#
* Links to source: (confidential)
* Bindings used: ServiceBusTrigger, TimeTrigger

**Comment by thomaslevesque** [comment]
Note that the issue only occurs for dependencies of dependencies.
For direct dependencies of the Function class, an exception is thrown

**Comment by jonathanantoine** [comment]
Same issue, any update ?

**Comment by v-anvari** [comment]
Apologies for the delayed response. Do let us know if you are still seeing this issue

**Comment by thomaslevesque** [comment]
@v-anvari yes, I'm still seeing the issue

**Comment by v-anvari** [comment]
Tagging @fabiocav for more inputs

**Comment by fabiocav** [comment]
Flagging this as a breaking change. 

This will likely not make the 4.0 release, but it's something we could consider as a configurable behavior/option.

**Comment by thomaslevesque** [comment]
Out of curiosity, why doesn't Azure Functions use the default DI container from Microsoft.Extensions.DependencyInjection?

**Comment by BrunoJuchli** [comment]
There's a related issue which was mistakenly posted @ DryIoc as the stack trace reveals DryIoc -- but this repo contains a copy of the source code of DryIoc, DryIoc is not referenced as a nuget package.
https://github.com/dadhi/DryIoc/issues/180

Another issue pertaining to the same problem was also active on this repository a while ago:
https://github.com/Azure/azure-functions-host/issues/3399

The issue might be fixed by using a newer version of DryIoc. As far as I can see the docs of DryIoc seem to state that it [should actually return a null value](https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/RegisterResolve.md#isregistered) instead of a partially resolved dependency:

>Important: IsRegistered does not check if a service is actually resolvable. For instance, if some of its dependencies are not registered. To check for resolvability use Resolve with IfUnresolved.ReturnDefault:

This is exactly how it's being used in azure functions, see:

https://github.com/Azure/azure-functions-host/blob/5294afc32a34e5783caade40a2629427cee0418a/src/WebJobs.Script.WebHost/DependencyInjection/ScopedServiceProvider.cs#L25

This in turn gets called from 

https://github.com/dotnet/runtime/blob/3eeee42e18c911bac7728b899874a28b0d389eaa/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ActivatorUtilities.cs#L153

which performs a null-check and throws an exception if it's null (unless a default value is provided, then null is ignored).

The problem here is that DryIoc is not referenced as nuget package but this repo contains a copy of it's source code: https://github.com/Azure/azure-functions-host/tree/master/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc

**Comment by BrunoJuchli** [comment]
@fabiocav I had a look at the code and it seems to me this is not something which can easily be made configurable by a flag.
The call to DryIoc is made via a [wrapper](https://github.com/Azure/azure-functions-host/blob/5294afc32a34e5783caade40a2629427cee0418a/src/WebJobs.Script.WebHost/DependencyInjection/ScopedServiceProvider.cs#L25) implementing the IServiceProvider interface which in turn is not called by code from this repo but via Microsoft.Extensions.DependencyInjection.Abstractions. That code relies on null being returned in case resolution fails (important for resolving parameters with a default value, where null is acceptable).
The wrapper itself however has no knowledge about these cases.

As far as I understand the current behavior is a bug which is fixed in current versions of DryIoc.
Introducing a config flag would mean adapting the copied DryIoc source code and thus further deviating from the original DryIoc source code. I suppose forking and maintaining an IoC container does not fit the scope of this repo.

Therefore I would suggest a breaking change without fallback behavior.

Ideally DryIoc should be removed from this repo entirely.

**Comment by lommez** [comment]
Hi @fabiocav,
Do you have any updates on this issue?

**Comment by Senderek** [comment]
Any updates on the issue?

**Comment by arphox** [comment]
Hi, while we are waiting for an implementation, I made a workaround.
I created a unit test which with gathers all types from the function app assembly with reflection, selects all types' all constructors' parameters' types, and tries to resolve them from a test service collection which has been configured with the Startup class' overridden Configure method.

See my implementation skeleton (for xunit) in [**this gist**](https://gist.github.com/arphox/07e4af629028eef0378d6c11da466139).

**Comment by fabiocav** [comment]
Closing this issue as this is not something that will be done in 4.0. 

As mentioned above, this would be a breaking change and the recommendation is to move to the .NET isolated model, where the behavior is what is expected and also fully configurable (including the use of other container frameworks). The host will be updated to move away from DryIoc, but this optimization will be used for the out-of-proc model only.

**Comment by PureKrome** [comment]
@fabiocav sorry to ask a question in a closed issue -> are you saying that this issue is only of IN-PROC models (because that uses DryIOC)?

So the ISOLATED model is not affected by this?

**Comment by fabiocav** [comment]
@PureKrome that's correct. 

For isolated, the function payload (the code you deploy), runs outside of the host and DI in those SDKs is all based on standard .NET DI interfaces and uses `Microsoft.Extensions.DependencyInjection` by default (also overridable). The DI behavior there is consistent with other models (Console, ASP.NET Core, etc.). 

The host version that will soon be servicing OOP payloads (including Isolated) has also been migrated away from DryIoc, though, that becomes an implementation detail and doesn't impact the deployed code. 

Hope this helps.

**Comment by PureKrome** [comment]
Thanks @fabiocav - sure helps clarify things. Appreciate the reply. Keep up the great work and fighting the good fight!
