### ISSUE TITLE
best practice for number of function triggers in one azure functions project

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/azure-functions-host#6638]
#### what is the best practice for number of azure functions in your project for azure functions in consumption plan
 i have a project with already 20 azure functions (most of them service bus striggers) which are reading message doing some dbquery and then saving to db.  If i keep adding more azure functions (backend jobs, more servicebus trigger functions then will it affect the performance due to shortage of ports and other resources like cpu/ram etc.  please advise .

**Comment by v-anvari** [comment]
Hi @krishnasingh1818 , you were right, more number of functions in a single app will put more load on CPU and memory since they will all share the same  resources. It may or may not necessarily cause a shortage of ports - it depends on whether the many functions are connecting to the same or different endpoints. More functions in a function app may also have an impact on cold-start. It's very similar to having more APIs in a REST app. We take care of things like connection pooling but if more functions are running, there's going to be more CPU and memory utilization at any one point. 

So it is suggested to build different Function Apps instead of more functions in a single app.
