### ISSUE TITLE
[Rpc][MultipleWorkers] Add check for memory consumption before spawning new processes

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#6704]
cc @AnatoliB @vrdmr 

This is related to https://github.com/Azure/azure-functions-host/issues/6671

Add check for memory consumption before spawning new worker processes.

**Comment by fabiocav** [comment]
@pragnagopa could you share more details about:

- Issues this would help address (any evidence of crashes OOM exceptions from creating additional worker processes?)
- Details on what that check would validate before launching the process

**Comment by AnatoliB** [comment]
> * Issues this would help address (any evidence of crashes OOM exceptions from creating additional worker processes?)

@fabiocav We may not be getting enough signals on these crashes today because:
- By default, this feature is turned off: https://github.com/Azure/azure-functions-host/issues/7499
- By default, FUNCTIONS_WORKER_PROCESS_COUNT is 1

As a result, only users who decided to experiment with FUNCTIONS_WORKER_PROCESS_COUNT will run into these crashes. These users already expect potential troubles from increasing FUNCTIONS_WORKER_PROCESS_COUNT, so they probably just decrease the value instead of complaining to us. Enabling https://github.com/Azure/azure-functions-host/issues/7499 by default (which we intend to do eventually) will lead to creating more processes automatically, so we should anticipate OOM to happen more often.

/cc: @alrod

**Comment by pragnagopa** [comment]
@fabiocav / @liliankasem  - removed "Needs:Author Feedback" label for this issue. Thanks @AnatoliB  for adding details.

**Comment by liliankasem** [comment]
Is it worth closing this in favour of #7499, or is 7499 acting as an epic we can link issues to?

**Comment by fabiocav** [comment]
Based on our discussion this week, I'll say yes. This should be tracked by the `Intelligent concurrency for language workers` issue you've linked (#7499).

**Comment by liliankasem** [comment]
@fabiocav I had a sync with Anatoli and Alexey about this and here's the TLDR;

- Intelligent concurrency as a feature has already been implemented and is in preview (Alexey will update #7499 with the current progress)
- The team is waiting for feedback to understand how many customers will be impacted by this through CRIs/customer complaints
- Anatoli does not believe we can GA without the memory checks being implemented, so either way regardless of Intelligent concurrency, this should be implemented
- There are plans to eventually do this but it is low priority at the moment for their team as they are waiting for customer feedback to roll in

We can either reopen this issue and address it ourselves, or leave this closed and it will eventually be addressed by the intelligent concurrency work.
