### ISSUE TITLE
Cannot access a disposed object. Object name: 'LoggerFactory'.

### ISSUE THREAD

**Issue by zmarty** [Azure/azure-functions-host#6715]
Azure Functions 3 on Windows
.Net Core 3.1
App Service Plan

Referencing previous issue as requested: https://github.com/Azure/azure-functions-host/issues/1690

@brettsam In the last 7 days, our host(s) crashed 122 times with Cannot access a disposed object. Object name: 'LoggerFactory'.

**Comment by zmarty** [comment]
https://github.com/Azure/azure-functions-host/issues/1690

**Comment by brettsam** [comment]
Can you share the stack trace that you get with the exception? This happens because the host is disposed and something is still trying to run on that disposed host. LoggerFactory just happens to be one of the first services that throws if it's used while it's disposed, so this exception is thrown first. We've got to figure out what is trying to run on that host and see if we can fix that.

**Comment by v-bbalaiagar** [comment]
Hi @zmarty, Can you please let us know if this is yet to be triaged.
