### ISSUE TITLE
Azure Functions Runtime is unreachable -> Microsoft.NET.Sdk.Functions 3.0.11

### ISSUE THREAD

**Issue by Tealons** [Azure/azure-functions-host#6908]
We are seeing the following error:

![image](https://user-images.githubusercontent.com/7141563/99563629-bd897680-29c9-11eb-83a6-cd4d837ee9ae.png)

This error is not there with Azure SDK 3.0.7, however that version has issues with the extensions.json generation.

We have the following host.json:

```
{
  "version": "2.0",
  "functionTimeout": "00:10:00"
}

```

Our function.json looks like this:

```
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-3.0.11",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "queueTrigger",
      "connection": "AzureWebJobsStorage",
      "queueName": "exceptionlogicqueue",
      "name": "batchId"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/CMP.Serverless.Scheduled.dll",
  "entryPoint": "CMP.Serverless.Scheduled.Functions.ExceptionLogicFunction.Run"
}
```

And our functions have the following extensions.json: 

```
{
  "extensions":[
    { "name": "Startup", "typeName":"CMP.Serverless.Scheduled.Startup, CMP.Serverless.Scheduled, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"},
    { "name": "AzureStorage", "typeName":"Microsoft.Azure.WebJobs.Extensions.Storage.AzureStorageWebJobsStartup, Microsoft.Azure.WebJobs.Extensions.Storage, Version=4.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}
  ]
}

```

The functions themselves are operating normally so we could ignore this error... However, it feels like we are doing something wrong and will hit a problem anywhere in the near future?

**Comment by Tealons** [comment]
Oke, we did long debug sessions the past couple of hours...  and found the solution.

In our project we added dependencies in our startup project to support the logic that was coming from our old project. One of the packages that we added was identity the following way:

```
services.AddIdentity<ApplicationUser, ApplicationRole>(options =>
                {
                    options.SignIn.RequireConfirmedEmail = false;
                    options.Password.RequireDigit = true;
                    options.Password.RequiredLength = 8;
                    options.Password.RequiredUniqueChars = 1;
                    options.Password.RequireLowercase = true;
                    options.Password.RequireNonAlphanumeric = true;
                    options.Password.RequireUppercase = true;
                })
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders(); 
```

I agree that it was a bit strange to add this, but our code used several functions in this package, so we did not mind for now. The main problem is that there is no error to be found that this package is causing the host problems. We found this out by trial and error by removing stuff from our startup.cs line by line. We are still clueless why this package caused our problems, but we fixed it now by creating some custom functions to replace those in the identity package. I hope this helps someone else and maybe we could get some pointers in how we can detect this problems better in the future?

**Comment by v-anvari** [comment]
Hi @Tealons , We appreciate your contribution to the repo and sharing your learnings with us. While the error could be because of various reasons. We are glad that you were able to fix it. 

Here are few reasons that were identified in the past and listed down to troubleshoot the error - - https://docs.microsoft.com/en-us/azure/azure-functions/functions-recover-storage-account#storage-account-was-deleted

While your issue will surely be helpful for other folks working on the same scenario as yours. Closing this issue, please feel free to reach back to us or re-open this issue in case of any queries.

**Comment by hirandesai** [comment]
This is an open issue and not sure how come got closed without a solution @v-anvari .
The problem here is - when using ASP.NET Identity packages with Azure function, the function works in your local development environment as expected but when it gets deployed to Azure, the host becomes unreachable.

For a new project, the work around is to remove the ASP.NET Identity dependency but knowing the popularity of ASP.NET Identity, this is not a acceptable solution.
