### ISSUE TITLE
Adding 'Microsoft.Extensions.Http' causes functions to fail at runtime

### ISSUE THREAD

**Issue by MarcDHall** [Azure/azure-functions-host#6946]
I have been trying to set up my functions App to use multiple named HttpClients. 

In order for this to work I need `IHttpClientFactory` from `Microsoft.Extensions.Http`, but adding this causes functions to fail at runtime with this error:

![image](https://user-images.githubusercontent.com/7155808/100329843-1ce91700-2fc6-11eb-992a-139f3b692879.png)

I'm am using v3 but had the same issue with v2 (I upgraded to try to fix the issue). I've read similar issues that suggest `Microsoft.Extensions.Dependency.Injection.Abstractions` targets the wrong version of `.netstandard`. I'm a little confused because I've read lots of content that suggests that this should be pretty straight forward, but it doesn't look like this could ever have worked.

Creating a new Functions App (.net core 3.) from the Visual Studio template and adding `Microsoft.Extensions.Http` causes this:

![image](https://user-images.githubusercontent.com/7155808/100330882-67b75e80-2fc7-11eb-8643-ccf367842544.png)

...adding that package doesn't make a difference.

**Comment by AartBluestoke** [comment]
as i commented in  https://github.com/Azure/azure-functions-host/issues/6893#issuecomment-726386105
- when you run azure functions, it starts before it loads your code. 
- only 1 version of a dll can be loaded at once.

Consequence: if you need a library that is a direct or indirect dependency of azure functions you can only use the version that is loaded. This is a case where azure functions is incorrectly reporting its hard dependencies.

eg: if you are using azure functions 3.0.7, then you must use a library binary compatible with logging.abstractions 2.1.0
When your code (eg if you have a asp.netcore dependencency) asks for something that is only found in Abstractions >=5.0 the runtime (correctly) responds "sorry, that function isn't there", because all it has is the 2.1.0 dll in memory.


![image](https://user-images.githubusercontent.com/1892829/100553711-72cdff80-32e3-11eb-94ec-c30c1bdf49ce.png)


Therefore the many tickets that will be raised that are like this can only be solved by upgrading azure functions to a newer version which has a dependency on the 5.x line of the abstractions.

In this particular case, if azure functions used Microsoft.Extensions.Logging.Abstractions 5.0, then it would be fine because that library appears to be backwards compatible so the reverse error doesn't occur (no runtime failure if you expect 2.1 and actually get 5.0). 

If that is not true for *all* libraries in common between azure functions and the libraries your code uses, then you will  be pinned in terms of your dependencies and azure functions versions.

**Comment by MarcDHall** [comment]
Thanks for the reply @AartBluestoke.

This is a bit of a bear-trap. There is documentation covering use of nuget packages that get back to this issue, like...

[https://docs.microsoft.com/en-gb/azure/azure-functions/functions-dotnet-dependency-injection](https://docs.microsoft.com/en-gb/azure/azure-functions/functions-dotnet-dependency-injection)

...that doesn't mention this. IIRC I ran into this issue early on trying to do dependency injection. I think there should be a page in docs about this specific limitation.

**Comment by felipementel** [comment]
Hi, @MarcDHall can you show me your csproj file?

I think there is some package from .net 5 - and the function app doesn't support .net 5 yet.

**Comment by MarcDHall** [comment]
@felipementel I don't have this issue anymore. The project running now so the .csproj doesn't recreate the issue. 

At some point I upgraded from netcore2.1 and Functions API v2 to netcore3.1 and Functions v3... that might have fixed it.
