### ISSUE TITLE
Metadata generation failed. Exit code: '-1073741502' Error: '' #6769

### ISSUE THREAD

**Issue by kristianbendren** [Azure/azure-functions-host#6947]
nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.2.0\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error : Metadata generation failed. Exit code: '-1073741510

The problems occurs when having 
.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.2.0

Removing this folder and only running package 1.1.8 works fine to build again.

**Comment by the-castman** [comment]
I am getting the same error but with 1.1.8 and with Microsoft.NET.Sdk.Functions 3.0.9

`[error]C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.1.8\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): Error : Metadata generation failed. Exit code: '-1073741502' Error: ''`. 

I am getting this om my Azure Devops build pipeline and very sporadic och sudden, using the clean option on the pipeline doesn´t help, This started to appear since one week ago. Sometimes after waiting a while, triggering a new build it would succeed. This is starting to get really annoying!

**Comment by ghost** [comment]
Thanks for the pointer @krillehbg This was exactly the issue on my local.

@the-castman I wonder if the Azure DevOps clean option is doing what we hope in giving us a completely fresh build env. I wonder if waiting a while then triggering a new build is (by chance) assigning a different build agent in the MS infrastructure.  :thinking:

**Comment by LeonsBuntis** [comment]
I'm getting same error with Microsoft.NET.Sdk.Functions Version="1.0.38".

There is no reference to microsoft.azure.webjobs.script.extensionsmetadatagenerator in my project, but I have encountered this issue in Azure Devops. Seems that if the package is downloaded by other projects that are built on same build agent it breaks my project.

The Azure DevOps clean option does not clean up shared nuget packages that are stored in "c:\users\\%username%\\.nuget\packages".

There is no such issue in newer version 1.2.1. of microsoft.azure.webjobs.script.extensionsmetadatagenerator, but the 1.2.0 must be cleaned up otherwise I still get same error.

Is there any workaround for this issue, other than forcing other teams that use same build agents to upgrade and cleanup packages?

**Comment by StefH** [comment]
Which .NET SDK version do you use when building your Azure Function project?

_(I solved this problem by using .NET SDK 3.1.x in the build pipeline instead of the default latest .NET 5.0)_

**Comment by v-bbalaiagar** [comment]
Hi @krillehbg, Apologies for the delayed response. Were you able find a solution? do let us know if a follow up is required.
