### ISSUE TITLE
Consumption Function with Blob Trigger stops listening after internal "Server is busy" crash

### ISSUE THREAD

**Issue by emilbm** [Azure/azure-functions-host#6967]
We have a setup where a Consumption Function App with a blobtrigger handles bulk amounts of blobs. 

We uploaded just under a million blobs, and when the function began executing, it ran for several hours after which we received an exception that the "Server is busy" on Dec 4, 2020, and that the host was shutting down. From then on, the blob trigger ceased firing, and no further blobs were handled over the weekend until I visited the portal monday morning (Dec. 7, 2020), after which processing resumed.

As you can tell if you look up the exception log in our insights, the error is entirely internal to the azure libraries, so I take it there's some sort of unhandled crash in the library for listening to blob triggers.

#### Investigative information

- Timestamp: 12/4/2020, 5:59:59.666 PM (Time of insights exception log)
- Function App version: ~v3
- Function App name: Lasso-EventHandlerBulk
- Function name(s) (as appropriate): EventHandlerBulk
- Invocation ID: Can't see from Exception in insights
- Region: West Europe

#### Expected behavior

The consumption function should have continued to execute until there were no more blobs to handle.

#### Actual behavior

Function stopped reacting to blobs until I visited the portal.

#### Known workarounds

Visit the portal...

**Comment by v-anvari** [comment]
Hi @emilbm, We have gone through the logs for the mentioned TimeStamp and found the below errors. Please go through the recommended actions and let us know if this eliminates the errors.

**Error:**
Source: Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostExceptionHandler
Microsoft.Azure.Storage.StorageException : The server is busy.
**Recommended Action:**
Since it is a Storage exception. A good way to investigate these issues is enable Storage Analytic metrics and see if your application is within the storage scalability targets. There are transaction metrics for number of requests and number of throttling errors.
[Monitoring Azure Blob storage | Microsoft Docs](https://docs.microsoft.com/en-us/azure/storage/blobs/monitor-blob-storage?tabs=azure-portal)
[Scalability   and performance targets for standard storage accounts - Azure Storage |   Microsoft Docs](https://docs.microsoft.com/en-us/azure/storage/storage-scalability-targets)

**Error:**
An unhandled exception has occurred. Host is shutting down.
**Recommended Action:**
Please try using Microsoft.Azure.WebJobs.Extensions.Storage 4.0.0 and above, which has the latest fix for "An unhandled exception has occurred. Host is shutting down". Release notes are here: https://github.com/Azure/azure-webjobs-sdk/releases/tag/storage-v4.0.0-preview2.

**Error:**
Singleton lock renewal failed for blob 'lasso-eventhandlerbulk/WebJobs.Internal.Blobs.Listener' with error code 306. The last successful renewal completed at 2020-12-04T17:59:28.833Z (31024 milliseconds ago) with a duration of 26 milliseconds. The lease period was 60000 milliseconds.
**Recommended Action:**
https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger#troubleshooting

**Error:**
Also, We see that "There were time periods were your function App CPU consumption was above 70% here. Having CPU intensive tasks might cause slowdown and errors.
**Recommended Action:**
Please consider reducing [concurrent calls per instance and batch sizes](https://docs.microsoft.com/en-us/azure/azure-functions/functions-best-practices#configure-host-behaviors-to-better-handle-concurrency) for your triggers in [host.json](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json-v1) if you are seeing high CPU usage for your function app.
