### ISSUE TITLE
Azure Function App stops responding to event after ~4 days if left unattended

### ISSUE THREAD

**Issue by brtkdotse** [Azure/azure-functions-host#7025]
We're running a Function App that has functions triggered by both Timer and Servicebus triggers. They work fine, but if left unattended they triggers stop firing after ~4 days (see screenshot). Doing any of the following seems to cause the triggers to "wake up":

- Redeploying the Function App
- Restarting the Function App
- Looking at the Function App in Azure Portal (?!)

#### Investigative information

Please provide the following:

- Timestamp: 2021-01-04T09:14:52.4427743
- Function App version: -
- Function App name: -
- Function name(s) (as appropriate): 
- Invocation ID: 1677112a-a125-4c3d-b433-7abeefb9c970
- Region: Northern Europe

#### Repro steps

1. Deploy Timer and Servicebus triggered functions
2. Verify they are running and are triggered by the appropriate events

#### Expected behavior

The functions should continue running without any intervention indefinitley.

#### Actual behavior

Functions stop being triggered after around 4 days / 96 hours. 

#### Known workarounds

Redeploying the application restarts the triggering, as does restarting the application. As I'm typing this, I noticed the functions started running again after I _viewed_ them in Azure Portal.

#### Related information 

Screenshot of the function count:

![image](https://user-images.githubusercontent.com/49452986/103522958-6b1def80-4e7b-11eb-9da8-8a7ab63545f4.png)

**Comment by v-anvari** [comment]
Hi @brtkdotse , Is this a consumption plan?
This usually happens when the [function timeouts](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#timeout). On a Consumption plan, a function execution times out after a configurable period of time.

**Comment by brtkdotse** [comment]
Nope, this is running on an autoscaling P1v2 (up to 3 instances)

**Comment by v-anvari** [comment]
@brtkdotse , Thank you for the confirmation. We will go ahead and check the logs using the invocation ID provided and see if we can find any exceptions or errors.

**Comment by brtkdotse** [comment]
Thanks, let me know if you need any additional info!

**Comment by v-anvari** [comment]
Hi @brtkdotse , I tried to search the invocation id in logs but failed to retrieve any logs. Could you provide us the Function App Name instead.

**Comment by brtkdotse** [comment]
Sorry, here's a new Invocation ID and timestamp: **71534302-f5f5-466c-be41-70a42bdf5372** (2021-01-11T08:41:14.985).

**Comment by v-anvari** [comment]
Hi @brtkdotse , I am sorry but I do not see any App running with that invocation id and no App running during that time in Northern Europe.

It would be helpful if you could provide me the function App name in private at v-anvari@microsoft.com

**Comment by v-anvari** [comment]
Hi @brtkdotse , Thank you for providing the App Name. 

The Invocation ID : 71534302-f5f5-466c-be41-70a42bdf5372 has completed the Event on time, I do not see any error at that time stamp. But, there are visible errors during the nearest Time Frames on the same Role Instance ID which is the cause of exceptions.

**Errors & Exception:**
1. ) Microsoft.Azure.ServiceBus.MessageLockLostException : _The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue.__ 
     Timestamp:2021-01-11T08:41:16
     Lock lost exception generally is a client-side error. Know more about it [here](https://stackoverflow.com/questions/61793052/azure-service-bus-exception-messagelocklostexception-the-lock-supplied-is-inv): 

2. ) System.ObjectDisposedException : Cannot access a disposed object.
      Timestamp:2021-01-11T08:41:13
[Diagnose exceptions in your web apps with Application Insights](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-exceptions#:~:text=%20Diagnose%20exceptions%20in%20your%20web%20apps%20with,to%20send...%205%20Next%20steps.%20%20More)

3. ) Around 1/11/2021 8:39:17 AM (UTC), on the same role instance, your application process was responding slow and more than 80% of the requests to the application was taking over 200 seconds in 5 minute interval. Open Web App Slow Tab to check app latency and analyze common patterns that cause your app to respond slowly Platform proactively healed your application by restarting the application process on affected instances. 

4. ) Also, During the same Time Frame the App is consuming an average of 96.68% of CPU on instances consuming high CPU. It is usually due to the processes in the instance call system APIs frequently. These can be IO, networking, threads context switching APIs, etc. Scaling up can be a possible solution.

5. ) There is a warning of SNAT Connection detected
Learn more: 
[Troubleshooting intermittent outbound connection errors in Azure App Service](https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-intermittent-outbound-connection-errors#avoiding-the-problem)
[How To Fix the problem](https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/#how-to-fix-the-problem)

6. ) There has been a Web App restart Around 1/11/2021 8:35:00 AM (UTC), your application process was restarted due to a user action like stopping the site from azure portal. Due to which Function executions for timer trigger were pastdue, causes when the current function invocation is later than scheduled. For example, a function app restart might cause an invocation to be missed.

**Comment by brtkdotse** [comment]
Thanks for you reply @v-anvari! The issues you saw in the logs occured _after_ i restarted the service today. What I'm wondering about is why all function executions stopped around **10:09 CET on 2021-01-06**:

![image](https://user-images.githubusercontent.com/49452986/104186210-65458280-5416-11eb-841d-9f06fdc2cf0a.png)

Except for the MessageLockLostException, there are no other failures around that time:

![image](https://user-images.githubusercontent.com/49452986/104186360-94f48a80-5416-11eb-9235-bf9aa3d314ee.png)

**Comment by v-anvari** [comment]
Hi @brtkdotse , Apologies for the delay, I went through the logs for the Time stamp - 2021-01-06 00:00:00 to 2021-01-07 10:00:00. I see the error "_Singleton lock renewal failed for blob 'Function App' with error code 409: LeaseIdMismatchWithLeaseOperation_", which is occurring almost every hour. Here is how you can troubleshoot the issue. [https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger#troubleshooting](https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger#troubleshooting)

Related information:
[azure-webjobs-sdk-extensions/issues/249](https://github.com/Azure/azure-webjobs-sdk-extensions/issues/249)
[azure-functions-host/issues/1864](https://github.com/Azure/azure-functions-host/issues/1864)
