### ISSUE TITLE
Singleton lock renewal failed for blob 'xxxxxx/host' with error code 409: LeaseIdMismatchWithLeaseOperation. The last successful renewal completed at 2021-02-09T23:43:41.979Z (17936 milliseconds ago) with a duration of 39 milliseconds. The lease period was 15000 milliseconds.	

### ISSUE THREAD

**Issue by ketanbembi** [Azure/azure-functions-host#7143]
Hi

I am facing below error in Azure function app (version used 2.0).

Singleton lock renewal failed for blob 'xxxxxxx/host' with error code 409: LeaseIdMismatchWithLeaseOperation. The last successful renewal completed at 2021-02-09T23:43:41.979Z (17936 milliseconds ago) with a duration of 39 milliseconds. The lease period was 15000 milliseconds.

After this error the job host restarts and hence stops any function running at that time,

Could anyone suggest solution to this issue,

TIA

**Comment by fabiocav** [comment]
@ketanbembi this by itself doesn't represent a problem, but is often caused by resource utilization issues, more specifically, high CPU utilization or thread exhaustion.

The recommendation would be to look a App Lens and diagnostic tools in the portal for your Function App. Without the app information, it's difficult to say what might have caused this, but engaging support if you can't find the information on the portal and this is a production app would be an option here. 

Hope this helps!
