### ISSUE TITLE
Could not evaluate 'Cosmos.CRTCompat.dll' for extension metadata. Exception message: Bad IL format

### ISSUE THREAD

**Issue by RickRockhold** [Azure/azure-functions-host#7218]
Please try the latest versions of Microsoft.Net.Sdk.Functions. Release notes:
- (for v1 and v2): https://github.com/Azure/azure-functions-vs-build-sdk/releases/tag/1.0.36
- (for v3): https://github.com/Azure/azure-functions-vs-build-sdk/releases/tag/3.0.7

_Originally posted by @brettsam in https://github.com/Azure/azure-functions-host/issues/5963#issuecomment-623732787_

**Comment by RickRockhold** [comment]
Unfortunately this has returned in 3.0.10 (with .NET core 3.1).

**Comment by danieltallentire** [comment]
On latest I get this message:
`Could not evaluate 'Cosmos.CRTCompat.dll' for extension metadata. Exception message: Format of the executable (.exe) or library (.dll) is invalid.`

Project file:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.17.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

Only solution was to downgrade the Microsoft.Net.Sdk.Functions to 3.0.7

**Comment by ankitkumarr** [comment]
@brettsam, if I understood the core issue, I think when we updated ExtensionsMetadataGenerator to use Mono.Cecil, we may have missed porting the logic to make Bad IL errors as messages rather than warnings.

Basically, when we did https://github.com/Azure/azure-functions-host/commit/8ee1fb5af64a7d9311e73d486385068e683805a0, I think we un did https://github.com/Azure/azure-functions-host/commit/f717438454435dee9c52fef7e4bd75752096df4a

If you could confirm that this is indeed what's going on, I think we can add a quick fix.

**Comment by brettsam** [comment]
Yeah, I think you're right. Let's fix this up -- it's really just a message anyway to help us debug if something has gone wrong.

**Comment by v-anvari** [comment]
@ankitkumarr / @brettsam , Do we have any updates on the fix here. Do we require to add this to any sprint for fix

**Comment by fabiocav** [comment]
This has been fixed in the latest version of the metadata generator. I don't believe the SDK has been updated to reference this latest version, so that needs to be done, but in the meantime, an explicit reference to https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator/1.2.3 would address the issue.

**Comment by v-bbalaiagar** [comment]
Hi @RickRockholdOWC, Let us know if the above information resolves your issue, or if you have any further queries.
