### ISSUE TITLE
Adding Durable storageProvider.type to SyncTriggers payload

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#7288]
#### What problem would the feature you're requesting solve? Please describe.
Currently the host does syncTriggers to update the system status of the triggers using this code 
https://github.com/Azure/azure-functions-host/blob/6b95141c6463d8815567bba913346dc780c40630/src/WebJobs.Script.WebHost/Management/FunctionsSyncManager.cs#L509-L535

But as far as I can tell, the type of the storage provider isn't taken into account. We will need that information in the payload somewhere if the type is `MicrosoftSQL`

#### Describe the solution you'd like
Include the storage type somewhere in the payload. 

#### Describe alternatives you've considered
We could assume `MicrosoftSQL` for envorinments where it should be the right choice, but it may not be entirely correct or lead to issues.  

/cc @mathewc @cgillum

**Comment by cgillum** [comment]
FYI @ConnorMcMahon 

I assume we need this fix not just for Lima, but also for Scale Controller support in Azure. In addition to the type, other information may also be needed (for example, some backends use different fields for connection information). I wonder if we should just capture the full `durableHostConfig` blob.

**Comment by mathewc** [comment]
Initially I was going to comment that it would be strange to dump host level config repeatedly into each function. However it looks like we're already doing that [here](https://github.com/Azure/azure-functions-host/blob/852eed9ceef6ef56b431428a8eb31f1bd9c97f3b/src/WebJobs.Script.WebHost/Management/FunctionsSyncManager.cs#L376).

We have https://github.com/Azure/azure-functions-host/issues/5390 tracking removal of this code from the runtime entirely, since it really shouldn't be there and is the only trigger requiring it. Perhaps we can use this new issue as a forcing function to remove this?

**Comment by ConnorMcMahon** [comment]
This sounds reasonable to me.

**Comment by TsuyoshiUshio** [comment]
Hi @cgillum  According to the conversation, do we need the `host.json` information? or still required for LogicApp scenario? I create a draft PR that includes `host.json` payload to the sync trigger to discuss the design, however, if it is not necessary, I'd happy to close my PR.  Probably, we need to change the code of the Durable Transformation part without using `host.json` payload.

**Comment by cgillum** [comment]
Hi @TsuyoshiUshio yes, we still need the host.json information, both for Durable Functions and for Logic Apps. This issue was originally going to be specific to Durable Functions. However, I think from this discussion that we agree we need a more general solution that captures host.json so that all trigger types can benefit and so that we don't need trigger specific information in the syncTriggers logic. I'll take a look at your other PR.

**Comment by pragnagopa** [comment]
Marking these as Sprint 100 to ensure we cut a hotfix release with the fixes
