### ISSUE TITLE
Support NPM install for Node functions

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#73]
We support project.json package management for C# already. We should do something similar for Node.

**Comment by davidebbo** [comment]
Key question is whether this should be a runtime or design time thing. Typically, in Kudu, it's always deployment time. but here for C# it sounds like it's runtime. Worth discussing.

**Comment by mathewc** [comment]
Yeah, whatever we do should be consistent across the languages.

**Comment by davidebbo** [comment]
Tricky thing about npm is that it's super slow to run even when there is no work to do. So we probably can't run install before running the function just in case the packages changed. Or maybe we'd need a smart marker that tells us when packages.json changed since the last npm run.

**Comment by danderson00** [comment]
A workaround for the moment is to execute npm install from a kudu console. However, it will likely fail if the package contains binaries as the version in the path in kudu will likely be different from the version running the function.

**Comment by christopheranderson** [comment]
We should discuss this. It's an interesting question. C# has the project.json per function. Node can do per function or per function app. We know that package management UI is expensive and probably out of scope. I'm inclined to say this is post RC, but I'd like to think about exposing the kudu terminal in an easier way to help mitigate (/cc @mattchenderson)

**Comment by nikos** [comment]
On a slightly related note: it would be great if after a "git push" (which deploys the new function version on the host) a "npm install" would automatically triggered. It seems currently after each deployment you have to visit the Console and install the node modules for each function over and over again.

**Comment by christopheranderson** [comment]
If you have a package.json at the root of your Function App, it will do so today.

**Comment by nikos** [comment]
At least for my current environment (using Function App version *Latest (~0.4)*) it does not work, but I had to manually trigger `npm install` after every git push again manually, as described in https://azure.microsoft.com/en-us/documentation/articles/functions-reference-node/ under *Node Version & Package Management*. This makes my DX not as pleasant as it probably could be.

**Comment by atrauzzi** [comment]
An "npm install" button might be nice somewhere in here...

![image](https://cloud.githubusercontent.com/assets/115199/23580040/832fed2a-00bf-11e7-8a39-469e6f3465e1.png)

**Comment by alterx** [comment]
Yeah, I was wondering if there was a way of remotely triggering `npm install`
It doesn't make much sense to have to manually log into the kudu console to run it. For node, this should be something that you can either start remotely or that runs automagically if it finds a valid package.json file after deploying.

**Comment by dstrimble** [comment]
At the very least it would make sense to run NPM install on function restart. I understand not doing it on every commit.

**Comment by atrauzzi** [comment]
The thing that's most important to me is that it happens quickly enough to be useful.  Right now, even though we have the option to do it from the kudu console, the speed makes it a non-option.

**Comment by alterx** [comment]
For the time being I think the best option is to keep a `package.json` file in the root folder and install every package from there. Those packages are available for every function.

For my use case this works.

**Comment by snobu** [comment]
Resurrecting this issue. For those developing straight into the portal editor a `npm install` button is really all that's needed right now. If you develop locally you most probably do it with source control, so Kudu takes care of `npm install` as deployment step. The Portal is what's making the whole `npm install` thing jarring, and it doesn't have to be. We actually need a dropdown to make to cover most practical cases: 

* npm init -y
* npm install
* npm install --save

Not sure how we can get a progress indicator for those actions since a `npm install` in Kudu isn't very verbose.

I agree the installation of dependencies should be uniform across supported languages, but for the time being, Node is really the one suffering from the Portal authoring experience.

**Comment by alexshyba** [comment]
+++ for adding a first class `npm install` for enhanced CD experience. npm is getting faster, so it should not be as big of an issue anymore. Running `npm install` manually is a bit of a pain...
Another suggestion: allow for using either `yarn` instead of `npm` (depending on the presence of `yarn.lock`.

**Comment by mm-gmbd** [comment]
+1 for this. I am standing up some Azure functions and doing this all through the Azure portal rather than through cli tools, so having this in the portal would be fantastic.

Any updates on progress? I.e. is this just in discussion phase? planned for development (i.e. in roadmap)? in development? in testing? I'm guessing it's the discussion phase based on the "needs-discussion" label, but just thought I'd ask in case the ticket is not totally up-to-date :wink:

**Comment by fabiocav** [comment]
This is not something we're currently tracking or planning to execute on. Closing to reflect that.
