### ISSUE TITLE
Function App Cold Starts Result in 404 or 503 error on Windows Consumption plan

### ISSUE THREAD

**Issue by mikecole** [Azure/azure-functions-host#7451]
I have created a handful of Azure Function apps in the portal, using the Windows Consumption plan, that provides HTTP trigger endpoints as an API to a SPA. I'm finding that when the function app cold starts that it intermittently returns 404 or 503 errors and my traffic isn't shown in function app logs. I'm seeing this globally across all of my Function apps.

#### Investigative information

Please provide the following:

- Function App version: 3.0.15733.0
- Invocation ID: 1b763988-4a46-404b-892c-de31a7be1817
- Region: Central US

#### Repro steps

Provide the steps required to reproduce the problem:

It's an intermittent issue, but during the day at certain times I receive the 404 or 503 responses when attempting to call an HTTP trigger from both a JavaScript app and through PostMan.

#### Expected behavior

I would expect to not get these intermittent errors.

#### Actual behavior

I would receive a 404 or 503 error, and after hitting the same endpoint a few times I'd eventually get a successful connection within a few seconds.

**Comment by v-bbalaiagar** [comment]
Hi @mikecole, Thank you for the details, We will check the logs to understand the error and revert back the findings.

**Comment by mikecole** [comment]
Thank you. Let me know if I can provide any more info.

**Comment by mikecole** [comment]
I put an uptime monitor on this same function:

![image](https://user-images.githubusercontent.com/1166315/121789551-94fedf00-cb9c-11eb-94ab-5f855eaae5ec.png)

**Comment by psyblade12** [comment]
I am also suffering from this problem. I am also using consumption plan but I am using Linux and is coding the function with Python.

This problem happened around 1-2 months ago. At that time, I just thought that because I am using free trial subcription, so the quality may not so good.

But now, after I have changed my account to PayAsYouGo, and is paying money for it, my application still suffers from this problem.

![image](https://user-images.githubusercontent.com/28593221/123627463-3f812e00-d83c-11eb-83a0-a11301b22c0c.png)

I expect Azure Functions should not return error 404 just after 3-4 seconds, it instead should hold the connection until the function is ready, and then return the result of the function.

**Comment by balag0** [comment]
@psyblade12 Since the issue could be different since this is a Linux app, could you please  open a new issue and tag me there?
Please include the app name using https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately#option-2
and approx.  timerange when the issue was happening if it is not failing currently.

**Comment by psyblade12** [comment]
> @psyblade12 Since the issue could be different since this is a Linux app, could you please open a new issue and tag me there?
> Please include the app name using https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately#option-2
> and approx. timerange when the issue was happening if it is not failing currently.

No problem, I will create a new issue, but as I am currently busy right now, I will open it in this weekend.
It is just that I may not know how to properly open an issue though.

I just checked some minutes ago and the problem is still there. It is quite irritating as the current only work around for this is to use the premium plan, which provides minimum dedicated node.... But if so, it is not so-called "serverless" anymore.

**Comment by v-bbalaiagar** [comment]
Hi @mikecole , Can we know if this is still persisting, we apologize for not following up frequently.
