### ISSUE TITLE
If a function key(s) become invalid, log the reason (if available) before regenerating new keys

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-host#7458]
Function keys can be invalidated for many reasons. When new keys need to be regenerated, log the reason why the previous ones became invalid. This is a common CRI question and this log entry will be very useful.

**Comment by Francisco-Gamino** [comment]
cc: @alrod

**Comment by fabiocav** [comment]
Do you have concrete examples of instances of key regeneration where the host would know what caused invalidation? Typically, this would occur if the host is sharing storage accounts with another instance with the same host ID (either explicitly defined or due to a collision), if the encryption keys are changed or something similar, but the host doesn't actually know that.

**Comment by Francisco-Gamino** [comment]
@fabiocav -- I had a sync with @alrod. You are correct, from the Functions Host point of view, it could not read the keys, and as a result, it regenerated new the keys. However, we think that we could improve the current Functions keys detector to analyze the logs and provide possible causes of regenerations. Please let me know if we can use this issue to improve on the current detector.

**Comment by fabiocav** [comment]
If the scope of the work is for the detectors only, we should probably be tracking that in the detector board (let me or Sonia know if you don't have that) and close this issue.

**Comment by Francisco-Gamino** [comment]
I've created a new entry in the Detector board to improve the current Functions keys detector. Closing issue.
