### ISSUE TITLE
Strange behaviour in EventHub triggered Functions since 2021-06-14T18:00:00Z

### ISSUE THREAD

**Issue by ijagberg** [Azure/azure-functions-host#7474]
Hi, we have noticed strange behaviour in many of our Azure Functions with EventHub triggers. At pretty much exactly the same time, they all suddenly decided to start executing way more often than before, for example going from around 4600 executions per minute to over 11000 executions per minute for the same amount of incoming messages. This has caused our apps to use vastly more CPU than before, and our auto-scaling AppService Plans have almost doubled in number of instances, so it is costing us a lot more money than usual to run our Functions. The fact that is seems to have happened at such a specific timestamp (same time for all affected apps) makes me think something was done to the Host, an update in scaling logic or something similar maybe? But since we have tried to pin the Host to an older version I am not sure that is the case.

#### Investigative information

- Timestamp: 2021-06-14T18:00:00Z
- Function App version: ~2 and ~3 (the same behaviour has appeared in both versions)
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region: West Europe

#### Expected behavior

We have not made any changes to any of these Function apps or EventHubs, so the expected behaviour is that the number of executions should stay relatively stable over time.

#### Actual behavior

Heres the amount of data coming in graphed out over the last two weeks:
![image](https://user-images.githubusercontent.com/4225887/122569257-d84cc800-d04a-11eb-8462-199c19e69c41.png)
The peaks are around 10m messages per hour, the valleys around 1.7m messages per hour.

Heres the Function Execution Count metric for one of our affected apps, during roughly the same period of time:
![image](https://user-images.githubusercontent.com/4225887/122569597-31b4f700-d04b-11eb-8d10-e5306fd7ac8b.png)
The stable data is around 230k executions per hour, and then after the problem appeared, the peaks are around 900k executions per hour.

Heres the same graph as above, zoomed in to the timestamp mentioned:
![image](https://user-images.githubusercontent.com/4225887/122569882-793b8300-d04b-11eb-8112-f05874d82b65.png)

#### Known workarounds

No known workaround, we have tried:
* Restarting the apps
* Pinning the host to a specific version

**Comment by v-anvari** [comment]
Hi @ijagberg , Could you please provide an invocation ID of the error, this will help us analyze the backend logs. Also, kindly check the memory dump to understand where the requests are coming from, a support ticket can help you find and analyze the memory dump as well.

**Comment by ijagberg** [comment]
How do I find an invocation ID for something like this? It's not one specific execution of one specific Function that is wrong, it's the number of executions suddenly happening after a specific timestamp. Do you want an arbitrary invocation ID so you can find out which Function app it is and where it is hosted? In that case, here is one for one of the affected apps: `8eed30d3-04d0-42e6-8b6a-639a9f0d1297`

**Comment by v-anvari** [comment]
Thank you for the details, yes this should work. I shall check the logs and update you the findings. Meanwhile, could you also explain us the repro steps.

**Comment by ijagberg** [comment]
I don't know how to reproduce this, since I don't know what is causing the issue, that's why I opened this issue. My assumption is that there has been an update by Microsoft to EventHubs/App Service Plans/Azure Functions Host. These are apps that we haven't touched in over a year, so the only changes that could have happened must be external to us. There are no shared dependencies among the affected Functions (they don't all depend on Redis cache or on some REST api), not all of the apps are hosted on the same App Service plan and not all of the apps read from the same EventHub, so it seems to me that is must be a service update somewhere in Azure that has caused this. But there are no ways for me (as far as I am aware) to find out what external updates have been made to our resources.

**Comment by v-anvari** [comment]
Hi @ijagberg , I have checked the data for the Time period - 14 June to 15 June . The web app iot-positions-stream-ruter-v1 is the main cause of high Memory across multiple instances during this time period. During periods of High Memory, iot-positions-stream-ruter-v1 is consuming an average of 54.94% of Physical Memory on instances consuming high Memory. 
If your app is performing slow or not responding at all, or if it consuming high memory, you can collect a memory dump to identify the root cause of the issue. The tool will collect a memory dump for your app and generate an analysis report.

Collect Memory Dump on app iot-positions-stream-ruter-v1 to identify why that app is consuming high memory.

Please follow these instructions to collect a memory dump.

_Go to App Service Diagnostics
Choose Diagnostic Tools .
Click on Collect Memory Dump tile and follow the instructions._

Kindly, let us know if you can find any information from the memory dump. Also, I require to understand the project scenario and steps that your functions are deployed as. Repro steps include, how the functions have been deployed, usage of different resources, and the process of your functions. This will help us understand what your functions are trying t achieve. Well, I understand that the functions are using event hub trigger, I also would like to know the bindings used, proxies used and etc.
