### ISSUE TITLE
Function stops in the middle of processing with no exceptions

### ISSUE THREAD

**Issue by mschoneman** [Azure/azure-functions-host#7479]
#### Investigative information

Please provide the following:

- Timestamp: `2021-06-21T07:26:16.4985863Z`
- Function App version: `azurefunctions: 3.0.15733.0`
- Invocation ID: `e7e092b7-2811-4174-af8c-3013b0bdb029`
- Region: `East US`

#### Repro steps

When load testing our app, multiple functions are stopping mid-execution without any errors being logged.

#### Expected behavior

Function should complete or an exception should be thrown.

#### Actual behavior

When load testing our app, multiple functions are stopping mid-execution without any errors being logged.

#### Known workarounds

None

#### Related information 

Provide any related information 

* Programming language used  `C#/ .NET Core 3.1`
* Bindings used
```
         public async Task RunAsync([ServiceBusTrigger("sbq-parse", Connection = "ServiceBusConnection")] string myQueueItem)
```

**Comment by v-bbalaiagar** [comment]
Hi @mschoneman, Thank you for reaching out to us, We will be checking the backend logs to try and find any errors and update you with the findings.

**Comment by mschoneman** [comment]
Appreciate it, if there's any more information you need, just let me know.

**Comment by v-bbalaiagar** [comment]
Hi @mschoneman, I went through the logs there is an error from worker channel. We would like to have more insights on the scenario to understand it better. Can you provide us your project file and all the packages and assemblies used so that we can investigate why the error has come from worker channel.

**Comment by mschoneman** [comment]
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <AzureFunctionsVersion>v3</AzureFunctionsVersion>
        <ProjectGuid>218BAF9F-4223-448E-85DB-10DBF5AE2EC0</ProjectGuid>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <DocumentationFile>DocumentParser.xml</DocumentationFile>
      <NoWarn>1701;1702;1591</NoWarn>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <DocumentationFile>DocumentParser.xml</DocumentationFile>
      <NoWarn>1701;1702;1591</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.1.0" />
        <PackageReference Include="Azure.Storage.Blobs" Version="12.8.0" />
        <PackageReference Include="DocumentFormat.OpenXml" Version="2.12.3" />
        <PackageReference Include="EFCore.BulkExtensions" Version="3.6.1" />
        <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
        <PackageReference Include="Microsoft.Azure.ServiceBus" Version="5.1.2" />
        <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.6.1" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.2.1" />
        <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="3.1.14" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="3.1.14" />
        <PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="3.1.14" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.14" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="3.1.14" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="3.1.14" />
        <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="3.1.14" />
        <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
        
        <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="5.0.3">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        
        <PackageReference Include="MimeTypeMapOfficial" Version="1.0.15" />
        <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.164">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="16.9.54">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
        <None Update="host.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="local.settings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <None Include="..\.editorconfig" Link=".editorconfig" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\Shared\Project.Database\Project.Database\Project.Database.csproj" />
      <ProjectReference Include="..\..\Shared\Project.Dataverse\Project.Dataverse\Project.Dataverse.csproj" />
    </ItemGroup>
</Project>
```

**Comment by mschoneman** [comment]
Here's the Project.Database.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.14">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="3.1.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.14">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```
and here's the Project.Dataverse.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="3.1.14" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.14" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="3.1.14" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.14" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="3.1.10" />
        <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />

        <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="5.0.3">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="16.8.51">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

    </ItemGroup>

</Project>
```

**Comment by mschoneman** [comment]
For what it's worth, here's another invocation that appears to get killed:

InvocationId == "1649bbc1-b039-47af-997e-7b77c5604d4b"
Timestamp == '2021-06-24T05:36:13.8742538Z'
East US

I don't see any exceptions 10 minutes before to 10 minutes after the last log entry I have in AppInsights.

**Comment by v-bbalaiagar** [comment]
Hi @mschoneman,  Thank you for the details, checking internally on this issue. We will update you with any information found.

**Comment by mschoneman** [comment]
Here are some more instances if it's helpful

timestamp [UTC] | InvocationId | operation_Id
-- | -- | --
2021-06-29T19:30:22.3913354Z | de944730-2e13-420b-a55f-f116e813d4d9 | 011fd2cdba1d6f49b4053b6d3d43f357
2021-06-29T19:35:23.8000967Z | 79b5e35a-cb4b-47fc-a74a-068221a93b8f | 3056143333fb484a866fdac8165cf11d
2021-06-29T19:40:23.6733855Z | f3f8709c-ee99-4f77-908f-738df4b41e0b | ecb933e300070e43b727bf5800b3086f
2021-06-29T19:35:12.1789721Z | 8f62c791-4811-4f0f-bd6e-e561b4c82ac0 | aad1552802e8d84e8a7fa40c66dbc025
2021-06-29T19:40:12.2158053Z | 570e8ae3-a9b5-466c-9eb0-086265ff3349 | a374127de3384f4cbee737391cb308e4

**Comment by mschoneman** [comment]
@v-bbalaiagar Any updates?

**Comment by v-anvari** [comment]
Hi @mschoneman , We apologize for the delay, Thank you for the all the details provided. We ran through the logs for the Time stamp between (2021-06-29 18:30:00) to (2021-06-29 20:00:00). Like you mentioned there are few invocations that did not complete the execution. We investigated few of them and commonly we see that few executions are taking longer than expected while the application is warming up. Also, during this timeframe your application process was restarted as application environment variables changed. This can most likely occur due to update in app settings or swap operation. This event occurred multiple times during the day.

We are seeing the warning during this Time frame - 	
_The site process was running on the instance. However the frontend did not send traffic to the site on this instance at that moment. This can most likely occur because the site was stopped or the app was getting warm-up on the new instance._

For one of such instances, At 19:30, the ServiceBusQueue was idle, after which the previous sample indicated the oldest message has been in the queue for 14.89 seconds, which is higher than the threshold of 1.5 seconds. 

When Pre-Warmed Instance is set to 0, function app will experience Cold Start. 

In the Azure Functions premium plan, we allow apps to reserve and run your app always warmed on a specific number of workers. This means if you have an app that may go from 0 events to 10,000 events at a moments notice, you could pre-warm 1 or many workers to always have that app ready to run. As the app scales out, it will first scale into the pre-warmed workers (and continue to buffer out to warm additional workers) so you can effectively avoid cold start. This also means for the Azure Functions premium plan we require at least one worker is running at all times the plan is active.

For more information regarding pre-warmed workers and how to configure it, you can go through the below links:
https://github.com/Azure/Azure-Functions/blob/main/functions-premium-plan/overview.md#pre-warmed-workers
https://michaelcandido.com/app-service-warm-up-demystified/

**Comment by bfinagraph** [comment]
@v-anvari

We are hitting a similar issue in consumption plan.  
The one main difference is that we are using Storage Queue triggers instead of service bus trigger.  Also, we are using North Central Region (if it helps).

Here's what we have observed so far
- Job Host starts at time T0
- 3 messages are processed (1 message ~about every 6 minutes)
- during processing of the 4th message (2 min into processing) the job host stops - with no exceptions or reason
- Overall time for the job host to restart seems to be around 20 min mark.

One recent instance where this happened:

Timestamp|Operation_Id|InvocationId|RoleInstance
-- | -- | -- | --
2021-07-12T20:26:39.7940426Z| 2a9bcc43209e784888b5e12278aaa5c4 | 09ed2778-97bb-410d-886e-6ba94cf0df3c|2fc7806220bc8814e5bb4b93959331f7c54ad37de569c80343d951533c6d602d
-- | -- | -- | --
 
Are there any special (undocumented) timeouts that a JobHost will be recycled every 20 minutes or something? Any information you could share will be helpful.

**Comment by v-anvari** [comment]
Hi @bfinagraph , This seems like an issue related to https://github.com/Azure/azure-functions-host/issues/7498. Can you open a new issue with all the mentioned details in the request form, so that we can investigate further
