### ISSUE TITLE
Function app return 404 on first call after long time of idle.

### ISSUE THREAD

**Issue by psyblade12** [Azure/azure-functions-host#7522]
I have a simple function that just connect to CosmosDB and return value. My code is written in python and I am using Linux consumption plan.

Region: Southeast Asia.

I don't have application insight enable so that I have no other information. If you need my function name, I will send it to you by personal message. Or please teach me other way to get the Function ID without application insight.

Steps to reproduce the issue:

1. Let Azure Functions be idle for a long time.
2. Call a function.

Actual behavior: Azure Function return 404 on the first calls, but the following calls are successful.
Expected behavior: Azure Function should hold the connection, waiting for the functions to be prepared. After that it should return the result.

![image](https://user-images.githubusercontent.com/28593221/124350921-a4b09700-dc21-11eb-8bd9-7b7258b841a1.png)

Other note: Even I called the function 7 times (2 failed and 5 successful), the Azure Function metric just shows that I called it 5 times.

![image](https://user-images.githubusercontent.com/28593221/124350941-b98d2a80-dc21-11eb-9d0a-8586583c8696.png)

Actually I think the problem is similar to https://github.com/Azure/azure-functions-host/issues/7451 , but balag0 at the page told me to make a separate page, so that I made it here.

**Comment by v-anvari** [comment]
Hi @psyblade12 , You can share us the invocation id, region name and the Time stamp of the error. This will help us find the App name.

**Comment by psyblade12** [comment]
> Hi @psyblade12 , You can share us the invocation id, region name and the Time stamp of the error. This will help us find the App name.

Hello. I have send an email to your email address (v-anvari@microsoft.com). 

In that email I gave you the function app name directly. It is just my test function so I think there is no problem with directly sharing the function app name.

I don't have application insight enable in my function app, so I have no way to get something like invocation ID though. I don't want to use Application Insight, as I used to be charged a lot by using Application Insight in Azure Functions, without knowing the reason why. The cost of Application Insight of that month is even 10 times higher than the cost of Azure Functions itself.

![image](https://user-images.githubusercontent.com/28593221/124497113-99599900-dde4-11eb-8bf1-0a385d32fc34.png)

**Comment by v-anvari** [comment]
Hi @psyblade12, Thank you for the details, I have checked the logs for the Time Frame - (2021-07-03 09:30:00) and (2021-07-03 10:30:00) and I see the below exception -

` Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: Failure Exception: KeyError: 'azure.functions' Stack:   File '/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py', line 482, in _handle__function_environment_reload_request     DependencyManager.reload_azure_google_namespace(   File '/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/utils/dependency.py'`

This issue is already identified in the recent past and has a fix scheduled for the next release.

Your type of scenario is explained in the below PR
https://github.com/Azure/azure-functions-python-worker/pull/854

Here is a workaround:
https://github.com/Azure/azure-functions-host/issues/7421#issuecomment-858863387

Let us know if the workaround helps in your scenario

**Comment by v-anvari** [comment]
Details for future investigation, if required:

FunctionInvocationId == "b8045717-424e-4e73-b1d3-4d811ca694f8"
Region: South East Asia
Time Stamp: 2021-07-03 09:43:15.4685915

**Comment by psyblade12** [comment]
> Hi @psyblade12, Thank you for the details, I have checked the logs for the Time Frame - (2021-07-03 09:30:00) and (2021-07-03 10:30:00) and I see the below exception -
> 
> ` Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: Failure Exception: KeyError: 'azure.functions' Stack: File '/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py', line 482, in _handle__function_environment_reload_request DependencyManager.reload_azure_google_namespace( File '/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/utils/dependency.py'`
> 
> This issue is already identified in the recent past and has a fix scheduled for the next release.
> 
> Your type of scenario is explained in the below PR
> [Azure/azure-functions-python-worker#854](https://github.com/Azure/azure-functions-python-worker/pull/854)
> 
> Here is a workaround:
> [#7421 (comment)](https://github.com/Azure/azure-functions-host/issues/7421#issuecomment-858863387)
> 
> Let us know if the workaround helps in your scenario

Thank you, but can you post a notice to this thread when the fix is out.
Currently I still suffer from this bug and don't no when the fix will be released to get things back to normal.

**Comment by v-anvari** [comment]
Hi @psyblade12 , You can subscribe to the PR Notifications in the right column of the PR
![image](https://user-images.githubusercontent.com/66122429/125314775-20ae8b80-e354-11eb-9636-f140ead8cdea.png)

Let me know if you don't have the option for that. If not, then I shall notify you here. 


You can also follow the work around provided here -  #7421. Otherwise, you will have to downgrade the version for now.

**Comment by psyblade12** [comment]
> Hi @psyblade12 , You can subscribe to the PR Notifications in the right column of the PR
> ![image](https://user-images.githubusercontent.com/66122429/125314775-20ae8b80-e354-11eb-9636-f140ead8cdea.png)
> 
> Let me know if you don't have the option for that. If not, then I shall notify you here.
> 
> You can also follow the work around provided here - #7421. Otherwise, you will have to downgrade the version for now.

Thank you I have subcribed to this 
Hope to see the fix soon.

**Comment by v-anvari** [comment]
Thank you for the confirmation, closing the issue here.
