### ISSUE TITLE
Function stops execution in the middle of processing when using Queue trigger

### ISSUE THREAD

**Issue by bfinagraph** [Azure/azure-functions-host#7542]
#### Investigative information

Please provide the following:

- Timestamp: 2021-07-12T20:26:39.7940426Z
- Function App version: ~3
- Invocation ID: 09ed2778-97bb-410d-886e-6ba94cf0df3c
- Region: North Central

#### Repro steps

Provide the steps required to reproduce the problem:
1. Job Host starts at time T0
2. 3 messages are processed (1 message ~about every 6 minutes)
during processing of the 4th message (2 min into processing) the job host stops - with no exceptions or reason
3. Overall time for the job host to restart seems to be around 20 min mark.

#### Expected behavior

The Job host does Not restart in the middle of execution or has additional context on why it was shutting down.

#### Actual behavior
The job host shuts down about ~20 minutes while execution is in progress [even though the function instance was running for barely few minutes]

#### Known workarounds

As an *experiment*, we switched to using Premium Plan  and that seems to keep the job host active for > 20 min.  .

#### Related information 

* Programming language used : .net Core 3.x
* Trigger used: Queue trigger

#### Related issues:
-  https://github.com/Azure/azure-functions-host/issues/7479
- https://github.com/Azure/azure-functions-host/issues/7498

**Comment by bfinagraph** [comment]
@v-anvari As recommended, tracking this as a new issue.

**Comment by v-anvari** [comment]
Hi @bfinagraph , Thank you for the details, will investigate it further and share the findings

**Comment by v-anvari** [comment]
Hi @bfinagraph , I have run through the logs and here is my analysis for the Time stamp (2021-07-12 19:45:00)  to (2021-07-13 09:45:00)

We detected a latency of 4 mins in one of your functions during (7/12/2021 8:19:20 PM - 7/12/2021 8:29:20 PM). The Queue was also idle for longer period. This app is using version 3.0.11.0 of the extension, which is older than the latest 4.0.4 version. Upgrading to the latest version of the extension may resolve performance and functional issues. 4.0.1 | Contains improvements to Queues Timeout Handling

The below logs explains the latency due to cold start. The below logs occur after the queue was idle was longer period of time. The poll frequency includes a backoff if the app is idle for an extended period of time or if there are issues connecting to storage. After which the App was in a steady state. Could you enable the scale controller logs to understand how it works. 

```

- Function app does not contain any active triggers. Creating a scale down activation task to ensure the app scales down or does not get assigned to a worker.
- The last sample indicated the oldest message has been in the queue for 20.59 seconds, which is higher than the threshold of 1.5 seconds.
- Ping request to http://10.66.56.74/admin/host/ping timed out after 10 seconds.

```

To prevent the issue of a cold start, you can either upgrade to the premium plan or you have a assign a timer trigger to keep the App working.  
https://azure.microsoft.com/en-us/blog/understanding-serverless-cold-start/

**Comment by v-anvari** [comment]
Further analysis:

At 2021-07-12 20:34:27.9416773, Message has reached MaxDequeueCount of 1. Moving message to queue 'sag*******uest-poison'. 

You can set MaxDequeueCount to 2 for it to retry the delivery attempts at least twice before it gets released to the poison queue

[Handling Poison Messages](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms703179(v=vs.85))
[maxDequeueCount](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue#hostjson-settings)
[QueuesOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.host.queuesoptions.maxdequeuecount?view=azure-dotnet-preview)
