### ISSUE TITLE
Durable function: delays between activity task being scheduled and being run

### ISSUE THREAD

**Issue by saint222** [Azure/azure-functions-host#7628]
Hello, Community!

**Description**

We are currently using Azure durable function with some activities within it. Almost all patterns are in use (chaining, fan-out/fan-in etc.). Our function is running on P1V3 service plan.
So, while testing we noticed that the delay between our activities can run up to 10-15 minutes (please, look at the attached screen shot) without any evident reason. At the same time each activity actually works for some seconds and then delays appear  (Application Insights doesn't track any dependencies during delays). It works like this: function is working => delay => function is working etc.

![image_2021_08_20T16_07_02_311Z](https://user-images.githubusercontent.com/44610915/130262137-6c0b2515-9763-4d8a-be21-da949486e628.png)

Our Host Json:

"durableTask": {
      "maxConcurrentActivityFunctions": 30,
      "maxConcurrentOrchestratorFunctions": 16,
      "storageProvider": {
        "partitionCount": 8,
        "maxQueuePollingInterval": "00:00:20"
      },

As you can see on the provided screen shot, each function is getting started for several times and has "IsReplay: false" status.

**Expected behavior**
The activity tasks should run one by one without delays.

**Actual behavior**
The activity tasks take 10-15 minutes before being run.

**App Details**
Durable Functions extension version: 2.5.1
Azure Functions runtime version: 2.0
Azure region: North Central US
Programming language used: c#

Any thoughts on it? Thanks!

**Comment by v-anvari** [comment]
Hi @saint222 , Thank you for reaching out to us.

Can we have the below details of your App so as to check the backend logs:
Function failed invocation id
Time stamp during the error

**Comment by saint222** [comment]
> Hi @saint222 , Thank you for reaching out to us.
> 
> Can we have the below details of your App so as to check the backend logs:
> Function failed invocation id
> Time stamp during the error

Here is the data you requested:

DurableFunctionsInstanceId	d6d36a5703d549a9ac8a88c3716cbb72
InvocationId	0c5bc717-a5d5-4936-b7bd-c6ae8616d772
Event time		2021-08-17T11:41:14.1580473Z

Activity #6
InvocationId	95903e3f-c8c1-436f-9556-0ebf051b87bb
Event time		2021-08-17T11:41:19.8164585Z

Activity #7
InvocationId	ec813ec3-a4b0-4512-a3c8-360f4fe67fd4
Event time		2021-08-17T11:51:39.793064Z

Activity #7
InvocationId	f7e8f6db-dfb0-425a-941b-de3507fd8aa2
Event time		2021-08-17T12:02:01.2291626Z

**Comment by v-anvari** [comment]
Thank you for the details, We shall go through the backend logs and update our findings

**Comment by v-anvari** [comment]
Hi @saint222 , I have gone through the logs and every time there is a delay in your traces, I see an event "ExecutedHttpRequest" taking place in your App. The [_ExecutedHttpRequest_](https://github.com/Azure/azure-functions-host/blob/2520fdb09fbaf7518925f8aaea618dd9b95de7ba/src/WebJobs.Script.WebHost/Middleware/SystemTraceMiddleware.cs#L40) log comes from the Functions runtime and isn't necessarily related to Durable Functions. Kindly, look at the Diagnose and Solve Problems blade in the Azure portal to get more insights about where this issue might be coming from. Apart from these events, I don't see any delays more than 1 sec in your App.

Meanwhile, to clarify the property "isReplay" in the traces. This property is not "isReplay=true" because this line is executed once. Whenever the Orchestrator await some call, it stops its own execution right there and waits for that call to finish. When it does, it runs through all the code up until its last point again - without making outbound calls again. Since there is no further await behind your last logging statement, this line is only reached once. Please find more context on it here - https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-diagnostics?tabs=csharp#debugging

The delay could be due to various reasons, one of which is explained here - https://github.com/Azure/azure-functions-durable-extension/issues/606#issuecomment-463029081

You can also add the property ["maxQueuePollingInterval](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-bindings?tabs=csharp#durable-functions-1x)": "00:00:30", in your host.json, this will explain the higher values can result in higher message processing latencies.

**Related information:**
https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#orchestrator-function-replay
https://github.com/Azure/azure-functions-durable-extension/issues/618
