### ISSUE TITLE
Azure Queue trigger is not triggering after being idle for sometime.

### ISSUE THREAD

**Issue by manojyamasani** [Azure/azure-functions-host#7753]
Hi, Iam using Azure Queue trigger as part of the chatbot application. Immediately after deployment queuetrigger works fine. But when it goes idle for a certain time and after that even though a new message is added to Azure Queue storage the queue trigger is not triggering. 
#### Investigative information

Please provide the following:

- Timestamp:
- Function App version: 3.2.0.0
- Function App name: Functions-Chatbot-AI-Side
- Function name(s) (as appropriate): ConversationStatechangeQueueTrigger
- Invocation ID: 341622bf-3eaf-4cca-8ad1-3d0dee6f2958
- Region: Central US

#### Repro steps
1. Pushing a message to Azure Queue storage will not trigger the queuetrigger. 
#### Expected behavior
After i push a message to queue storage queue trigger should be triggered and give the response. 
#### Actual behavior
When I push the message to queue storage Queue trigger is not triggered and response is not given. 
#### Related information 
* Programming language used  : C# (.NET Core)
* Links to source 
* Bindings used (Azure Table Storage)

```csharp
 public static class ConversationStatechangeQueueTrigger
    {
        private static HttpClient httpClient = new HttpClient();

        [FunctionName("ConversationStatechangeQueueTrigger")]
        public static async Task RunAsync(
       [QueueTrigger("conversationidqueue", Connection = "AzureWebJobsStorage")] string input,
       [Table("ConversationalStates", "ConversationalStatus", "{queueTrigger}")] tablerow row,
       ILogger log)
        {

            var json = JsonConvert.SerializeObject(row);
            var finalcontent = new StringContent(json, UnicodeEncoding.UTF8, "application/json");
            var response = await httpClient.PostAsync("https://webhook.site/0d24a886-7d9b-4707-8d52-b2b115b2e1bf", finalcontent);
        }
    }
```

**Comment by v-bbalaiagar** [comment]
Hi @manojyamasani, Thank you for your feedback!  We will check the logs to understand the cause and revert back the findings.

**Comment by v-bbalaiagar** [comment]
Hi @manojyamasani,  I went through the logs for the time stamp : 2021-10-08 00:00:00 to 2021-10-10 23:59:00. I see the error Singleton lock renewal failed for blob 'fun*****' with error code 409: LeaseIdMismatchWithLeaseOperation. Here is how you can troubleshoot the issue.
https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger#troubleshooting
Related information:
[azure-functions-host/issues/7025](https://github.com/Azure/azure-functions-host/issues/7025)
Azure/azure-webjobs-sdk-extensions#249
[azure-functions-host/issues/1864](https://github.com/Azure/azure-functions-host/issues/1864)

Also, we analyzed 6 Environment Variables Changed Events, 5 User Events.

Your application process was restarted as application environment variables changed. This can most likely occur due to update in app settings or swap operation. This event occurred multiple times during the day.
Check **View Activity Log** described in the **Troubleshooting and Next Steps**.

Around 10/9/2021 7:45:00 PM (UTC), your application process was restarted as the host.json or function.json was manually changed from Portal, Kudu, FTP or via App Service Editor. It will restart the Function App host in order for the new values to be loaded.
If you have Application Insights, you can check if your Function App was restarted due to modifying files used by your functions using the following query:
traces
| where message == "Host configuration has changed. Signaling restart" or message contains "File change of type 'Changed' detected"
| order by timestamp desc


Alternatively, follow the instructions below.

1. Navigate to the application in the Azure Portal.
2. In the left hand side menu click on **Activity Log**.



Go to **App Service Diagnostics**

Please check and let us know if this helps.
