### ISSUE TITLE
Consumption Plan - Azure Service Bus Trigger: JobHost stops after inactivity and does not wake back up when new messages arrive

### ISSUE THREAD

**Issue by gma2222** [Azure/azure-functions-host#7762]
#### Check for a solution in the Azure portal
Went through all the diagnostic steps in the Azure portal

#### Description
Running a Function App on a Consumption plan where one of the functions uses a Service Bus Trigger. If no messages arrive on the queue for a period of time, the Job Host shuts down and my function stops running (as expected in a Consumption plan function app). 
However, once this happens, my function never "wakes back up" no matter how many new messages get placed on the service bus queue. I've learned from other issues similar to this that navigating to the function app in Azure portal manually kicks off an instance of the function, so that's been a workaround, but not a viable solution moving forward.

#### Investigative information

- Timestamp: 2021-10-12T15:37:38.189742Z
- Function App version: v3
- Invocation ID: b22bfe99-6a04-49c9-b315-c3f2ad0baf30
- Region: East US 2

Note that the above invocation executed after 12+ hours of not running despite there being messages on the queue during that time, and only started after I navigated to the function app in the portal

#### Repro steps

1. Don't run or access the function app for approximately 20 minutes (i.e. until Job Host stops).
2. Send message(s) to the connected service bus queue.

#### Expected behavior

- After step 2, I expect (after however long the "cold-start" takes) for the Job Host to start back up and for my function to start processing messages off the queue

#### Actual behavior

- After step 2, the Job Host stays asleep until I access the resource in the portal manually.

#### Known workarounds

- Navigating to the function app in the portal
- Unconfirmed by me, but users in other issues suggest creating a timer function to essentially keep the function app 'always on' (I don't want to do that; I would like to utilize the Consumption plan as intended)

#### Related information 

What I've tried:
Looked at many other issues similar to/the same as this, some of which include:
  - https://github.com/Azure/Azure-Functions/issues/1254
  - https://github.com/Azure/Azure-Functions/issues/229
  - https://github.com/Azure/Azure-Functions/issues/370
  - https://github.com/Azure/azure-functions-host/issues/6917

Tried all the methods discussed in there 
- I've confirmed that my triggers are synced and I am using WebDeploy
- Tried tinkering with SAS policies, giving 'Manage' rights
- Changed my ServiceBus connection string app setting name to `AzureWebJobsServiceBus`
- Hard-coding the queue name in the function signature (rather than getting it from app setting)

Have functions with ServiceBusTrigger, HttpTrigger, OrchestrationTrigger, & ActivityTrigger in my function app
All written in C#

**Comment by RARomano** [comment]
That happened with my as well, but with the early access .net 6 and function host ~4

**Comment by v-anvari** [comment]
Thank you for reaching out to us,  We will investigate this further and update you with the findings.

**Comment by svilenstefanov** [comment]
I can confirm this happens for me as well. Function app using consumption plan using ServiceBus trigger.

**Comment by v-anvari** [comment]
Hi @gma2222 , I have gone through the logs, and I see that you have been using the premium plan. I do see a 12 plus hour gap between two running functions. Can you confirm if you were using RunOnStartup at this time period (which is disabled now). Though, not fully recomended for production - This property allows the runtime to start when the function app wakes up after going idle due to inactivity and when the function app restarts due to function changes, and when the function app scales out. Otherwise, this needs to be done manually.

![image](https://user-images.githubusercontent.com/66122429/138904710-65ca4afb-1d76-49cc-81b6-740d4553f3bf.png)

I see 2 errors popping up during this 12 hours gap, 
1. The managed identity that you are using here - AzureWebJobsServiceBus , isn't configured properly, hence the connection string is not retrieved properly. 
![image](https://user-images.githubusercontent.com/66122429/138905091-135e7c8c-fb3b-43a7-8f42-914ea72d5c5c.png)
```

Full Exception :
 Error parsing the specific connection string in ConnectionConfiguration. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Azure.AppService.ScaleController.Extension.ClientProviders.External.ConnectionConfiguration.TryInitializeFromConnectionString(String connectionString)
```

2. The system requested for a restart - 
![image](https://user-images.githubusercontent.com/66122429/138905263-3af085a0-14b5-4270-813f-020de134e626.png)

Also, I do not see any messages during this period, since the Application was clearly offline during this period. This could be because of the restart requirement. The environment variables change, must have broken the other functions to process their requests. 

Cold start should not be affecting your App, as the you have the prewarmed instance is setup. 

For a consumption app, it is likely to have longer cold starts and this can be prevented by having a timer trigger. But, nevertheless it needs to wake up with a new request.

**Comment by svilenstefanov** [comment]
> I can confirm this happens for me as well. Function app using consumption plan using ServiceBus trigger.

For me the problem was resolved when hardcoded the topic name and subscription name in the code rather than getting those from the config. Hope that would help someone.

**Comment by ThoughtHopper** [comment]
Same issue here, Service Bus with Consumption plan. Messages were not consumed until I manually went in to Azure to troubleshoot. (Suggested Workaround in OP)

Will take a look at the other links and such.
