### ISSUE TITLE
Why Must "Always On" Be Enabled For Timer Triggered Functions?

### ISSUE THREAD

**Issue by DrakeLambert** [Azure/azure-functions-host#8021]
My team has been working on a timer triggered v3 function app for the past few months. It's set to go off every twelve hours, `0 0 */12 * * *`. It's a C# function running on an app service plan. Here's an invocation id: `42c60c3c-9230-45e1-8c17-901dfdc5f317`.

For the longest time, we were only able to get it to trigger every 24 hours. Recently, It didn't trigger for nearly an entire week. Here's a graph of executions:

![image](https://user-images.githubusercontent.com/17054016/147701679-0d2192d7-564c-43b2-8c36-f757fbd64c44.png)

I read [this wiki page](https://github.com/Azure/azure-functions-host/wiki/Investigating-and-reporting-issues-with-timer-triggered-functions-not-firing) which recommends having "Always On" enabled. I found that we had that setting turned off, so I've switched it on. I'll wait to see if that helps.

My question is the title. I'd be happy to hear other thoughts on why we've observed this issue with the timer trigger!

**Comment by v-bbalaiagar** [comment]
Hi @DrakeLambert , Thank you for your feedback!
Apps that run in Classic mode require 'Always On' to be enabled. 
There are two plans that Functions apps can run in: Dynamic and Classic. You choose the plan during app creation.

**Classic Plans** run on App Service plans just like other App Service apps. You can choose from Free, Basic, Standard, etc. and you control the scale yourself. If you are using a Classic Plan, you must turn on 'Always On' in order to have triggers fire reliably. This requires your site to be in Basic or Standard mode. You can manage this from your Function App (and check for 'Always On') by clicking 'Function app settings' -> 'Go to App Service Settings'. The 'Always On' setting lives in 'Application settings'.

**Dynamic Plans** are charged by execution. There's no concept of 'Always On' -- when a trigger fires, your site will be started (if it's not already) and your function will run.

Please check here for more details: https://azure.microsoft.com/en-us/documentation/articles/functions-scale/#choose-a-service-plan

**Comment by DrakeLambert** [comment]
I appreciate your response, but I'm still a bit lost.

> ... you must turn on 'Always On' in order to have triggers fire reliably.

Can you explain why this is? I'm trying to understand why my timer function would **completely fail** to start when "Always On" is disabled rather than only having a **delayed** start.

**Comment by balag0** [comment]
delayed start vs complete failure depends on the type of the trigger.
if it is a http triggered app the http request itself works as the trigger to wake up the app if it had idled out. this will lead to delayed start.
For other trigger types (ex: timer trigger) there is no explicit external trigger to awaken the app. in dynamic skus the trigger is a platform component called scale controller. since this component is not available in dedicated sku, there is no one to wake the app (leading to missed executions) and we instead rely on not letting the app ever going idle by setting alwayson.
