### ISSUE TITLE
Scalability issue: Very limited aggregate network bandwith for consumption plan?

### ISSUE THREAD

**Issue by casper-79** [Azure/azure-functions-host#8103]
Hi

We are developing an analytics application in Java on Azure functions consumption plan. Unfortunately, we have run into a scalability issue and we would really appreciate rapid input on how to resolve it.

I have made a simple http triggered consumption plan Azure function, which illustrates the essence of the problem we are facing. On each invocation it simply uploads 20 MB of randomly generated bytes to blob under a random UUID filename and downloads it again. No data is transferred in/out of the app, we are focusing solely on quantifying the bandwith to premium block blob storage. For putting load on the app I have made test code, which produces a given number of concurrent request to the function. Under a given constant workload I wait for the function app to stabilise in terms of scale-out and then inspect the aggregate ingress and egress throughput metrics of the storage account.

For 1 concurrent request both ingress and egress stabilises around 0.25 GB/minute=4 MB/s
For 10 concurrent requests both ingress and egress stabilises around 1.3 GB/minute=22 MB/s
For 100 concurrent requests both ingress and egress stabilises around 6.5 GB/minute=108 MB/s
For 200 concurrent requests both ingress and egress stabilises around 7.5 GB/minute=125 MB/s

Clearly the aggregate bandwith to blob for the entire function app is capped at somewhere around the 125 MB/s mark, which seems suspiciously close to the maximum of a single 1 gbit link. This is not at all what we had expected, since the individual function invocations are running on a large number of different hosts as evident from application insights. Any advice for overcoming this barrier will be greatly appreciated - further details on the app follow below.

Linux host Azure function running java code on consumption plan in region West Europe
Premium blob storage in same resource group and region
Azure-storage 8.6.5 blob client library

**Comment by casper-79** [comment]
Hi @surgupta-msft. Any suggestions on how to work around this issue or information on the architecture of the underlying infrastructure? We are working completely in the blind trying to find a workaround ...

Since I created the issue we have done some further investigations, but unfortunately it has not resulted in any improvement:

We have deployed to france-central and observed the same behaviour as in west-europe
We have disabled Java DNS caching without observing any difference
We have upgraded to Azure-storage 8.6.6 and experimented with different request options (eg. concurrent requests, blob block size, disable MD5 checksumming etc)

Cheers,

Casper

**Comment by casper-79** [comment]
Another update. We have looked at realtime metrics in Application Insights which shows our workload is distributed on 50 servers, when running at a sustained workload of 200 concurrent requests. In other words each server is handling 4 concurrent requests on average. Inside the function code we log the transfer rate of each upload/download operation and we are frequently seeing numbers as low as 0.5 MB/s.

**Comment by surgupta-msft** [comment]
@casper-79  Thanks for reaching out. We are discussing this issue internally in our team. I will get back to you as soon as I have more information on it.

**Comment by balag0** [comment]
@casper-79 Could you share the appname and approx time range when the test was run please
(You can use https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately if required)

**Comment by casper-79** [comment]
@balag0 

Appname is dev-1229-3236-datarepository in france-central. It transfers data into the container data-repository on storage account lar53b7zp5xbo. I did a test with 200 concurrent requests this morning 9:40-10:00 CET. If there is anything else you need please let me know ..

Cheers,

Casper

**Comment by balag0** [comment]
@casper-79 Thanks for the additional details. Hopefully the following details are helpful.

During the test on 02/04 the function app had 36 instances assigned in the backend. The bandwidth limits dont apply at the function app level. The limits are at the node level and there could be other instances from other subscriptions running on the same node since it is a multi-tenant service. These 36 instances were fairly distributed across different nodes. This could be both good and bad as these bandwidth intensive instances are not all on the same node, but this also means there is more chances of noisy neighbors.

The number of workers and limit per node are not documented as there are too many factors involved. But it does seem like the bandwidth you observed does appears less than what is generally expected. 
Unfortunately, it is difficult to know where the bottleneck is (it is not because the function app is being throttled)

For next steps, I recommend isolating the different dependencies like Storage and see if that changes anything. (May be there are configs on the storage account that impacts throughput for example)

In general, functions are not suited for this type of bandwidth intensive workloads due to the reasons listed above which you would have no control over. Also, network usage is not a metric used in making scale decisions, so even if the app would benefit from more instances there is no guarantee it will provided. So, looking into using Azure dedicated host could be an option as well.

**Comment by casper-79** [comment]
Hi

We have worked further on the issue and found the source of the problem to be the blob client in azure-storage SDK. We changed the code to use azure-storage-blob instead and numbers are now consistently up by an order of magnitude. We also found that queue triggered functions are much more suitable for this type of workload, since you can control maxConcurrentCalls in host.json. By combining these two tweaks we are seeing perfect scaling and high aggregate bandwidth (3000+ MB/s).

I would suggest this performance issue is somehow addressed or documented in the azure-storage SDK, but apart from that the issue is closed on our side.

**Comment by v-bbalaiagar** [comment]
Hi @balag0 , Since its a document related issue. Can we add this in our documents and if its a valid note, then can we transfer this issue to the docs repo.

**Comment by balag0** [comment]
@casper-79 Thanks for the update.
@v-bbalaiagar We usually don't document behavior of client libraries not owned by functions as we have no way to know if something changes later on.
