### ISSUE TITLE
Managed identity support for WEBSITE_CONTENTAZUREFILECONNECTIONSTRING setting

### ISSUE THREAD

**Issue by damiangelis** [Azure/azure-functions-host#8135]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 

All

#### Question

I have a function app running on Windows. I managed to replace `AzureWebJobsStorage` setting with `AzureWebJobsStorage__accountName`, which contains the Storage account name instead of connection string. Function app works and so does deployment via Azure Pipelines.

I wonder if I can get rid of connection string in `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` setting as well. Do you plan to support something like `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING__ACCOUNTNAME` for function apps under Windows (*)?

(*) I understand function apps under Linux do not require this setting.

My current settings look like this:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/682920/153440622-bc039bc9-9c0d-4ac5-9fc3-275994ff5941.png">

According to [Docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#website_contentazurefileconnectionstring), `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING__ACCOUNTNAME` setting is mandatory for Windows:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/682920/153443953-febc04dc-7452-4de3-9a9f-72d40798f7dc.png">

Related issue: https://github.com/Azure/azure-functions-host/issues/6423

## Updates on 2/15/2022:

We were able to provision function apps without neither `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` nor `WEBSITE_CONTENTSHARE` settings. However, the following warning message started to appear in those resources:

![image](https://user-images.githubusercontent.com/682920/154145832-6ee543e1-a00f-4c06-bdb2-8441a75a1416.png)

That warning pointed us to a [doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-recover-storage-account#storage-account-application-settings-were-deleted) which states that those WEBSITE settings are mandatory for Premium plans:

![image](https://user-images.githubusercontent.com/682920/154145855-70ddd9ef-a6c8-43fe-b0e3-c73268fa19c1.png)

Then we tried to have at least the MSI-related `AzureWebJobsStorage__accountName` in place, but it didn’t work either, sounding like WEBSITE settings can’t go away:

![image](https://user-images.githubusercontent.com/682920/154145868-bcfabc18-20e9-49ab-b25b-09380fd781b1.png)

**Comment by damiangelis** [comment]
FYI @spmanjunath

**Comment by damiangelis** [comment]
FYI @jesperkristensen

**Comment by v-bbalaiagar** [comment]
Hi @damiangelis , Thank you for your feedback! We will investigate this further and update you with the findings.

**Comment by damiangelis** [comment]
Added today’s updates to issue description.

**Comment by mattchenderson** [comment]
Azure Files does not support using AAD identities for SMB mounting. As such, a connection string is required by that service. Our recommendation is to store the secret in Key Vault and reference it with an identity as you have shown in that first screenshot.

**Comment by dnblankedelman** [comment]
@mattchenderson Thanks for the speedy reply. We are not using SMB mounting or Azure File store, just blog storage which [this announcement](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob#storage-extension-5x-and-higher) seems to imply should work without secrets.

**Comment by mattchenderson** [comment]
This issue refers to `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING ` which is for Azure Files mounting at the platform layer. Triggers and bindings can use identities in the latest extension versions, but they should not be making use of the Azure Files configuration.

**Comment by mattchenderson** [comment]
Ignoring the Azure Files connection, I don't see anything other the `AzureWebJobsStorage__accountName` setting in your configuration. If that is being used for a blob trigger, I would expect you to see runtime errors during application startup. The error you referenced at the end of the original post is slightly different than what I'd expect, but that signals part of the issue to me.

`__accountName` is only applicable to host storage. It cannot be used for the extensions. You should instead set `AzureWebJobsStorage__blobServiceUri` and `AzureWebJobsStorage__queueServiceUri`. That would satisfy host storage and your blob trigger (I'm assuming trigger since the error showed queues, and that would not be needed for input or output bindings). Another option is to have your trigger use a new connection with those properties (not reuse AzureWebJobsStorage)

A critical piece of information missing here is what role assignments are in place. The docs at the time of this comment are incorrect, but for reference: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=csharp#grant-permission-to-the-identity. You would need what is captured there ([Storage Blob Data Owner](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-owner) and [Storage Queue Data Contributor](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-queue-data-contributor, for both AzureWebJobsStorage and whatever your trigger uses), but the thing they are missing is that you also need [Storage Account Contributor](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-account-contributor) over the account used for AzureWebJobsStorage specifically (regardless of the connection configured for the trigger). I'm hoping to get these docs updated soon.

**Comment by damiangelis** [comment]
Hi @mattchenderson, thanks for all your help.

Fortunately we managed to get rid of connection strings with account key by:
1. Deleting function app resource in Portal
1. Deleting both `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING`, `WEBSITE_CONTENTSHARE`, and `AzureWebJobsStorage` settings in ARM template
1. Adding `AzureWebJobsStorage__blobServiceUri` and `AzureWebJobsStorage__queueServiceUri` settings into ARM template
1. Re-provision function app
1. Setting up these role assignments in Storage account access control (IAM) for the function app:
   - Storage Blob Data Owner
   - Storage Queue Data Reader
   - Storage Queue Data Message Processor
   - Storage Queue Data Contributor
   - Storage Queue Data Message Sender

Note: We only have timer-triggered and queue-triggered functions in the function app.

Settings:
<img width="290" alt="image" src="https://user-images.githubusercontent.com/682920/154511099-030bba2a-033a-438b-815d-35f66abfaa72.png">

Message below still shows up, however. If function app really won’t have any scaling issues, this should be fixed at some point to stop being displayed.

![image](https://user-images.githubusercontent.com/682920/154511194-5482896a-51fb-4836-a376-4e9250d52657.png)

**Comment by mattchenderson** [comment]
I'm glad you have things working! Apologies for overfocusing on BlobTrigger - it's where I've seen the most issue with getting started. But your setup otherwise seems fine to me - did you find that you actually needed all 4 queue role assignments? That does seem a little excessive to me.

That warning there is the result of you removing the Azure Files settings. Consumption apps are generally recommended to use Azure Files for better scalability. We show that warning for all consumption apps which do not have Azure Files configured. It is possible that scaling for the app would be limited.

**Comment by damiangelis** [comment]
@mattchenderson I added those 4 queue role assignments just in case. Regarding scaling, we’re under Premium plan, not Consumption, so I don’t see we’re going to run into any issues.

**Comment by dnblankedelman** [comment]
(and just in case you are curious why we are under Premium... it is our understanding that one has to be in Premium to satisfy the [network isolation requirements](https://eng.ms/docs/security-compliance-identity-and-management-scim/security/azure-security/security-health-analytics/network-isolation/tsgs/troubleshooting/azurepolicyandprivatelinks/privateendpoint) coming to all services, Consumption doesn't support the necessary networking setup)

**Comment by mattchenderson** [comment]
So if it's Premium, I am a little surprised to see that warning come up. But yes, you should be fine, then.

**Comment by jesperkristensen** [comment]
Is there a description of what scaling issues there might be for consumption apps, and is it planned to fix that?

**Comment by mattchenderson** [comment]
> So if it's Premium, I am a little surprised to see that warning come up. But yes, you should be fine, then.

A recent discussion pointed back at this thread with some confusion versus the docs for the setting. The docs are the authority here, and I think the best treatment we currently have at time of this comment is https://learn.microsoft.com/en-us/azure/azure-functions/storage-considerations?tabs=azure-cli#create-an-app-without-azure-files. That is missing a few details and has a confusing error in it, but we will work on getting those resolved.

One important distinction to make here is between the Premium plan as in [Premium SKU of a dedicated plan](https://learn.microsoft.com/en-us/azure/azure-functions/dedicated-plan) and the [Elastic Premium plan](https://learn.microsoft.com/en-us/azure/azure-functions/functions-premium-plan?tabs=portal). I can't recall my thinking in writing that comment 1.5 years ago, but it's possible I assumed this referring to a dedicated plan, in which case Azure Files would not be needed. However, an Elastic Premium app _would_ need to consider scaling impact. If not using Azure Files, run-from-package or a container-based deployment would need to be in place to ensure you do not possibly hit some limits. 

Again, we'll work on getting the docs updated to present this all more clearly. Apologies for any confusion.
