### ISSUE TITLE
Method not found when invoking Azure.Storage.Blob dynamically

### ISSUE THREAD

**Issue by eddynaka** [Azure/azure-functions-host#8155]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app, select `Diagnose and solve problems` from the left, and view relevant dashboards before opening your issue.

#### Investigative information

Please provide the following:

- Timestamp: 2/18/2022, 10:32:09.120 PM
- Function App version: v3 or v4
- Function App name: 1esnightlyscan-api
- Function name(s) (as appropriate):
- Invocation ID:
- Region: West US2

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a function that has a dependency dll dependency and is being loaded dynamically
2. This dll dependency uses Azure.Storage.Blob (latest version)
3. Invoke the function that uses the Azure.Storage.Blob

#### Expected behavior

1. Create a function that has a dependency dll dependency and is being loaded dynamically
2. This dll dependency uses Azure.Storage.Blob (latest version)
3. Invoke the function that uses the Azure.Storage.Blob
4. No exceptions thrown

#### Actual behavior

1. Create a function that has a dependency dll dependency and is being loaded dynamically
2. This dll dependency uses Azure.Storage.Blob (latest version)
3. Invoke the function that uses the Azure.Storage.Blob
4. It will throw an exception:
```
Method not found: 'Azure.Response`1<Azure.Storage.Blobs.Models.BlobServiceProperties> Azure.Storage.Blobs.BlobServiceClient.GetProperties(System.Threading.CancellationToken)'.
```

#### Known workarounds

No workarounds so far

### Related information 

Provide any related information 

* Programming language used: C#

**Comment by v-bbalaiagar** [comment]
Hi @eddynaka , Thank you for your feedback! I went through the logs for the time stamp : 2022-02-18 10:00:00 PM to 2022-02-18 10:30:00 PM. 

Your Function app is pinned to extension bundle version 2.8.3, but the latest version for v2 is version 2.8.4. 

Around 2/18/2022 10:40:00 PM (UTC), your application process was restarted as the host.json or function.json was manually changed from Portal, Kudu, FTP or via App Service Editor. It will restart the Function App host in order for the new values to be loaded.
If you have Application Insights, you can check if your Function App was restarted due to modifying files used by your functions using the following query:
traces
| where message == "Host configuration has changed. Signaling restart" or message contains "File change of type 'Changed' detected"
| order by timestamp desc

Also, host runtime instance (Dynamic Plan) was not available for a long time period (> 15 minutes).
Function App was offline due to previous deployment. Please restart the Function site manually or redeploy the function site to get the issue mitigated.
Please visit [Azure App Service Deploy task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops) for more information.

Please check and let us know if this helps.

**Comment by eddynaka** [comment]
Hi @v-bbalaiagar ,

In the end, I had to move from a normal AzureFunction v3 to the isolated process v4.
Thanks again for the attention.

You can close this :).

**Comment by v-bbalaiagar** [comment]
Thank you for the update. Closing this issue, please feel free to reach back to us in case of any further queries related to this issue.
