### ISSUE TITLE
Do not auto-ignore local.settings.json from Git.

### ISSUE THREAD

**Issue by Sergey-Nosov-CloudFit** [Azure/azure-functions-host#8179]
I feel `local.settings.json` should remain for local non-Azure settings only, as there is big difference between running locally in an emulator and running in an actual Azure environment.

I think, however, `local.settings.json` should _not_ be auto-ignored form Git.

When a new developer comes on-board and pulls a function app project, they cannot run it locally as the `local.settings.json` is missing.

Thank you

See also:
https://github.com/Azure/azure-functions-host/issues/1594
https://github.com/Azure/azure-functions-host/issues/3189

**Comment by springcomp** [comment]
I feel strongly against this. 
The default behaviour to auto ignore is to protect you from your own mistakes and prevent leaking secrets into the Git repository.

Just create a sample `local.settings.sample.json` file that you store in Git and your’re good to go.

**Comment by Sergey-Nosov-CloudFit** [comment]
`local.settings.json` is a wrong place to store secrets, that is what `secrets.json` is for (right click application, Manage User Secrets).

Here is a typical `local.settings.json`; no secrets there:
```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"
  },
  "Host": {
    "CORS": "*"
  }
}
````

**Comment by springcomp** [comment]
Well, I would argue that `AzureWebJobsStorage` **is** a secret...

**Comment by v-bbalaiagar** [comment]
Tagging @ahmelsayed / @paulbatum , for more inputs

**Comment by paulbatum** [comment]
My guess is that this would be a fairly dangerous change due to a large user base that is used to storing local development secrets in `local.settings.json`. Support for IDE managed secrets (such as the VS feature you mentioned) is relatively new and is not universally present across different development environments. 

There is a straightforward workaround/fix for teams that have well established practices of keeping `local.settings.json` free of secrets - update .gitignore and commit the file.
