### ISSUE TITLE
Key vault configuration references no longer updating on function app restart

### ISSUE THREAD

**Issue by John-Bosch** [Azure/azure-functions-host#8269]
I use logic apps to manage the automatic rotation of some Service Bus access keys, which are then stored in a Key Vault. Several Azure Functions have key vault links in their configuration to the secrets. The logic app uses the Azure Management REST API to perform a "restart" operation on the Azure Function to trigger a re-read of the configuration when the keys are rotated. 

While all of our functions were on consumption plans, this work like a charm. The restart was executed with the softRestart flag and on restarting the new service bus keys were picked up and the functions continued on as if nothing had changed.

However, I recently moved all of our functions to a standard app service plan with a VNET and NAT so that we could use a consistent outbound IP address as we have a number of firewalls to penetrate. I am reasonably certain that since that move the picking up of the new key vault secret values on app restart has been failing (I am certain it's failing, I am just not sure if it's related to the app service plan change or not).

In the screen shot below, you can see multiple successful "Restart Web App" requests being triggered by our key rotation logic app. While these requests appear to succeed (more on this in a moment), the new secret values are NOT read and the queueing of messages to service bus begin failing with authentication errors. However, if I manually edit the application's configuration simply by going to the "Advanced Edit" screen, hitting ok (with no changes), then saving the Function App's configuration it triggers the "Update website" events which DO trigger a re-reading of the key vault secret values and the function apps start sending messages to the queues correctly again.
 
![image](https://user-images.githubusercontent.com/5135377/160305007-5f87efb7-2691-4310-8300-4302a63fd52d.png)

As a side note, the two "Restart Web App" events that failed have the "softRestart" flag on the restart event set to true. They failed with an "There was an unexpected InternalServerError" error. Only by removing this flag can I now get the restart call to succeed at all. It used to work fine but stopped doing so around the time I changed the app service plan.

Timestamp: Mon Mar 28 2022 06:15:12 GMT+1100
App version: V3
App Name: ndss-dev-integration-fa-d365-api-poll
Region: Australia East

**Comment by v-bbalaiagar** [comment]
Hi @John-Bosch , Thank you for your feedback! We will try to get the logs and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @John-Bosch ,  I went through the logs for the time stamp - 2022-03-28 00:00:00 to 2022-03-28 23:59:00. We detected that Host Runtime instance (Dedicated Plan) was not available for a long time period (> 15 minutes). 
Function was running on 0 worker instance for more than 550 minutes between 3/28/2022 9:55:00 AM and 3/28/2022 7:10:00 PM.
**Possible cause** :  
Function App was offline due to previous deployment
Please restart the Function site manually or redeploy the function site to get the issue mitigated.

Always On is not enabled so the function site could be stopped permanently while it being idle for sometime.
Please visit [Always On for Dedicated Hosting plans for Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/dedicated-plan#always-on) for more information.

Function site worker runtime was not started successfully then
Restart the function site or Scale Up and Scale Down to force the function site runtime being started on a new worker instance
Please visit [Scale up an app in Azure App Service](https://docs.microsoft.com/en-us/azure/app-service/manage-scale-up) for more information.

Also, We detected that **Socket handles leaked.**
Applications running on the following instances: dw0SmallDedicatedWebWorkerRole_IN_2702 [dw0sdwk000232] are probably leaking socket handles because the actual TCP connections on the machine are not high. During this period, the process w3wp.exe of site ndss-dev-integration-fa-d365-communications with Process Id 16944 had the maximum open handle count of 1853.
Please Note - This message alone may or may not mean TCP connection exhaustion. Socket handles will be leaked when your app is not closing connections gracefully or opening too many connections. You can collect a memory dump to identify the handles that are not closed. 
For ASP.NET applications, you can use the PrintConnectionSummary.aspx page from Investigating Socket exception for ASP.NET applications in Azure App Service article to identify the host names for sockets that are leaked the most. You need to copy this page to your app and wait for the issue to happen again to identify the connections to the host names.

### Modify application code to avoid SNAT issues.

SNAT port exhaustion is usually a result of when the application is not reusing existing connections.
**Creating an outbound connection per request is bad practice and can lead to snat port exhaustion, especially if the backend is responding slow**. Please check if the application code is following best practices and using connection pooling.

Most of the libraries support connection pooling so there shouldn't ideally be a need to create a new outbound connection per request.

For C# applications, ensure that the `HttpClient` object is created once and resued again. 
For ADO.NET connections, make sure database connection pooling is used. You may restart the web app in order to reset this limit.

It is recommended to pursue a long term and stable fix by following connection pooling best practices.

+ [Manage connections in Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/manage-connections)
+ [Improper Instantiation antipattern (Code sample included)](https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/#how-to-fix-the-problem)
+ [Call a Web API From a .NET Client (C#)](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client) 
+ [SQL Server Connection Pooling (ADO.NET)](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-connection-pooling)
+ [Modify the application to use connection pooling](https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-intermittent-outbound-connection-errors#modify-the-application-to-use-connection-pooling)

#### Pros:
+ Refactoring the code can lead to overall improved application stability, reliability and efficiency.
+ The application may be able to support higher load post code refactoring.
+ No additional associated cost.

#### Cons:
+ May need time to refactor the code and can be a significant investment.


Go to [App Service Diagnostics](https://portal.azure.com/?websitesextension_ext=asd.featurePath%3Ddetectors%2Ftcpconnections#@microsoft.onmicrosoft.com/resource/subscriptions/620192e5-c9a4-47fc-a0b8-69c81af903fb/resourceGroups/ndss-dev-integration/providers/Microsoft.Web/sites/ndss-dev-integration-fa-d365-api-poll/troubleshoot)

Please check and let us know if you are able to solve the issue with this information.

**Comment by John-Bosch** [comment]
Thanks for the feedback @v-bbalaiagar.

The "Always On" I had noted and am in the process of fixing in our deployment scripts. These functions have recently come off of a consumption plan so couldn't have always on in the past. Are you saying then that the soft restart will only succeed in re-reading the application config if the function is actually running? We have a few functions that we shutdown overnight to stop them sending to down stream resources that aren't available so I will need to take that in to account if that is the case.

The socket leaking I will need to investigate. That function should be using a singleton HttpClient object that is only created once. I will do a code review to work out where the leak could be coming from.

**Comment by John-Bosch** [comment]
I thought about this more overnight and did some more investigating this morning. The :Always On" flag is enable on all of our Azure Functions, and has been for a few months now so I can discount that being an issue.

I am now mostly focusing on the fa-d365-api-poll function as that is the one giving me the most grief. This function is shut down over night by a scheduled logic app via the Azure management API. However, as I suspected that the soft reset may not work if the application was stopped so I have rescheduled the key rotation to happen at a time that the function is running. I will provide another update once that happens.

**Comment by John-Bosch** [comment]
Thanks for closing this as stale, even though I had responded!

I have now tested this with a clean and very simple function and am still convinced that doing a restart action via the Azure Management API (both with and without the softRestart) no longer forces a re-reading of key vault values in configuration settings. Consumption versus App Service Plans with or without "Always On" doesn't seem to make any difference either.

All the HTTP triggered function is doing is reading configuration via an injected IOption<X> and writing those configuration values in the response. It isn't until I force an "Update website" operation by manually updating the configuration settings that the response contains the new key vault secret values. Issuing a "Restart Web App" operation via the Azure Management API is no longer sufficient.

Just for completeness, here are the test functions details:

Timestamp: Thu Apr 28 2022 10:26:30 GMT+1000 (Australian Eastern Standard Time)
App version: V3
App Name: jb-function-options-test
Region: Australia East

**Comment by ThomasPe** [comment]
The only reliable way I found to force an update from the Key Vault is by breaking the reference on purpose and the fixing it again.
