### ISSUE TITLE
No auth required for Admin API for local calls?

### ISSUE THREAD

**Issue by changeforan** [Azure/azure-functions-host#8291]
https://github.com/Azure/azure-functions-host/blob/3b9449e5870ba98ad4b08f4cde18f22bb631d2f9/src/WebJobs.Script.WebHost/Controllers/HostController.cs#L325

Hi, I tried to restart my Azure Functions via this Admin API: `admin/host/restart` and I found that if I call it from local - use a postman - it works with no authentication.
![image](https://user-images.githubusercontent.com/7800290/162385672-0beda92c-ecaa-4d4c-b116-25ee75cde346.png)
I can call this API inside my function, it also caused the Function host service to restart.
```
await new HttpClient().PostAsync($"http://localhost:{portNum}/admin/host/restart", null).ConfigureAwait(false);
```
My question is:
Is this by default? No auth required for local calls. Or is this a bug?

**Comment by Ved2806** [comment]
Hi @changeforan Thank you for the feedback, we will discuss this internally and let you know about the findings.

**Comment by Ved2806** [comment]
Hi @mathewc @brettsam Could you please look into this issue? Thanks.

**Comment by mathewc** [comment]
For ease of local testing, auth is not required when running locally. This is by design and mentioned in the documentation [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cwindows%2Ccsharp%2Cportal%2Cbash#start):

_"When running locally, authorization isn't enforced for HTTP endpoints. This means that all local HTTP requests are handled as authLevel = "anonymous""_

**Comment by changeforan** [comment]
thanks, Mathew.
