### ISSUE TITLE
Add support for logging without invocation id

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-host#8304]
Currently, for out-of-process applications, logging happens only if the log message ([RpcLog instance](https://github.com/Azure/azure-functions-language-worker-protobuf/blob/dev/src/proto/FunctionRpc.proto#L496)) is associated with an invocation id. We have use cases like below where logging without an invocation id is a valid use case. 

1. [Logging using an ILogger\<T\> instance does not work when it is not part of a function execution](https://github.com/Azure/azure-functions-dotnet-worker/issues/702)
2.  [Add startup logger to log startup code failure](https://github.com/Azure/azure-functions-dotnet-worker/issues/850)

[This](https://github.com/Azure/azure-functions-host/blob/dcfd7fc1458da020de2c3f49b1d9672b1e1bc229/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs#L696) is the code which checks the existence of invocation Id before executing the logging code, in host.

**Comment by liliankasem** [comment]
This is specifically for customer code right? For worker code, you can use the system category to log things without an ID

**Comment by fabiocav** [comment]
The key ask here is for the ability to send user level logs to the host. The mechanism we expose today enables infrastructure (worker) level logs to flow through, but doesn't apply to user level logs. 

The work being done by @brettsam (Worker AI integration) should address this requirement, but this issue is also captured by #8222 . So we're closing this issue as a duplicate.

Link to the AI PR: https://github.com/Azure/azure-functions-dotnet-worker/pull/944
