### ISSUE TITLE
Anyway to call Dispose on value created and provided by an extension using IValueProvider IBinding IBindingProvider

### ISSUE THREAD

**Issue by drdamour** [Azure/azure-functions-host#8482]
#### Is your question related to a specific version? If so, please specify:
function runtime v4 on dotnet 6

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
I have extensions that provide values using the IValueProvider (via IBinding, and IBindingProvider) and they work great, but i went to add a new provided value but this one turned out to be something that implements IDisposable...and it certainly doesn't make sense for every function i have to call Dispose() directly.  IS there a hook/lifecycle that allows me to property dispose of this provided value in my extension?

I tried looking at some of the existing extensions that i figured would have to do something like this, but i couldn't find anything in particular that was calling Dispose, since most of them are getting their Disposable things from the DI container and they aren't per request from what i could see.  I thought for sure the SQL binding would have to dispose of the command, but i just couldn't quite trace through to it.

**Comment by Ved2806** [comment]
Hi @fabiocav Could you please help with this?

**Comment by mathewc** [comment]
IValueProviders themselves are disposed [here](https://github.com/Azure/azure-webjobs-sdk/blob/4e287eb443e2445a298a8a959f7cd01efc46e2c9/src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs#L1013) after a function invocation, so you could technically implement IDisposable on your provider and dispose any values you've handed out.

The invocation pipeline itself doesn't dispose of the values directly and never has. I haven't heard of any issues due to that, and making a change to start disposing bound values might be breaking and lead to issues. The question is - who owns the lifetime of the values provided by the binding? I think having the source of the value (the IValueProvider) own this makes sense, and the existing IDisposable support for these providers achieves that. Does this work for you?

**Comment by drdamour** [comment]
@mathewc yeah that'll probably work ok.  does every func invocation create a new value provider?  Are they ever reused?

**Comment by mathewc** [comment]
Yes, each new invocation creates new value providers as part of the invocation bind process. You can verify that with your testing.

**Comment by drdamour** [comment]
> Yes, each new invocation creates new value providers as part of the invocation bind process. You can verify that with your testing.

well i saw it doing that, but doesn't mean it won't ever happen and is part of the contract.  my test cases can't possibly be exhaustive...unless you've solved p=np ;)

thanks!
