### ISSUE TITLE
Azure Functions Authentication during Development / local testing

### ISSUE THREAD

**Issue by klyse** [Azure/azure-functions-host#8536]
#### Question

My Azure functions (mostly written in C#) require HTTP authentication (`AuthorizationLevel.User`). I found many resources on how to configure OpenID on Azure but could not find much on how to setup the authentication locally during development.

The [function core tools](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cwindows%2Ccsharp%2Cportal%2Cbash) have a dedicated `--enableAuth` flag. Adding the `enableAuth` flag to the run command (`func start --enable-auth`) results in some more services being injected in the DI container. As far as I understand this disables the local default behaviour where the function `AuthorizationLevel` is ignored and instead performs the authentication steps. I could not find any documentation how this authentication pipeline works locally? How can I define the OpenID provider and how can I pass the Bearer token (I assume with the `Authentication` header)?

In the end I need `ClaimsPrincipal` to contain relevant user information provided by the Auth Token (Bearer) so that I can access the user context during local development.

**Comment by Ved2806** [comment]
Hi @klyse You may want to try [this](https://docs.microsoft.com/en-us/azure/app-service/configure-authentication-provider-openid-connect?toc=%2Fazure%2Fazure-functions%2Ftoc.json). Please let us know if it is helpful?

**Comment by klyse** [comment]
Hi @Ved2806, thanks for the answer but I am afraid this describes only how to configure the app service on Azure. I specifically asked on how to configure this locally for testing / debugging purposes.

**Comment by klyse** [comment]
Hi @Ved2806, this issue is not stale and I am still hoping for an answer🥹

**Comment by marcin-burak** [comment]
I've been working with .NET Azure Functions for some time and as far as I'm aware there is currently no way to run [Azure App Service Plan Authentication (EasyAuth)](https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization) while developing .NET Azure Functions locally.

When you enable EasyAuth for your Azure Functions in Azure (or any Azure Web App) all the HTTP traffic flows through dedicated [sidecar process](https://docs.microsoft.com/en-us/azure/architecture/patterns/sidecar) that authenticates all incoming HTTP requests with the configuration you provided in the Azure Portal and forwards the requests to Azure Function with all identity related information via specific HTTP request headers. Azure Functions is smart enough to extract all this identity data from the HTTP headers and populate the `ClaimsPrincipal` object for you.

All this works great in Azure but I don't believe there is any kind of local emulator for this critical sidecar process we call EasyAuth.

My current approach is to use a specific version `1.12.0` of [`Microsoft.Identity.Web` library](https://github.com/AzureAD/microsoft-identity-web) (specific version due to bug [described here](https://github.com/AzureAD/microsoft-identity-web/issues/1548)) and do all authentication and authorization work myself. I mostly call `AuthenticateAzureFunctionAsync` method at the beginning of the HTTP triggered function in order to authenticate the incoming HTTP request. 

It's not so developer friendly because there are some weird edge cases (e.g. calling another API on-behalf-of the user) you have to debug and find workarounds yourself or in GitHub issues but so far it gets the job done for me. You might also want to enable EasyAuth in Azure anyway and use [`Microsoft.Identity.Web` integration with EasyAuth](https://github.com/AzureAD/microsoft-identity-web/wiki/1.2.0#integration-with-azure-app-services-authentication-of-web-apps-running-with-microsoftidentityweb) to further bulletproof your solution (I haven't played around with this scenario yet).

All above mentioned tips I used with .NET6 v4 Azure Functions with **in-process model**.

There is an issue [here](https://github.com/Azure/azure-functions-dotnet-worker/issues/856) that currently has `Planned & Committed` status which describes the need to align Azure Functions AuthN/AuthZ with existing ASP.NET patterns which I am really looking forward to because it is critical for Serverless Web APIs. I absolutely love Azure Functions but from my perspective the AuthN/AuthZ is not very developer friendly and requires a lot of work to setup which hopefully will be addressed in the future.

**Comment by klyse** [comment]
Hi @marcinburak, thanks for the answer. Appreciate it. 
Your feedback confirms my long feared theory: it just doesn't work🥲
Authentication is so important it should work out of the box for a great experience imho.

By the way I found https://github.com/fmichellonet/AzureFunctions.Extensions.OpenIDConnect to handle authentication locally. Seems to work well.

**Comment by marcin-burak** [comment]
Library seems quite nice and should work, just a word of caution: the library uses `FunctionInvocationFilterAttribute` to invoke the authentication and authorization process of the incoming HTTP request. This attribute is known as a [function filter concept](https://github.com/Azure/azure-webjobs-sdk/wiki/Function-Filters) but it has been in preview since 2018 so there is no guarantee if it will work in the future and giving the fact that we can use the isolated process model it will remain in preview indefinitely. 

If you have no problem with using the isolated process model instead of in-process model, you can do the same exact thing using middleware which is GA and will be the new standard way of invoking authentication. [Here is an example](https://joonasw.net/view/azure-ad-jwt-authentication-in-net-isolated-process-azure-functions).

**Comment by marcin-burak** [comment]
Keep in mind that the library you linked only authenticates and authorizes the HTTP requests but if your Azure Functions need to call some other web API like [Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview) [on behalf of the user](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow), then you will need to write some additional code yourself to achieve that.

**Comment by klyse** [comment]
Thanks for another valuable feedback @marcinburak. I'll move away from HTTP triggered functions. Too many unresolved questions. Too many unknown variables for for me for now... I'll probably use Azure Container Apps and ASP.net core instead.

**Comment by klyse** [comment]
Hi @Ved2806, don't think this issue is closed/completed. Bottom line is that it's difficult to handle authorization and that should change in the future. So I think some issue should track the problem and hopefully resolve this in future.
