### ISSUE TITLE
Issue to run tests locally due duplicated package reference

### ISSUE THREAD

**Issue by wbail** [Azure/azure-functions-host#8571]
Issue to run tests locally due duplicated package in the csproj.

#### Investigative information

N/A

#### Repro steps

1. clone the repo
2. try to run a test from "WebJobs.Script.Tests" project in ***dev*** branch.

#### Expected behavior

Run the tests successfully.

#### Actual behavior

The project doesn't compile.

#### Known workarounds

Remove the duplicated reference (the older one)

#### Related information 

Provide any related information 

* Links to source: https://github.com/Azure/azure-functions-host/blob/bfecdc29f78cd29cb6a8d01181d9f24ca79fe3a8/test/WebJobs.Script.Tests/WebJobs.Script.Tests.csproj#L56

<details>
<summary>Source</summary>

```
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.4.0" /> // REMOVE THIS ONE
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
```
</details>

**Comment by liliankasem** [comment]
Oddly, I have been able to build and run the tests in the dev branch without any issues. But agree that we should probably remove the dup. Right now we are not able to merge your PR because of this issue #7923, so I've created a PR to address it here: https://github.com/Azure/azure-functions-host/pull/8579
