### ISSUE TITLE
Confusing readme

### ISSUE THREAD

**Issue by DBJDBJ** [Azure/azure-functions-host#8637]
_...These libraries are the runtime used by [Azure Functions](https://azure.microsoft.com/en-us/services/functions/). The runtime builds upon the tried and true [Azure WebJobs SDK](https://github.com/Azure/azure-webjobs-sdk) - this library just layers on top to allow you to "script the WebJobs SDK"..._

When developing **not** scripted AF in C# one uses  `Microsoft.Azure.WebJobs` and `Microsoft.Azure.WebJobs.Hosting`, not `WebJobs.Script`, the above paragraph to me suggests otherwise. AFAIK there is no dependency of  Azure Functions towards  `WebJobs.Script`?

Also. The title of this repo is confusing. Perhaps it should be: `azure-functions-scripting-host`?

All this on top of a few years of confusion about Functions implemented as a kind-of-a WebJobs, while conceptually being different. 

AF is a microservice, WebJob is not.

**Comment by Ved2806** [comment]
Hi @DBJDBJ Thank you for the feedback, we are discussing this issue internally and let you know about the findings soon.

**Comment by mathewc** [comment]
I have a PR out to update the readme https://github.com/Azure/azure-functions-host/pull/8647, which should address the questions asked.

To respond specifically to your questions @DBJDBJ:

- Yes, if you're just authoring a WebJob outside of Azure Functions, you may optionally use the WebJobs SDK, not libraries from this repo.
- [Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/) is a managed serverless platform and this repo contains the code used for that service. Azure Functions shares a lot with WebJobs since it's built on the WebJobs SDK, so inherits its trigger and binding programming model.
- [WebJobs](https://docs.microsoft.com/en-us/azure/app-service/webjobs-create) is a separate service capability provided by Azure that allows you to run background tasks defined by an exe or script. Use of the WebJobs SDK is optional when creating WebJobs.

**Comment by DBJDBJ** [comment]
> To respond specifically to your questions @DBJDBJ:

Thanks @mathewc ,  I know what are WebJobs :) I think it is forever confusing for the thinking developer implementing AF by using WebJobs packages. There is no `Microsoft.Azure.Functions` package.

> [Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/) is a managed serverless platform and this repo contains the code used for that service. 

How? Where? 

> Azure Functions shares a lot with WebJobs since it's built on the WebJobs SDK, so inherits its trigger and binding programming model.

It seems AF base is entirely inside two WebJobs packages.  I do not know od any AF specific package beside what is in this repo.

Also, a "normal" AF code is not a script. C# makes DLL's, they get deployed to A and they run on the A. Quite unlike anything from the scripts in the samples, [part of this repo](https://github.com/Azure/azure-functions-host/tree/dev/sample). They all can use an web app to run. As the readme also says:

_"... When hosted in an [Azure Web App](http://azure.microsoft.com/en-us/services/app-service/web/) this means there is no compilation + publish step required. Simply by modifying a script file, the runtime will load the new script content + metadata,.."_

I just do not see how is "scripting" involved in coding, deploying and running normal AF.

Users do not use directly `Microsoft.Azure.WebJobs.Script`. Usage might be "hidden" somewhere; but where?

Is this all just a terminology issue? A diagram might help. I would love to see how is package `Microsoft.Azure.WebJobs.Script` fitting into the running AF application with one user-coded AF dll, inside it?

**Comment by mathewc** [comment]
Azure Functions leveraged the preexisting work in the WebJobs SDK because we already had an extensible trigger/binding model there that we also wanted for Azure Functions. The "Script" naming is historical in this repo because originally we didn't support the precompiled .NET DLL model for authoring functions in v1. So function code was provided as code files ("scripts"), and the Functions Host loaded and ran them on invocation.

You're right that for functions hosted by Azure Functions, customers don't reference any of the libraries in this repo. The runtime host is loaded behind the scenes by the platform, and it in turn loads the user's Azure Functions resources (.NET dlls, C# csx script files, Node.js files, Powershell scripts, etc.). Thus the Functions runtime isn't part of the customer's payload.

**Comment by DBJDBJ** [comment]
Many thanks, @mathewc , it seems we are getting somewhere :) 

This is gold:

> The "Script" naming is historical in this repo because originally we didn't support the precompiled .NET DLL model for authoring functions in v1. So function code was provided as code files ("scripts"), and the Functions Host loaded and ran them on invocation.

Correct me if I am wrong but that requires a completely new intro to the readme in this repo. And some serious re-naming too. Which is difficult by now, I am perfectly aware of that.

Unfortunately, **correct** naming is hard. But essential. As is the clean up-to-date Architecture. Which is simply just not documented here, it seems. But now we know, it does exist. Thanks.
