### ISSUE TITLE
Function continue to process even after host has stopped due to timeout, leaves item in the queue and results in duplicate processing of same message

### ISSUE THREAD

**Issue by nitish28** [Azure/azure-functions-host#8814]
Function sample code:
for (var i = 0; i < 4; i++)
                {
                    log.Info($"Next visible {i} : {myQueueItem}");
                    await Task.Delay(1000);
                }

Host.json settings:
{
  "queues": {
    "maxPollingInterval": 1000,
    "visibilityTimeout": "00:00:10",
    "batchSize": 4,
    "maxDequeueCount": 5,
    "newBatchThreshold": 2
  },
  "functionTimeout": "00:00:02"
}

Message re-appears in the queue after 10 minutes, However in setting visibility timeout is: 10 seconds. 
![image](https://user-images.githubusercontent.com/13083021/193478173-d2a70585-5e3b-4566-a377-433ae8a151d4.png)

Output:
![image](https://user-images.githubusercontent.com/13083021/193477947-cbeb1c11-1498-4c83-9947-846a72813c16.png)

Question: Why is it still processing the message once the host has stopped? If we look at the workflow, it has completed the queue message processing but it leaves the message in the queue which causes the duplicate processing of the same message.

**Comment by ramya894** [comment]
@nitish28 Please check the below SO for duplicate processing of same message.
https://stackoverflow.com/questions/50168173/azure-function-app-processing-same-message-2-times

If you still face the issue, please provide us the functiona app name, timestamp and invocation id details so that we can check for the logs in our system and update you further.
