### ISSUE TITLE
Function App Host shut down when network is unavailable. TimerTrigger only

### ISSUE THREAD

**Issue by tranduy216** [Azure/azure-functions-host#8850]
Lately, the Azure function app suddenly stopped and does not restart automatically (Run under App Service Plan + Always on)
Before the function app stop, there are some NoSuchHostIsKnown exceptions

After some investigation, I can reproduce on local host following steps:

**Steps:**
1/ Create a Timer Trigger Function (1 minute interval)
2/ Make sure network is available
3/ Start the function app and wait to Function app complete to start
4/ Network unvailable
5/ Waiting for 1 ~ 2 minutes

**Expected:**
Host does not shutdown. Timer Trigger log error

**Actual:**
Error log show
Host shutdown and does not restart
![image](https://user-images.githubusercontent.com/52338709/196108218-99fd7dd0-f11e-4baa-a856-a4ccdc23fc35.png)

**Environment:**
Azure Function SDK 4.1
Window platform
NET.Core

**Mitiagation:**
Separate HttpTrigger & Timer Trigger to different function App
Create health check for Function App

**Comment by ramya894** [comment]
@tranduy216 Please provide us the function app name, invocation id and time stamp details so that we can check for the system logs and investigate further.

**Comment by tranduy216** [comment]
@ramya894 , you can easily reproduce on local machine.
Just disable network after function app started (Function app requires TimerTrigger to reproduce).

On other hand, I will try to make exception on TimerTrigger (throw new exception) to test behavior.

In case, you really need more information, please check the support ticket: 2210130030000249.

Thanks,

**Comment by tranduy216** [comment]
I throw Exception at the beginning of Timer function with network available.
Function App show error without shutting down.

So the issue only happens with TimerTrigger + network unavailable while it is running.

**Comment by mathewc** [comment]
This is by design. TimerTrigger uses a blob lease mechanism "singleton" https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger#singleton-locks to ensure that only 1 of N scaled out instances of your app is running the timer. That requires network connectivity for lease acquisition + renewals. It's by design that if an instance either can't acquire the lease or can't renew it when it already has it, it's a fatal error and we stop the host to ensure that we're not continuing to run the timer when another instance may have acquired the lease. This ensures the guarantee that the timer is only ever running on a single instance.

**Comment by tranduy216** [comment]
I agree we can stop the host to avoid trigger timer again. But why does the application not restart?

**Comment by mathewc** [comment]
When running in Azure as you are (App Service Plan + AlwaysOn) when the process crashes, AlwaysOn should cause a new instance of your app to start.

**Comment by tranduy216** [comment]
The function app has enabled Always On, but when the connection lost to storage, Function App host had stopped and then it did not restart/create new instance.
The Function App only work after I restart.
![image](https://user-images.githubusercontent.com/52338709/199379217-af060e02-6dc2-4246-aaaa-8e33da3fd950.png)

The expectation is that Function App is high availability, no matter what exception, error, unexpected shutdown, it needs recovery mechanism.
My Function App = Timer Trigger + HTTP trigger, when the Timer issue happens, I cannot call HTTP request.

**Comment by mathewc** [comment]
Internal logs show that the reason your site was down during this period was because the WEBSITE_RUN_FROM_PACKAGE blob URL configured for the app was returning 404 when our platform was attempting to activate your site and download the package on startup. If you have a CRI I can share these detailed logs on that CRI, or you can create a CRI via the normal process if you need this to be investigated further. But it looks to me like this was an invalid app configuration that was fixed on your end, presumably by updating/fixing the package URL.
