### ISSUE TITLE
Functions hosts is not calling Flush method of the IAsyncCollector 

### ISSUE THREAD

**Issue by shrohilla** [Azure/azure-functions-host#8857]
For the out of proc apps the Functions hosts is not calling the Flush method of the binding collector in there pipeline of IAsyncCollector.
We tried to create a python function app with kafka trigger with multiple events and execute that by integrating the python worker with the function hosts on our local setup.
We set the breakpoint in Flush method of the Kafka extension's [collector](https://github.com/Azure/azure-functions-kafka-extension/blob/dev/src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaProducerAsyncCollector.cs) but when we hit the events for producing them back in the kafka broker the Flush method was never called in the pipeline post the [flow](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Binding/FunctionBinding.cs#L199)

Sample function is on [link](https://github.com/Azure/azure-functions-kafka-extension/tree/dev/samples/python/KafkaOutputMany)

cc @fabiocav @mathewc @lpapudippu

**Comment by shrohilla** [comment]
Sample payload -- {"ordertime":1235,"orderid":5,"itemid":"Item_184","address":{"city":"Mountain View","state":"CA","zipcode":94041}} for the body and key we are using as the iteration count.

**Comment by mathewc** [comment]
The executor will only call Flush if your value provider is an IValueBinder ([here](https://github.com/Azure/azure-webjobs-sdk/blob/4e287eb443e2445a298a8a959f7cd01efc46e2c9/src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs#L959)). Likely you're only implementing IValueProvider, not [IValueBinder](https://github.com/Azure/azure-webjobs-sdk/blob/3f4ec78be9f43bb041937425ced00b341883aa42/src/Microsoft.Azure.WebJobs.Host/Bindings/IValueBinder.cs#L12).

If you're implementing the value binder/provider yourself, you'll call Flush yourself on your collector when the platform calls SetValueAsync. When you're using the fluent binding rules (e.g. like [this](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/003b07b98616463470367f5b42908b5c11bd7d2f/src/WebJobs.Extensions.CosmosDB/Config/CosmosDBExtensionConfigProvider.cs#L59)), it'll be called for you.

**Comment by shrohilla** [comment]
@mathewc could you please share the extension which is following this approach, I just want to understand the flow.
CosmosDB extension is not following this.
I searched the same in EventGrid extension but the IValueBinder binding I failed to search, so wondering if you can share some more details regarding this.

**Comment by mathewc** [comment]
The EventHubs extension supports Flush [here](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/src/Triggers/EventHubAsyncCollector.cs#L99), and the Flush gets wired up automatically because it's using the BindToCollector binding rule [here](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/src/Config/EventHubExtensionConfigProvider.cs#L78). Behind the scenes, that results in [this](https://github.com/Azure/azure-webjobs-sdk/blob/3f4ec78be9f43bb041937425ced00b341883aa42/src/Microsoft.Azure.WebJobs.Host/Bindings/AsyncCollector/AsyncCollectorValueProvider.cs#L49) value provider triggering the flush.

So if you're not using the BindToCollector model in your extension, your value provider will have to do the same thing in its SetValueAsync impl.
