### ISSUE TITLE
Visual Studio 17.4.x does not run Function App on WebJobs

### ISSUE THREAD

**Issue by vijayrkn** [Azure/azure-functions-host#8966]
Creating an issue on behalf of the VS customer: 
Problem: Cannot run function app locally after updating VS2022 to 17.4.2.

Details: Function app can run correctly if we change the package Microsoft.NET.Sdk.Functions from Version 4.1.3 to version 3.0.11

Error message: “Microsoft.Azure.WebJobs.Host: ‘localendpoint’ Can’t be invoked form azure WebKobs SDK. Is it missing Azure WebJobs SDK Attribute?”

This was previously working and now is not

Method of verification: reverted my local version to 17.2.6 to run a function app locally as HTTP endpoints.

More details available in the developer community issue: https://developercommunity.visualstudio.com/t/-Visual-Studio-174x-does-not-run-Funct/10222841

**Comment by NathanMcCarthyWegmans** [comment]
Solution discovered.
Azure Function Core Tools version 4.0.3971 and Function Runtime Version 4.0.1.16815 was the reason this was not working, forcing an update to the tools resolved the issue

**Comment by vijayrkn** [comment]
@NathanMcCarthyWegmans - Thank you for the confirmation. I will close this issue.

**Comment by NathanMcCarthyWegmans** [comment]
Might it be a requested feature to autoupdate the Azure Function Host tools or an easier interface to interact with them?

I ask this because I used NPM and had manually updated my version to the latest, but was still seeing Visual Studio use it's own, older version, that was causing the issue. It wasn't until I found the setting in Visual Studio to update the Azure Function Host tools that I was able to resolve the issue. Hence my initial belief that it was a Visual Studio bug

Thanks!
Nathan

**Comment by vijayrkn** [comment]
It should ideally auto update when a new project is created. As you mentioned, there is an option under tools-> options to force update to the latest version. 

We will discuss and see how we can improve the discoverability of these options. Thanks for raising them.
