### ISSUE TITLE
Need ability to detect if user code actually executed via FunctionResult

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-functions-host#8994]
#### What problem would the feature you're requesting solve? Please describe.
Checkpointing is a feature of the Event Hubs library and trigger that allows for keeping track of what events have been processed by an application. In the Event Hubs trigger, events are automatically checkpointed after TryExecuteAsync is [called from the Event Hubs listener](https://github.com/Azure/azure-sdk-for-net/blob/147364d19481439d9f205ebbd40ccd774e2715e5/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/src/Listeners/EventHubListener.cs#L198-L214). Customers have complained that if a host exception occurs, e.g. due to the host being scaled in, the events are still checkpointed even though the user code never actually had a chance to run. This can result in customers losing data as the checkpoint offset would not be an accurate representation of the processed events when this situation arises.

#### Describe the solution you'd like
As [described](https://github.com/Azure/azure-sdk-for-net/issues/28653#issuecomment-1133263081) by @mathewc in the issue that was filed against the azure-sdk-for-net repo to add this feature to the trigger, it would be sufficient if there was a flag on FunctionResult that the EventHubs trigger code can inspect to determine whether or not it is safe to checkpoint the current event.

The proposal here is to add something like:

```c# 
public class FunctionResult 
{
// ... existing properties
  public bool MethodInvoked { get; }
}
```

In the Event Hub trigger code, we would check this property before checkpointing:

```c#
   if (eventToCheckpoint != null && result.MethodInvoked)
   {
      await CheckpointAsync(eventToCheckpoint, context).ConfigureAwait(false);
   }
```

#### Describe alternatives you've considered
There does not seem to be a way to implement this feature purely on the extension side - it requires some new API surface in the Function host types. 

#### Additional context
Extension feature request - https://github.com/Azure/azure-sdk-for-net/issues/28653
ICM - https://portal.microsofticm.com/imp/v3/incidents/details/353810445/home

**Comment by jviau** [comment]
I think this needs more discussion on what you _actually_ want here. Can you clearly define what "user code actually executed" means? For isolated functions, does it include middleware? If so, do you need to differentiate between user middleware and extensions middleware? _Can_ you differentiate that?

I understand the intentions of wanting to do the "right thing" for the customer here, but we are trying to solve a fairly subjective definition of "user code". In dotnet isolated, I could have middleware which handles the event hub trigger and short-circuits the execution, meaning the final method is never invoked, but the event _is_ handled. Similarly, this middleware could come from an external library. What is the right thing to do here?

I would recommend inverting the condition: try to detect known cases where event hubs does _not_ want to checkpoint. Can we detect the scenario mentioned in your original description? Is there a specific exception thrown indicating the host is shutting down?

**Comment by JoshLove-msft** [comment]
> I think this needs more discussion on what you actually want here. Can you clearly define what "user code actually executed" means? For isolated functions, does it include middleware? If so, do you need to differentiate between user middleware and extensions middleware? Can you differentiate that?

It would mean that the user had a chance to interact with the event. Whether that is middleware or the function, if the user owns this code (or they have added it themselves via external library), then it should be treated the same. 

> I understand the intentions of wanting to do the "right thing" for the customer here, but we are trying to solve a fairly subjective definition of "user code". In dotnet isolated, I could have middleware which handles the event hub trigger and short-circuits the execution, meaning the final method is never invoked, but the event is handled. Similarly, this middleware could come from an external library. What is the right thing to do here?

The intent is to be able to determine whether the user had a chance to act on the event - whether via middleware or their function.

> I would recommend inverting the condition: try to detect known cases where event hubs does not want to checkpoint. Can we detect the scenario mentioned in your original description? Is there a specific exception thrown indicating the host is shutting down?

The exception is a TaskCanceledException, so we cannot use this to determine that the host was shutting down and the user did not have a chance to act on the event. If some other custom exception were thrown in this scenario, then it could be reasonable to use that as an indication that the host is shutting down and the user code did not execute. I was pointed to this [code](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs#L656) specifically by @liliankasem as the point in which the host determines whether to continue with invoking user function or not. If this were to do something like 
```c#
context.ResultSource.TrySetException(new HostShutDownException());
```
instead of what it currently does:
```c#
context.ResultSource.TrySetCanceled();
```
that could be a path forward. But I don't know if something like this would be considered a breaking change, hence the addition of a new property seemed to be the safest approach. The property itself could be inverted to be something like 
```c#
public bool HostFailure { get; }
```
if that would help reduce the ambiguity.

**Comment by jviau** [comment]
I understand your intention of wanting some way to tell if the user has had a chance to interact with the invocation. But that is **extremely** ambiguous as to what would qualify as "interacting" with the invocation. What if we have, or later introduce, an extension point that lives occurs early in the pipeline which circumvents this whole logic? What I am getting at is that I believe this approach would be extremely fragile - it is hard to define accurately and will most likely include many edge cases we cannot anticipate.

I agree your problem at hand does need to be addressed, just maybe not with this approach. For example, can you use `IHostApplicationLifetime` and see if `ApplicationStopping` cancellation is requested when you catch that `TaskCancelledException`?

**Comment by JoshLove-msft** [comment]
> I agree your problem at hand does need to be addressed, just maybe not with this approach. For example, can you use `IHostApplicationLifetime` and see if `ApplicationStopping` cancellation is requested when you catch that `TaskCancelledException`?

I'm not sure if that will definitively tell us whether the user function didn't execute - it's possible the user throws a TaskCanceledException _and_ the host is shutting down. Aside from this concern, this approach only _potentially_ addresses one such situation where the user code doesn't execute. As mentioned in @mathewc's [comment](https://github.com/Azure/azure-sdk-for-net/issues/28653#issuecomment-1133263081), there are other scenarios where this may come up:
> A similar scenario can happen if the function declares input bindings that fail for whatever reason. Input bindings are resolved BEFORE the user code is actually called, so in this EH case you'd also likely not want to checkpoint if one or more bindings failed. So we'll likely want to find a way to reflect that as well via FunctionResult.MethodInvoked.

**Comment by fabiocav** [comment]
Flagging this for discussion and planning.

**Comment by hrgsmms** [comment]
Hi team, just bringing to this thread that one of our customers is having data loss since Dec 2022 due this issue (currently talking with Shyju). 
We have already followed the suggestions for applying drain mode + retry.  However his approach is not working as is ending up on the exceptions "Invocation cancelled - exiting retry loop.".  With this we are on the pending for this fix.

**Comment by jviau** [comment]
> >  Input bindings are resolved BEFORE the user code is actually called

This is no longer true for dotnet isolated. Input bindings and other extension implementations are part of the middleware pipeline, and users can also insert into the middleware pipeline. User code, extension code, and even framework code is now all interleaved with one another. We cannot answer if "user code" executed let alone even define what that means. Even for in-proc it is possible for customers to hook into extension points and further blur what "user code" means. Additionally, what if something we determine that is _not_ user code is failing, what is event hubs behavior here? Is that message indefinitely retried? Does it dead letter? What if this failing piece of code is **intentional** and inserted by the user via some extension point?

I think we are jumping ahead and assuming having some flag for user code is the solution to this problem, I recommend we take a step back and evaluate this feature on its own merits: there are known scenarios where function invocations are aborted, and event hubs needs to identify when such scenario happens and avoid checkpointing. So we need to 1) identify these scenarios and 2) ensure there is a way for extensions to identify these scenarios.

**Comment by jviau** [comment]
@JoshLove-msft I recommend you make a change similar to this PR: https://github.com/Azure/azure-functions-durable-extension/pull/2456. This will let you avoid checkpointing on host shutdown.

**Comment by JoshLove-msft** [comment]
Thanks, will take a look.

**Comment by fabiocav** [comment]
Moving this to 145 while the discussion here is still active.

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft I recommend you make a change similar to this PR: [Azure/azure-functions-durable-extension#2456](https://github.com/Azure/azure-functions-durable-extension/pull/2456). This will let you avoid checkpointing on host shutdown.

I've added handling in https://github.com/Azure/azure-sdk-for-net/pull/36432 to avoid checkpointing when the function app is being scaled in or out. One thing we are still not sure of is whether it is possible that calling TryExecuteAsync might fail to execute the user's function when not in the situation where we are scaling in or out. If this scenario is possible, we would still have a gap where data loss could occur. @jviau, do you know if this scenario is possible?

**Comment by jviau** [comment]
@JoshLove-msft this is very difficult to determine as the definition of "user code" is not really definable from our standpoint. It depends on so many external factors we cannot (and should not) try to define what user code is here.

Take the dotnet isolated worker for example. There is the gRPC dispatch and then also on the other end there is an extensible middleware pipeline. What is "user code" here? Is it when gRPC is dispatched? Is it when it has reached some point in the function pipeline? But being an extensible pipeline, it is a black box to us. We cannot answer what is "user code" within that pipeline. There is the function invocation at the end of the pipeline sure, but anything within that pipeline could short circuit the invocation with a result (or failure). This is much like AspNetCore.

Even in the case of ServiceBus, a customer could write their own middleware which intercepts SB trigger invocations and handles them without ever reaching the actual function at the end of the pipeline. This is all by design and an intentional extensibility point for the customer. We do not want to add constraints to this, it must remain a black box.

Attempting to infer what user code is will always be an incomplete solution here and most likely cause more issues than it solves. The best option I see is to find specific well-defined scenarios where you know checkpointing should be avoided and address those - such as on host shutdown.

As for `TryExecuteAsync` failing due to some bug in our code, well it is just that: a bug. We need to identify and fix the bug. Unfortunately, just with the user code issue above, it is not feasible to know at runtime if a failure is from user code or framework code.

**Comment by JoshLove-msft** [comment]
We ended up applying the workaround based on https://github.com/Azure/azure-functions-host/issues/8994#issuecomment-1523798908.

**Comment by jviau** [comment]
Ah great - is this okay to close then?

**Comment by JoshLove-msft** [comment]
Yes, thanks
