### ISSUE TITLE
Azure function - Linux based - isolated process - .net 6 - failure to execute function

### ISSUE THREAD

**Issue by clientbala** [Azure/azure-functions-host#9047]
We are seeing the below error at the time of function execution.

Error:
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: An HTTP/2 connection could not be established because the server did not complete the HTTP/2 handshake.", DebugException="System.Net.Http.HttpRequestException: An HTTP/2 connection could not be established because the server did not complete the HTTP/2 handshake.

Environment Setup:

1. Linux based App Service plan
2. Azure function app - dotnet isolated
3. .Net 6 framework
4. Azure function - V4
5. **VNet Integrated**

The function works, if we remove the VNet integration. Similar issue was raised before here as well - https://github.com/Azure/azure-functions-dotnet-worker/issues/518

**Comment by fabiocav** [comment]
@clientbala can you make sure you're running on the latest versions of the SDK and Worker packages and verify whether this is still an issue?

Thanks!

**Comment by mathewc** [comment]
@fabiocav Reactivating this because I'm working a CRI now where this is happening. Also, if you run a query, you can see this is actively happening for a small number of apps. I spot checked these and they all seem to be Linux Premium/Dedicated w/ VNET.

All("FunctionsLogs")
| where PreciseTimeStamp > ago(1d)
| where Level == 2
| where Summary startswith "Language Worker Process exited"
| where Details contains "An HTTP/2 connection could not be established because the server did not complete the HTTP/2 handshake."
| summarize count() by AppName
