### ISSUE TITLE
Developing Azure Function Service Bus Triggers on Mac

### ISSUE THREAD

**Issue by jmarbutt** [Azure/azure-functions-host#9088]
I have a simple Service Bus trigger and I can develop with it on Windows without any issue. But when I am using the trigger on my Mac I get this error:

```
Put token failed. status-code: 401, status-description: InvalidSignature: The token has an invalid signature..

Message processing error (Action=Receive, ClientId=MessageReceiver1my-topic/Subscriptions/my-sub, EntityPath=my-topic/Subscriptions/my-sub, Endpoint=my-dev.servicebus.windows.net)
```

The function is the boiler plate Service Bus function:

```c#
namespace MyApp.Functions;

public static class MyFunction
{
    [Function("MyFunction")]
    public static void Run([ServiceBusTrigger("my-topic", "my-sub", Connection = "ServiceBusConnection")] string mySbMsg,
        FunctionContext context)
    {
        var logger = context.GetLogger("MyFunction");
        logger.LogInformation($"C# ServiceBus topic trigger function processed message: {mySbMsg}");
        
    }
}
```

I updated my nuget packages to the following:

    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.10.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.7.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.7.0" />

I have copied my `local.settings.json` so that it matches what's on my Windows machine which runs fine. 

**UPDATE** After much testing, this only appears to be happening when running from Rider OR Visual Studio. I have the Azure tools installed and all other functions work correctly. If I run `func start` it runs fine.

How do I fix this issue?

**Comment by liliankasem** [comment]
@jmarbutt sorry for the delayed response, we must have missed this issue. Are you still seeing the same problem with all the latest packages?

If you are still seeing this issue:

I use a MacBook myself and was not able to repro the issue you mentioned - I was able to run and debug the service bus function without issues in VS Code. Are you suggesting the issue is only in Rider or plain old VS mac? The error message suggests some sort of misconfiguration of the connection to servicebus. I have no idea where `Put token failed. status-code: 401, status-description: InvalidSignature: The token has an invalid signature..` is coming from - I search the SB and Host codebase and we don't output any errors like this, can you share the full stack trace and logs?
