### ISSUE TITLE
Customize default route on Azure function

### ISSUE THREAD

**Issue by nciross** [Azure/azure-functions-host#9092]
I know that we can disable default page on azure function using AzureWebJobsDisableHomepage but how customize it ?
other question how return a default html page when error occur.

**Comment by liliankasem** [comment]
In order to have a custom handler for the "homepage" route (root), you'd need to define an empty HTTP trigger route and set the route prefix configuration to an empty value. The route prefix configuration would be done in host.json:

`"extensions": { "http": { "routePrefix": "" } }`

In C# you can set the route property to an empty string:

`[HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = "")] HttpRequestData req`

For error handling, we don't have anything that can be used outside of the function flow.
