### ISSUE TITLE
Regular Microsoft.Azure.WebJobs.Script.Description.FunctionInvocationCanceledException "The invocation request with id '<id>' was canceled before the request was sent to the worker."

### ISSUE THREAD

**Issue by ErikRosengren-work** [Azure/azure-functions-host#9387]
Function app regularly throws FunctionInvocationCanceledException when being called by other service. 

From the other service we can see that the request takes a long time and is then cancelled after 10+ seconds. In the most recent occurrences of this we get requests less than a second before that we receive in the function app code and respond to as expected, but the second request that times out never reaches the function code for our function app. As far as we can tell this is not because of cold starts because we have the first request that completes as expected less than a second before the request that fails and throws the error.

#### Investigative information

Please provide the following:

- Timestamp: 
- Function App version: 4.23.0.20886
- Function App name: 
- Function name(s) (as appropriate):
- Invocation ID: 8070e284-acf7-404a-afde-f8247eae8b6f
- Region: North Europe

#### Related information 

Provide any related information 

* Programming language used: C#

**Comment by liliankasem** [comment]
Hello, please open a support ticket for this. The issue usually due to scaling or moving of worker instances, or if there is an issue with your function app code.

**Comment by fabiocav** [comment]
Flagging this item for discussion to understand what changes we can make here to make this clearer.

**Comment by nhuurnink** [comment]
My isolated durable function apps are full with TaskCancelledException's every day. I don't understand why exception's within Azure Function's infrastructure are popping in my logs.

I am waiting for months now for a solution and have a long lasting support ticket with Azure support that doesn't get me anywhere. Could someone look into this, please?

**Comment by nhuurnink** [comment]
Any updates? All fun and great that thousands exceptions are being raised every day because of a "feature", since this is apparently by design. I wished we never upgraded to .Net 7 + Isolated mode by now.

I would hope that someone in the product team actually figures out that this should be a priority.

**Comment by fabiocav** [comment]
@nhuurnink there are different conditions that may lead to this scenario, some were covered by @liliankasem above, but another cause, which based on the context I have, is what we see in your application, is due to client disconnects.

This is something that was previously not surfaced, and would lead to unpredictable behavior as you're attempting to handle a request and write to the response when the client is gone. The host now detects this, logs the message you're seeing and short circuits the invocation. Prior to this, if you had similar issues with client disconnects, the request would still flow to the worker, causing it to handle and process the invocation, but leading to failures (in some cases, silent ones), in the return path.

We're discussing changes to this to help eliminate some of the confusion this log is causing. We're considering options like verbosity changes or a mode that would enable the invocation to flow with a signaled token, buts I'd love to get your feedback on the behavior you'd like to see with the client disconnect scenarios you're experiencing.

Thank you!

**Comment by nhuurnink** [comment]
@fabiocav what I've understood from my support ticket is that there is no actual "problem" in my case, every requests is eventually handled appropriately.
Assuming this is correct, then I don't want to see any exceptions in my logging, as there is nothing that I can do about this issue.

So my approach to this matter is simple:
- If I need to change my software, I want Exceptions
- If I can't do anything about it, then it's an Azure Functions infrastructure problem, and the functions are handled properly slightly later, then I don't want to be informed about it. I'm using Consumption Plan, so my application is designed to deal with deferred executions and cold starts.

**Comment by nhuurnink** [comment]
Did something change a few days ago? I don't get the exceptions anymore in my Application insights.

**Comment by liliankasem** [comment]
> Did something change a few days ago? I don't get the exceptions anymore in my Application insights.

We haven't made any changes to this area that I'm aware of
