### ISSUE TITLE
Looking to increase performance of my Azure Function App (Consumption plan)

### ISSUE THREAD

**Issue by stevehizmi** [Azure/azure-functions-host#9437]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
Python

#### Question
I have 5 functions deployed, where one of the functions fails to finish in under the 10 minute time limit. 
This function processes a pdf and converts it into a csv (pdf is about 1000 pages).
When viewing the live metrics, about 5 servers are available but all are around 2-3% CPU utilization. The servers go offline as the function runs until there are none left in some cases.

I get the error `host cpu threshold exceeded (82 >= 80)`. I decided to introduce asynchronous functionality with my functions and also included `FUNCTIONS_WORKER_PROCESS_COUNT` in my app settings and set that to 5. 
Now 2 / 5 servers can get the CPU utilization up to about 40% and my function gets to process about 300 pages before it does the same thing previously with stalling/throttling.

After the servers all go offline, it'll restart my function back to page 1. 

I'm looking for help in optimizing the host configuration and anything else that could improve performance. I'm not necessarily looking for options like upgrading plans or implementing durable functions because running the functions logic locally takes less than 2 minutes so I'm assuming I did not configure the azure function app appropriately. 

Is it possible to dedicate a server for one function? Would it make sense to stop all other processes once the pdf conversion starts? I'm not sure what else to include in here, so if there is more information to be needed please comment!

**Comment by bhagyshricompany** [comment]
Please refer the  document  for app service plan and some suggestions to optimize the configuration of your Azure Function app and improve the performance of your function:

App Service Plan: Make sure you're using an appropriate App Service Plan for your Azure Function. If your function is resource-intensive, consider using a higher-tier plan that offers more CPU and memory resources.

Function Code Optimization: Review your function code for any inefficiencies that might be causing it to use more CPU than necessary. Make sure you're following best practices for coding in Python.

Batch Processing: Since you're processing a large PDF with many pages, consider breaking down the processing into smaller batches. This way, you can parallelize the processing across multiple function instances.

Throttling and Retry Logic: Implement proper throttling and retry logic in your function code to handle potential transient errors, which might be causing your function to stall or fail.

Concurrent Execution: Configure the maximum concurrent executions for your function app. Azure Functions can run multiple instances of a function in parallel. Setting this value appropriately can help optimize resource utilization.

Concurrency Control: Depending on your use case, you might want to limit the maximum number of concurrent executions for your specific function to prevent excessive resource utilization.

Instance Warm-Up: Set up instance warm-up scripts or use the "Always On" feature to keep your function instances warm, which can help reduce cold start times and improve overall performance.

Scaling Strategy: Adjust your scaling strategy. If one function is resource-intensive, you might want to consider dedicating more resources to it, while keeping other functions separate.

Function Triggers: Review your function triggers. Make sure they are appropriately configured and not causing unnecessary function invocations.

Caching: Implement caching strategies, especially if there are portions of your PDF processing that can be cached and reused for subsequent pages.

Optimize PDF Processing: Look into optimizing your PDF processing library or approach. There might be ways to improve the efficiency of converting the PDF to CSV.

Azure Monitor and Diagnostics: Utilize Azure Monitor and Application Insights to gather more insights into the performance of your function. This can help identify bottlenecks and areas for improvement.

Resource Limits and Scaling Settings: Adjust the resource limits and scaling settings in your function app's configuration based on the resource requirements of your function.

Remember that Azure Functions are designed to be scalable and stateless, so the architecture should be designed to work well in a distributed environment. Additionally, using asynchronous processing can help in cases where there's a lot of waiting time involved, but you need to ensure your code is designed appropriately for asynchronous execution.

As for dedicating a server for one function, Azure Functions are designed to be serverless, meaning they dynamically scale up and down based on demand. While you can influence resource allocation, dedicated servers might not align with the serverless nature of Azure Functions.
